### ISSUE TITLE
CMake: Improve out-of-the-box experience

### ISSUE THREAD

**Issue by kamgha** [panda3d/panda3d#1072]
## Description
This is a follow-up for issue #1013. 

Running `cmake -DHAVE_AUDIO=OFF ..` without a thirdparty directory present should result in a build somewhat close to `makepanda --nothing`, it should build in any case (out-of-the-box). Currently, this renders into a few issues:

The CMake scripts

1. Assume that OpenSSL has been found (while it is not present on the system and result into the build failing). It does mention to set `HAVE_OPENSSL_OFF` to continue, but I'd rather expect it to default to it if it doesn't find it, like CMake does for the other libraries. It prints out a `+` and not a `(not found)` in the summary.

2. While CMake notices that it did not find Python, it will still assume that Python is enabled (see messages accordingly). While it even suggests to set `HAVE_PYTHON=OFF` to continue, it could default to `HAVE_PYTHON=OFF` like it does for the other libraries.
Note that Python 3.7 is in %PATH% in my case, but I'd probably expect CMake to look for a seperate Python shipped in thirdparty for a clean set-up.

3. The test for HAVE_SSE2 fails (according to the printed message), albeit the used compiler (MSVC 2015 on 64bit Windows) does support SSE2.

See the attached screenshots and markings for details:

![cmake](https://user-images.githubusercontent.com/7195621/102025668-d6533500-3d99-11eb-8f24-9044d59f67d7.png)

## Steps to Reproduce
Run `cmake -DHAVE_AUDIO=OFF ..` in a subdirectory from the Panda3D source.

## Environment
 * Operating system: Windows 7 64bit
 * System architecture: x86_64
 * Panda3D version: current git master as of 2020-12-13 (1.11.0pre)
 * Installation method: from source
 * Python version (if using Python): none in this case, or Python 3.7 in %PATH%
 * Compiler (if using C++): MSVC 2015, 64bit

**Comment by rdb** [comment]
Could you attach your logs so I can see how the test failed?

**Comment by kamgha** [comment]
For the SSE2 test, CMake adds `-msse2`, which is not a valid flag for MSVC.

[cm-log.zip](https://github.com/panda3d/panda3d/files/5720225/cm-log.zip)

**Comment by rdb** [comment]
As for points 1 and 2, these are by design.  The majority of people who are compiling Panda3D want to do so with Python and OpenSSL support, and doing otherwise is likely to be a mistake.  So we mark those packages as critical, and they need to be disabled explicitly in order not to build with them.

This is intended to fix the recurring support issue we have with makepanda, where people don't bother looking at the build output and then complain that "Panda3D doesn't work".

They show with a "+" because they are enabled, not because they are present.  Maybe this is confusing.  Perhaps we should show them with a "!" or something like that.
