### ISSUE TITLE
Feature request: Serializable CollisionTraverser and CollisionHandler

### ISSUE THREAD

**Issue by wanweiwei07** [panda3d/panda3d#1090]
## Description
CollisionTraverser (also CollisionHandler) needs to be serializable by pickle 

## Use Case
I am dumping a self-defined class which has a NodePath member variable as root and a CollisionTraverser member variable that detects collisions under the NodePath. CollisionTraverser is not serializable. I have to suppress it before pickle.dump and reinitialize it again after pickle.load. 

I am also looking forward to serialize the shaders under the NodePath, as mentioned in #408

**Comment by rdb** [comment]
Which collision handlers in particular are you using, that I should prioritise supporting?

**Comment by wanweiwei07** [comment]
Thanks for your quick reply. I am using a simple Queue.
My class.__init__ is like:

```
    def __init__(self, name="auto"):
        self.ctrav = CollisionTraverser()
        self.chan = CollisionHandlerQueue()
        self.np = NodePath(name)
        self.is_nprendered = False
        self.nbitmask = 0 # capacity 1-30
        self._bitmask_ext = BitMask32(2**31) # 31 is prepared for cd with external objects
        self.all_cdelements = [] # a list of cdlnks or cdobjs for quick accessing the cd elements (cdlnks/cdobjs)
```

**Comment by rdb** [comment]
I've implemented pickleability for the classes CollisionTraverser, CollisionHandlerQueue and CollisionHandlerEvent.  I may add additional handlers later, if requested.

Please note that you have to use the `direct.stdpy.pickle` module instead of the regular `pickle` module.  It behaves the same, except that it prevents duplication of Panda objects.  With the regular `pickle` module, every instance of a particular NodePath or CollisionHandler will end up creating a new copy.

You can try out this feature in this development build.  Let me know if you are encountering any problems.
https://buildbot.panda3d.org/downloads/8852c835fc6b362ce6e331c1e4d19fa9949930c6/

**Comment by wanweiwei07** [comment]
Thank you very much!
