### ISSUE TITLE
flatten_strong rotates tangent-space vectors of loaded models

### ISSUE THREAD

**Issue by Epihaius** [panda3d/panda3d#1179]
Hi,

It would seem that `flatten_strong` causes yet another problem with loaded model files:
the rotation on the node seems to be applied to the tangent-space vectors.

The screenshot below shows rotated copies of a simple plane model exported from Blender, with a normal map depicting a sphere applied to it:

![Rotated tangent-space vectors](https://user-images.githubusercontent.com/16452534/127047219-40426681-3189-43ee-954e-4d0470ee9338.png)

The following code sample should reproduce this issue:

```python
from panda3d.core import *
from direct.showbase.ShowBase import ShowBase
import simplepbr


base = ShowBase()
simplepbr.init(use_normal_maps=True)

# set up a light source
p_light = PointLight("point_light")
p_light.set_color((1., 1., 1., 1.))
light = base.render.attach_new_node(p_light)
light.set_pos(-100., 100., 100.)
base.render.set_light(light)

# set the initial camera transformation
mat = Mat4.rotate_mat(-45., Vec3(1., 0., 0.)) * Mat4.translate_mat(0., -30., 30.)
mat.invert_in_place()
base.trackball.node().set_mat(mat)

# load a model with normal mapping applied
model = base.loader.load_model("plane.gltf").find("**/+GeomNode")

# create a root node to copy the loaded model to
root = base.render.attach_new_node("root")

# copy the loaded model, setting not only a different position but also a different
# heading for each copy
for i in range(10):
    for j in range(10):
        model.copy_to(root).set_pos_hpr(i * 2. - 10., j* 2. - 10., 0., (i + j) * 36., 0., 0.)

# merge the geometry of the model copies into a single geom
root.flatten_strong()

base.run()
```

Here is the `plane.gltf` file used by the code above:

[plane.zip](https://github.com/panda3d/panda3d/files/6880681/plane.zip)

## Environment
 * Operating system: Windows 10 64-bit
  * Panda3D version: 1.10.9
 * Installation method: SDK
 * Python version: 3.7.9

**Comment by rdb** [comment]
flatten_light (and by extension, flatten_strong) is in fact intended to apply the rotation to the tangent-space vectors, so that the result of computing `p3d_ModelViewMatrix * p3d_Tangent` remains the same before and after applying the transformation to the vertices.

The problem with this model is in fact that the tangent-space vectors *aren't* being rotated.  This is because the model specifies the tangent column is using `C_other` instead of `C_vector`, so Panda leaves it alone.  Presumably, the reason panda3d-gltf chooses `C_other` is that Panda3D does not yet understand how to transform the special 4-component packed tangent space column used by glTF and simplepbr.

Support for 4-component packed tangent space columns is being tracked in #546.

**Comment by Epihaius** [comment]
Ah, I see.
Fair enough; I look forward to version 1.11 of Panda in that case.
