### ISSUE TITLE
SSBO support in shaderpipeline branch

### ISSUE THREAD

**Issue by lachbr** [panda3d/panda3d#1190]
## Description
I'm using the shaderpipeline branch and I have a use case for SSBOs in something I'm working on.  SSBO support in shaderpipeline and the SPIR-V implementation seems to be incomplete.  `OpTypeRuntimeArray` (variable-length arrays in SSBOs) is not handled by `ShaderModuleSpirV` and SSBOs don't get collected by `GLShaderContext` for SPIR-V modules.  Are there plans to get SSBOs working with shaderpipeline/SPIR-V any time soon?

**Comment by rdb** [comment]
IIRC SSBOs are supported just fine on the shaderpipeline branch, but the runtime-sized array is not.  We can just process it as a zero-length array, I think.  Unit test and/or PR would be welcome, I will not have time to work on it this week or next week.

**Comment by rdb** [comment]
Still working on this, but lost my progress due to stolen laptop, so I have to redo it.  It's a harder problem than it seems at first because of a current design issue in the shader pipeline.

The tricky part right now is changing the way parameters are being identified in the shader system.  Since the SPIR-V id is unique per stage, we can't use that.  So currently it relies on all (uniform) parameters binding points being identified by a location, and then the back-end turns this into a binding point, but this was a design mistake.  Firstly, SSBOs don't actually have a location in OpenGL, just the binding point.  Secondly, locations don't really apply in Vulkan, because data is passed through UBOs there, and resources through explicit binding indices, so assigning locations to everything only to have the Vulkan back-end strip them out again is kind of silly.  Using names isn't really convenient either because they may be stripped out.

So I think we need a map/array on Shader containing all the uniquified parameters, and we can refer to them by the index into this array.  And then we need to indicate how these parameters are bound to the state in a less fine-grained and specific way than ShaderMatSpec, because ShaderMatSpec only applies to some inputs and is duplicated out for each nested member, eg. `p3d_LightSource[n].shadowViewMatrix`.  And then the back-end needs to be responsible for splitting this out however it needs to into something like ShaderMatSpec while assigning implementation-specific locations (or offsets into an UBO) as needed.

At the same time, I've been hoping I can tackle the fact that the shader parameter binding system is ridiculously convoluted right now (to say nothing of the difference between ShaderPtrSpec and ShaderMatSpec) but things like the matrix generator are so ridiculously flexible right now that it's hard to come up with something that's not either a lot of work or sacrifices some aspect of the current functionality.

**Comment by rdb** [comment]
All that was a lot of work, but it's done! 4a91995082c5ea8690fe5738fd7a1f8b5c23b358 finishes SSBO support, also adding it to OpenGL ES 3.2.  Multi-dimensional of SSBOs are also supported.

Missing piece is reflection of SSBOs when compiling with legacy GLSL pipeline (it'll just show up as an empty struct if you try to query the internal members via the reflection API), but I'm not inclined to do the work to support that--just use the new pipeline (which is the default for GLSL 1.50+ shaders), or accept that you can't query the structure from Python.

**Comment by rdb** [comment]
One "regression" that could be noted is that if you had an array of SSBOs and were only accessing the second array index (ie. the first one is unused), you only had to supply the second index from Panda.  Now Panda will complain if the first array index isn't present either.  Just bind a dummy SSBO to shut Panda up.
