### ISSUE TITLE
Accessing raw keys through the polling interface

### ISSUE THREAD

**Issue by Schwarzbaer** [panda3d/panda3d#1211]
## Description
Raw keys are currently available only through the event API. I would like to be able to access them through the polling API.
My preferred implementation would allow me to simply prefix the string passed to `ButtonRegistry.ptr().find_button` with `raw-`.

## Use Case
I have written a key bindings abstraction over the polling interface due to it being easier to use for such a task than the event API. Now I would like developers to be able to use it while referring to keys by their physical position on the keyboard, not their label.

**Comment by rdb** [comment]
> My preferred implementation would allow me to simply prefix the string passed to `ButtonRegistry.ptr().find_button` with `raw-`.

This would require that raw buttons are represented by separate ButtonHandle objects; right now they use the same ButtonHandle objects.

I think we should either:
1. Add the polling interface for raw keys to (GraphicsWindow)InputDevice, or
2. Add an `is_raw_button_down` to MouseWatcher.

I slightly lean towards the former since it's already the most low-level place to get button states for input devices and avoids having to track extra state in MouseWatcher.

Apropos, I am a little dissatisfied with how the raw inputs are currently entirely separate from the "virtual" events; I think I would rather seek to combine them into a single event (which would be more efficient too). But, that just concerns the event API and not the polling API.

While I'm rambling, I'll also add my opinion that I don't think "virtual" keys should have ButtonHandles at all; there are potentially thousands of possible virtual keys, and I don't think we ought to register ButtonHandle objects for every possible Unicode code point. It makes more sense to use ButtonHandles for raw keys and strings for virtual key mappings.

**Comment by rdb** [comment]
Implemented in b5e92e29f5410ceabd2faaa53a05beabdf0c3cce - we can think about better approaches later if we want
