### ISSUE TITLE
Add support for Taranis X9D plus Input Device (gamepad)

### ISSUE THREAD

**Issue by git2323** [panda3d/panda3d#1218]
## Description
Please add support for the Taranis X9D plus RC transmitter (https://hobbyshop247.com/Taranis-X9D-Plus-2.4GHz). The device is connected with an USB dongle (https://www.mhm-modellbau.de/part-Frsky-XSR-SIM.php) to the PC. Currently the device can be seen and the buttons work. The 4 analog axes appear in the device_tester.py, but only move in a certain direction (see also attached video).

Here is the output from notify-level-device debug:

:device(debug): Started input device listener thread.
:device(debug): GIDC_ARRIVAL: \\?\HID#VID_0483&PID_5720#6&26a78d5&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
:device(debug): Successfully loaded hid.dll
:device(debug): Found gamepad device "FrSky Simulator" with 32 data indices, 1 button caps, 8 value caps
:device(debug): Found button range: DataIndex=0..23, ReportID=0, UsagePage=0x9, Usage=0x1..0x18
:device(debug): Found value: DataIndex=24, ReportID=0, UsagePage=0x1, Usage=0x36, LogicalMin=-127, LogicalMax=127
:device(debug): Found value: DataIndex=25, ReportID=0, UsagePage=0x1, Usage=0x36, LogicalMin=-127, LogicalMax=127
:device(debug): Found value: DataIndex=26, ReportID=0, UsagePage=0x1, Usage=0x35, LogicalMin=-127, LogicalMax=127
:device(debug): Found value: DataIndex=27, ReportID=0, UsagePage=0x1, Usage=0x34, LogicalMin=-127, LogicalMax=127
:device(debug): Found value: DataIndex=28, ReportID=0, UsagePage=0x1, Usage=0x33, LogicalMin=-127, LogicalMax=127
:device(debug): Found value: DataIndex=29, ReportID=0, UsagePage=0x1, Usage=0x32, LogicalMin=-127, LogicalMax=127
:device(debug): Found value: DataIndex=30, ReportID=0, UsagePage=0x1, Usage=0x31, LogicalMin=-127, LogicalMax=127
:device(debug): Found value: DataIndex=31, ReportID=0, UsagePage=0x1, Usage=0x30, LogicalMin=-127, LogicalMax=127
:device(debug): Discovered input device FrSky Simulator (connected), gamepad, 24 buttons, 8 axes

I uploaded a picture of the transmitter with the analog axes. They behave as follows in regards to the device_tester.py output:

Movement of the Analog Axes on the controller and the resulting movements in the device tester:

Move stick in the direction (1) => left_trigger moves to max right position
Move stick in the direction (3) => left_trigger does not show any movement (instead it sticks to max right position)
Move stick in the direction (2) => right_x moves to max right position
Move stick in the direction (4) => right_x does not show any movement (instead it sticks to max right position)
Move stick in the direction (5) => left_y moves to max left position
Move stick in the direction (7) => left_y does not show any movement (instead it sticks to max left position)
Move stick in the direction (6) => left_x moves to max right position
Move stick in the direction (8) => left_x does not show any movement (instead it sticks to max right position)

Thanks a lot

![taranis_x9d_plus_movements](https://user-images.githubusercontent.com/44967298/145722505-9a645d8f-6706-4167-a054-cd176278009f.jpg)
[VID_20211212_151833-1.zip](https://github.com/panda3d/panda3d/files/7699212/VID_20211212_151833-1.zip)

**Comment by rdb** [comment]
OK, I see what's going on. The mapping is consistent for a flight stick, with the right stick controlling roll/pitch and the left stick controlling yaw/throttle, but Panda is interpreting it as a gamepad, causing the mapping to be all screwy. As such I wonder if we should be mapping it as a flight stick as opposed to a gamepad, although we definitely could map it as a gamepad if desirable. What do you think? Instead of left_x, etc. the axes would be mapped as roll/pitch/yaw/throttle and Panda would map the buttons as generic joystick1, joystick2, etc. instead of start/menu/lshoulder/rtrigger/dpad, etc.

In any case, I've created a commit to correct the mappings (as gamepad), and [builds are available here](https://buildbot.panda3d.org/downloads/f01399bba875929d0f25c460c290f584f0f81608/). It'd be great if you could try it out as soon as you have some time. It may be possible to get this into 1.10.11 then, or it'll have to wait for the next release.

Particularly, it would be good to verify that the axes are correct and positive in the right direction (up and right should be positive).

I am not really sure how to explain the axes maxing out when going in the negative direction. I have added some more debug output to the above build; I would love for you to set `notify-level-device spam` and show me what kind of raw values you get when moving the axes in the negative direction.

**Comment by git2323** [comment]
For me it does not matter if it is mapped as a flight stick or as a gamepad.
I installed 1.10.11 and recompiled.
Up and right of both sticks are always going from 0(in the center) to 1. That looks good.
But now all sticks when they are full left or down they show a value of 1.02. When I move these sticks to the center the value increases from 1.02 to 2.01. Right at the center 2.01 switches to 0.
The attached output show the value of the axis. Axis 5 is moved from full negative (starting with 1.02) to full positive(1).
[Axes5_moved.txt](https://github.com/panda3d/panda3d/files/7777223/Axes5_moved.txt)
Also spam output has been uploaded.
[panda3d.log](https://github.com/panda3d/panda3d/files/7777230/panda3d.log)

What is really strange is when I attach the joystick to a linux system (debian), the device_tester does show the correct movement.

Thanks a lot for your effort

**Comment by rdb** [comment]
It looks like we're not doing sign-extension of 8-bit values correctly (I never caught it because unfortunately there is no gamepad in my pile of testing devices that reports negative values).  I've checked in a change to the `release/1.10.x` branch that makes the sign extension mechanism a bit more general.

I also made the device reported as flight stick, which probably makes more sense for this type of device.

I would be grateful if you could test this change.  If you need them, builds will appear shortly at [this link](https://buildbot.panda3d.org/downloads/0e9ea6706686ee810eea8171b96637b324763481/).

**Comment by git2323** [comment]
The device is now recognised as a flight_stick.
Up and right still works without error.
When moving the sticks from full left or full down towards the center I get values from:  -0 to -1.
I guess when the left and down half of the axis get reversed it should be fine.
Thank you and Happy New Year.

**Comment by rdb** [comment]
Third time's the charm:
https://buildbot.panda3d.org/downloads/500491e6c92b6a3b552a59cbe4359367a9934f8b/

**Comment by git2323** [comment]
Works like a charm. Thank you.
