### ISSUE TITLE
[MacOS] build from source: image not found; pzip

### ISSUE THREAD

**Issue by carstendroesser** [panda3d/panda3d#1219]
## Description

When building panda3d on MacOs 11.6 Big Sur from source, it crashes with the given error message.

```
dyld: library not loaded: libCg.dylib
referenced from: /Users/carsten/code/simulator/build/panda3d/bin/pzip
Reason: image not found
/bin/sh line 1: 22550 Abort trap: 6 bin/pzip -o /Users/carsten/code/simulator/build/panda3d/./models/box.egg.pz /Users/carsten/code/simulator/panda3d/models//box.egg
make[2]: *** [panda3d/models/box.egg.pz] Error 134
make[1]: *** [panda3d/CMakeFiles/models.dir/all] Error 2
make: *** [all] Error 2
```

## Steps to Reproduce
1. create a cmake project
2. clone panda3d as a git submodule
3. copy thirdparty-folder into previously cloned panda3d-folder
4. create folder build
5. call `cd build`
6. call `cmake ..`
7. call `make`

## Environment
 * Operating system: MacOS Big Sur 11.6
 * System architecture: Apple-Intel
 * Panda3D version: recent master branch
 * Installation method: built from source
 * Compiler (if using C++): AppleClang 13.0.0.13000029

**Comment by rdb** [comment]
You may need to copy libCg.dylib to the compiled lib dir and use `install_name_tool` (before the build) to make sure that it can be found.  Or, compile without Cg for now, or using makepanda.
The command would probably look something like:
```
install_name_tool -id "@loader_path/../lib/libCg.dylib" build/lib/libCg.dylib
```

This is a known issue, but we decided not to bother fixing it since we will remove the libCg library very soon (when the `shaderpipeline` branch is merged) and CMake support is still marked as experimental.

**Comment by carstendroesser** [comment]
Thank you, @rdb. How would compiling without Cg looklike? --no-Cg?

**Comment by rdb** [comment]
With CMake?  It should show up in the CMake GUI, but I think it would be `-DHAVE_CG=OFF`.  You may also need `-DHAVE_CGGL=OFF`.
