### ISSUE TITLE
True Threading is not enabled with public build?

### ISSUE THREAD

**Issue by duongnb09** [panda3d/panda3d#1241]
## Description
True Threading is not enabled with public build
## Steps to Reproduce
Install Panda3D via `pip install panda3d==1.10.11`. The doc [Threading — Panda3D Manual](https://docs.panda3d.org/1.10/python/programming/tasks-and-events/threading) says public builds enable true threading by default, but `Thread.isThreadingSupported()` returns False

## Environment
 * Operating system: Windows 10, Ubuntu 18.04
 * System architecture:
 * Panda3D version: 1.10.9, 1.10.11 * Installation method: pip
 * Python version (if using Python): 3.7

**Comment by rdb** [comment]
Cannot reproduce on Windows (with Python 3.8), or Arch Linux (with Python 3.10), both cases return True.

Are you sure you don't have `support-threads #f` in Config.prc somewhere?

**Comment by duongnb09** [comment]
It was a fresh install so I don't have` support-threads #f `in the config, but I used RenderPipeline (https://github.com/tobspr/RenderPipeline). Without render pipeline, `Thread.isThreadingSupported()` returns True. So, I guess render pipeline turns off something that might cause this problem. @rdb I believe you're the creator of the RenderPipeline and you could know this better. Any insights here?

**Comment by rdb** [comment]
No, I wasn't involved with RenderPipeline development; it was created by @tobspr.

However, these lines in the RenderPipeline configuration file are probably to blame:
https://github.com/tobspr/RenderPipeline/blob/d8c38c0406a63298f4801782a8e44e9c1e467acf/config/panda3d-config.prc#L140-L142

I imagine that it was disabled because the RenderPipeline doesn't use threading, with the idea that some overhead might be reduced.

**Comment by duongnb09** [comment]
Thank you for the explanation! So, this is not an issue with panda3d and I will close this topic!
