### ISSUE TITLE
CommonFilters doesn't work with non-default coordinate systems

### ISSUE THREAD

**Issue by pokepetter** [panda3d/panda3d#1289]
```python
from direct.showbase.ShowBase import ShowBase
from direct.filter.CommonFilters import CommonFilters
from panda3d.core import loadPrcFileData


app = ShowBase()
app.disableMouse()
myNodePath = loader.loadModel("panda")
myNodePath.reparentTo(base.render)
myNodePath.setPos(0,40,-4)

# # Changing the coordinate system breaks the filter and it seems
# # to stretch one row of pixels the whole height of the screen or something similar.
# # Uncomment the lines blow to reproduce error.
# loadPrcFileData('', 'coordinate-system y-up-left')
# myNodePath.setPos(0,-4,40)
# myNodePath.setHpr(0,90,180)

filters = CommonFilters(base.win, base.cam)
filters.setBloom()

app.run()
```

**Comment by Lekksii** [comment]
So, with some experiments in **CommonFilters.py** on line 297 I found:
```py
text += "  %s = vtx_position.xz * float2(0.5, 0.5) + float2(0.5, 0.5);\n" % (texcoord)
```
So I've changed XZ to XY -> `vtx_position.xz` to `vtx_position.xy` and it works to _y-up-left_ coordinate system!

_With this one XZ changing:_

**`Inverted`** filter work correct.
**`Cartoon Ink`** filter work correct.
**`Bloom`** filter **maybe** need to find vtx_position on 299 line or elsewhere.
**`Half pixel shift`** filter work correct.
**`Blur sharpen`** filter **maybe** need to find vtx_position on 299 line or elsewhere.
**`View Glow`** filter work correct. (Changing of color channel alpha, can be configured in CommonFilters.py).
**`Exposure Adjust`** filter work correct.
**`Gamma Adjust`** filter work correct.
**`Volumetric lighting`** filter also work correct.

**Comment by rdb** [comment]
Thanks for the testing.

CommonFilters shaders rely on the quad coordinates being in vtx_position.xz, but the `CardMaker.set_frame_fullscreen_quad()` used by FilterManager orients the quad differently depending on the coordinate system.

The easiest way to fix this would be to make sure that the quad is always generated in Z-up, and set the orthographic lens that renders this quad to Z-up (or perhaps just rotate the quad appropriately).  Though, this would be a breaking change for people currently using FilterManager in Y-up mode.

Alternatively, and perhaps better, the shaders could be changed to use the auto-generated texture coordinates of the quad rather than `vtx_position.xz`, which don't depend on the specific coordinate system.

**Comment by Lekksii** [comment]
Sure, will test it soon.

**Comment by Free4tlh** [comment]
I've tested most of the filters and I believe they are all working correctly. However I have limited exposure to shaders and how most of them should look. 

Thanks for your tests poke and Lekksii, and thank you rdb for the fantastic work!
