### ISSUE TITLE
incompatible with Vscode's pylance language server

### ISSUE THREAD

**Issue by BlackEagle1983** [panda3d/panda3d#1327]
## Steps to Reproduce

Hello . Your python version of this framework is not compatible with vscode's pylance language server because when I want to import content of **ai** and **core** modules vscode does not recognize them . Microsoft told me this issue is for lacking of type subs files . please solve this issue . 
![panda3d_2](https://user-images.githubusercontent.com/72033451/175804487-ec873f52-cf60-4b5c-9164-d1c416b1d595.png)
## Environment
 * Operating system: windows 10 pro 64bit
 * System architecture: 
 * Panda3D version: 1.10.11
 * Installation method: pip
 * Python version (if using Python): 3.10.5
 * Compiler (if using C++):

**Comment by rdb** [comment]
I am not sure why VSCode requires specific type stub files for the module, surely it can just import the modules and see what's in there?  Are you sure it doesn't just need the panda3d modules to be added to some path somewhere so that it can find them?

I am not opposed in principle to adding the type stub files if someone can do the work of researching what they should look like and writing a script to generate them (not particularly hard using the interrogatedb module).

**Comment by BlackEagle1983** [comment]
Yes . I am sure it needs type stube because when we use Jedi language server in vscode conents of panda3d modules appears But Jedi language server is slow . If you can add type stub files it will help python programmers to use this framework easily because another IDEs like pychar are expensive . other editors have no features same as Vscode . 
Thank you .

**Comment by BlackEagle1983** [comment]
Thank you so much for writing type stub files . @WMOkiishi

**Comment by 8Observer8** [comment]
@WMOkiishi thank you very much for your solution! Could you make your package compatible with Pyhton 3.8.10? I cannot use another version because [pybox2d](https://github.com/pybox2d/pybox2d) works with 3.8 only.

- I downloaded [types_panda3d-0.0.2-py3-none-any.whl](https://github.com/WMOkiishi/types-panda3d/releases/download/v0.0.2/types_panda3d-0.0.2-py3-none-any.whl)
-I tried to install it:

> pip install types_panda3d-0.0.2-py3-none-any.whl

I have this error: ```ERROR: Package 'types-panda3d' requires a different Python: 3.8.10 not in '>=3.10'```

**Comment by WMOkiishi** [comment]
@8Observer8 Yeah, I should be able to do that. I think it might only be a matter of changing the stated minimum Python version, as the stubs are only read by the type checker. So keep an eye out for an update.

**Comment by unwave** [comment]
@8Observer8 You can download the folder https://github.com/WMOkiishi/types-panda3d/tree/master/src/panda3d-stubs with https://download-directory.github.io/ , name it `panda3d-stubs` and add the directory containing it to the VSCode's settings:    
```json
"python.analysis.extraPaths": [
        "C:\\Users\\user\\Documents\\panda3d\\stubs"
]
```

**Comment by 8Observer8** [comment]
I downloaded:

![image](https://user-images.githubusercontent.com/3908473/183420660-d30cef22-5004-470a-bbac-bea65dc056e3.png)

I set the path and reloaded VSCode:

![image](https://user-images.githubusercontent.com/3908473/183420813-eb58fbf6-9a94-44b9-a01c-fd5ba87f9768.png)

But it does not work:

![image](https://user-images.githubusercontent.com/3908473/183420947-db62f12f-ce9e-4c3b-b6f3-6035eb3f6ba1.png)

**Comment by unwave** [comment]
> the directory containing it [the folder] 

Not the folder with stubs itself.

```json
    "python.analysis.extraPaths": [
        "E:\\Libs"
    ]
```

**Comment by Moguri** [comment]
I believe we can close out this issue for the time being. types-panda3d module works for the time being, and that's currently a better spot to iterate (more flexibility with releases). We can look at bringing it in to Panda itself as types-panda3d stabilizes (i.e., changes are infrequent enough that being tied to Panda's release cadence is fine).
