### ISSUE TITLE
DirectEntry/PGEntry overflow causes segmentation fault

### ISSUE THREAD

**Issue by darktohka** [panda3d/panda3d#1344]
## Description

Enabling `overflow` in a DirectEntry/PGEntry item will cause Panda3D to crash during the cull traversal phase.

Assertion error:
```
Traceback (most recent call last):
  File "direct.task.Task", line 546, in run
  File "direct.task.Task", line 497, in step
  File "direct.showbase.ShowBase", line 2155, in __igLoop
AssertionError: node_gbv != nullptr at line 217 of /srv/panda3d/panda/src/pgraph/cullTraverserData.I
```

## Steps to Reproduce

```python
from direct.showbase.ShowBase import ShowBase
from direct.gui.DirectGui import DirectEntry, DGG

class ReproGUI(ShowBase):

    def __init__(self):
        ShowBase.__init__(self)
        self.userEntry = DirectEntry(aspect2d, overflow=True)

if __name__ == '__main__':
    ReproGUI().run()
```

## Environment
 * Operating system: Arch Linux
 * System architecture: x86_64
 * Panda3D version:  1.11.0 master
 * Installation method: Built from source
 * Python version (if using Python): 3.10.5
 * Compiler (if using C++): clang 14.0.6

**Comment by darktohka** [comment]
Possibly a regression caused by: https://github.com/panda3d/panda3d/commit/fac6916151cd148c4c8b69aa037962bebe1d7138

**Comment by rdb** [comment]
I think there's a `check_cached(true)` check missing somewhere.  If I call it on the `_text_render_root.node()` in `PGEntry::cull_callback()`, the problem goes away, but I need to think about whether it belongs somewhere else.

**Comment by rdb** [comment]
Ah, took me a while but I found it.  It's because ScissorEffect is being used, whose cull callback sets the CullTraverserData's `_view_frustum`, but it may have previously been null (if we've already determined everything is in view) and if it's null we normally don't actually ensure that the node's bounds are up-to-date.  This is only a problem if some node's cull callback resumes traversal on a disjoint scene graph (which is what PGEntry does), since otherwise a `check_cached(true)` at the root node would've already updated the whole graph recursively.  Very subtle.

I think the `check_cached(true)` should be done at the time of the ScissorEffect's cull callback, since that's when we know for sure that we will need the bounds.  In theory you could even render a scene without culling and suddenly a ScissorEffect will introduce a frustum.  Will check this in.
