### ISSUE TITLE
PStats not starting.

### ISSUE THREAD

**Issue by janEntikan** [panda3d/panda3d#1391]
PStats doesn't start and does not display any error messages. 

This happens with both `panda3d-1.10.10-cp310-cp310-manylinux2010_x86_64.whl` and `panda3d-1.10.12-cp310-cp310-manylinux2014_x86_64.whl`. 

Not sure this is insightful, but running it from the interpreter prints -11. 
```
>>> from panda3d_tools import pstats
>>> pstats()
-11
```

This happened on Arch Linux x86_64 with LXDE

**Comment by rdb** [comment]
It's a segfault.  It appears to occur with wheel-installed builds of Panda3D.  It's somewhere inside harfbuzz (as invoked by panda as invoked by GTK).  Downgrading Panda doesn't help, it's probably due to something that changed within Arch.

I am taking a shot in the dark: Panda is statically-linking harfbuzz, and the harfbuzz symbols within libpanda may be conflicting with the system version of harfbuzz.  I'm going to make a change that makes sure the harfbuzz symbols aren't re-exported from libpanda, and we'll build new wheels, and we'll see if that helps.

**Comment by rdb** [comment]
According to my testing, the bug is fixed in [the latest build](https://buildbot.panda3d.org/downloads/84a69e1689099d81926fe165de9310ef79069585/), please close if you confirm.
