### ISSUE TITLE
PSSMCameraRig should not accept lens with infinite far plane

### ISSUE THREAD

**Issue by el-dee** [panda3d/panda3d#1397]
## Description

The method `PSSMCameraRig::update()` should throw an assert error if the lens of the given camera has an infinite far plane to warn the user. Otherwise the splits are either degenerate or behaves weirdly as the frustum split algorithm can no longer calculates proper splits.

To be honest, it's midway between a bug report and a feature request :)

## Steps to Reproduce

Use the PSSM demo from [here](https://github.com/el-dee/panda3d-samples/tree/main/pssm) and set the far plane to `math.inf`

## Environment
 * Operating system: Linux / macOS
 * System architecture: x86-64
 * Panda3D version: Latest master
 * Installation method: built from source
 * Python version (if using Python): 3.8
 * Compiler (if using C++): GCC 9.4.0

**Comment by rdb** [comment]
Yeah, ouch, there's a divide-by-infinity in there :-)

The math tries to get the corner points using `lens.extrude()`, and then linearly interpolates along it.  The first problem with that is that lens.extrude actually caps the values to `lens-far-distance`, so when dividing something by the far distance it should take that cap into account as well.

However, it's probably better to fix it to use `lens.extrude_depth()` instead—and actually fix `lens.extrude_depth()` to handle infinite far planes properly, which (looking at the code) I can't imagine it doing properly currently.

**Comment by rdb** [comment]
Actually, that won't work, because to obtain a value suitable for passing to `lens.extrude_depth()`, we still need to divide by the far distance.

Come to think of it, there's no reason for the code to care about the far distance of the lens, given that we only care about the frustum up to the maximum defined by `_pssm_distance`.

One fix is to just make a copy of the lens and set the far clip to `_pssm_distance`, but since there are some inaccuracies in the calculation, I'm going to just cap the reciprocal of the far distance to `lens-far-limit` for maximum compatibility in 1.10.13.
