### ISSUE TITLE
Distribute PStats on macOS via Homebrew

### ISSUE THREAD

**Issue by miklesz** [panda3d/panda3d#1399]
## Description
I would propose you to distribute PStats on macOS via Homebrew.

## Use Case
Currently Panda3D for macOS does not have a binary version of PStats. This means that you have to compile it yourself, which is usually much more complicated than simply pip installing the package. Given that it would probably be complicated to include Panda3D in the pip package, perhaps it would be simpler to distribute the binaries with Homebrew, where installation is as easy as with pip.

**Comment by rdb** [comment]
FWIW, I spent a bit of time trying to get GTK 3 to build on macOS, but gave up after a few painful hours.  There are a *ton* of dependencies, using a mixture of build systems (Meson and autotools), everything relies on pkg-config for package detection, and Meson doesn't even support universal builds due to a bug (mesonbuild/meson#8206), making everything twice as complicated as it needs to be.

Distributing with Homebrew is probably the right approach.  We might need to modify our build systems to be able to build *just* pstats and nothing else.

We should probably forget about supporting the 1.10 GTK2-based version of PStats and instead just package the 1.11 GTK3-based version of PStats.  It is much superior anyway and compatible with older client versions of Panda3D.

**Comment by rdb** [comment]
Closing, I no longer see a reason to do this as of #1531.
