### ISSUE TITLE
scipy.libs and shapely.libs errors on build using setup.py

### ISSUE THREAD

**Issue by josheuchert** [panda3d/panda3d#1492]
## Description
When building an executable using the setup.py build_apps functionality, having the requirements of shapely and/or scipy causes the executable to fail. The executable cannot find the library files. 

The error message in the output log: 

"FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\usr\\PycharmProjects\\proj\\venv\\Scripts\\build\\shapely.libs' "
[output.log](https://github.com/panda3d/panda3d/files/11326057/output.log)

See discussion for more information:
https://discourse.panda3d.org/t/filenotfounderror-build-dependency-package-libs-when-using-setup-py/29300

## Steps to Reproduce

Simplest files to reproduce the bug:
[requirements.txt](https://github.com/panda3d/panda3d/files/11326075/requirements.txt)

(below are originally .py files I converted to .txt to be able to upload)
[setup.txt](https://github.com/panda3d/panda3d/files/11326084/setup.txt)
[test.txt](https://github.com/panda3d/panda3d/files/11326097/test.txt)

Run 'python setup.py build_apps'

Try to run the build/win_amd64/test.exe executable.

## Environment
 * Operating system: Microsoft Windows 10 Pro
 * System architecture: setup(.py) and requirements.txt builds test(.py)
 * Panda3D version: 1.10.13 
 * setuptools version: 65.5.1
 * Installation method: wheel?
 * Python version: 3.9

**Comment by rdb** [comment]
scipy and shapely both use a tool called delvewheel to build their Windows wheels, which insert code like the following into their `__init__.py` files:

```python
# start delvewheel patch
def _delvewheel_init_patch_1_3_1():
    import os
    import sys
    libs_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir, 'scipy.libs'))
    is_pyinstaller = getattr(sys, 'frozen', False) and hasattr(sys, '_MEIPASS')
    if not is_pyinstaller or os.path.isdir(libs_dir):
        os.add_dll_directory(libs_dir)
```

So, possible ideas for ways in which we can work around this:
1. Set `sys._MEIPASS`, pretending to be PyInstaller.
2. Put the libraries in `scipy.libs` and `shapely.libs` sub-directories.
3. Just create empty `scipy.libs` and `shapely.libs` sub-directories, but leave the libs in the root folder.
4. Strip the delvewheel patch from the `__init__.py` files.

I'm currently inclined towards #3 for 1.10 and then implement #1 for master, because I suspect that #2 is harder to implement, but I'll have to see.

**Comment by rdb** [comment]
Oops, 2 and 3 are ruled out, because they are looked for in the _parent_ directory.  This is very unfortunate.
