### ISSUE TITLE
TLOPO and AMD 7000 series GPU

### ISSUE THREAD

**Issue by MaddaPakka** [panda3d/panda3d#1521]
## Description
The Legend of Pirates Online utilizes OpenGL and Panda3D. I have recently built a new PC with a 7900XT Merc 310 GPU and 7900X3D CPU, the game is struggling to produce textures with ships, material pictures, enemies, sand, etc.

## Steps to Reproduce
Simply signing in will create this black textured environment.

## Environment
 * Operating system: Windows 11
![20230727_145248](https://github.com/panda3d/panda3d/assets/140756727/5ef6f677-3ba8-4c32-ad83-5acf12adac6b)

**Comment by rdb** [comment]
This is not a bug tracker for TLOPO, contact their developers instead.

**Comment by MaddaPakka** [comment]
I'm not sure why you closed this. This same issue was on toon town and the individual who posted was able to work a fix with Panda3D and it was fixed. I'm seeing the same exact issue here as ToonTown had.

**Comment by rdb** [comment]
We're not responsible for Toontown or TLOPO, we have no access to their codebases, and can't troubleshoot issues with their software.  Their developers should isolate the issue, and if it turns out to be an issue with Panda3D, they can construct a reproduction case and report the issue with relevant details upstream (here).

As such, the issue isn't actionable for us and so it was closed.

If you are running into issues running Panda3D itself, such as the sample programs, or a program you have constructed, then feel free to post an issue here.

**Comment by rdb** [comment]
That all said, the nature of the issue suggests a graphics driver bug, and I would recommend making sure you've updated them to the latest version.
