### ISSUE TITLE
Adding a second MouseRecorder fails

### ISSUE THREAD

**Issue by git2323** [panda3d/panda3d#1561]
## Description
I want to create additional Recorders based on the existing MouseRecorder.
During that process the replay of the frame data fails.
The problem can be reproduced by using two MouseRecorders.

## Steps to Reproduce
The code to reproduce this can be found here: https://github.com/git2323/MouseRecorder/tree/kw_MouseRecorder
The recording of the data can be started by pushing the "r" key.
The replay of the data can be started by pushing the "p" key.

## Environment
 * Operating system: Windows 10
 * System architecture: x64
 * Panda3D version: latest master version
 * Installation method: built from source
 * Python version (if using Python):
 * Compiler (if using C++): msvc 2022 / v143 / C++20

**Comment by git2323** [comment]
some more information:

There seems to be a problem in https://github.com/panda3d/panda3d/blob/4c2581a4d2831eb220ab03757051dc2b372bead9/panda/src/recorder/recorderTable.cxx#L207 The scan._current_index of the datagram does not reflect the read which happens in 
RecorderController::get_factory()->make_instance_more_general(type, fparams)
 
string name = scan.get_string();
 s.a. PandaNode::fillin_recorder().  So when the second Recorder is read, it fails. If I fake the read, by adding the line 
scan.get_string();
 after the call to make_instance_more_general adding a second Recorder works

**Comment by rdb** [comment]
We shouldn't add a `get_string()` without a matching `add_string()` in `write_datagram()`.

BamReaderParam stores a reference to the DatagramIterator, but `MouseRecorder::make_recorder()` (which is the factory function that is being called by `make_instance_more_general`) is creating a copy of the DatagramIterator, so whatever increments `MouseRecorder::fillin_recorder` does to the DatagramIterator doesn't get reflected in the original DatagramIterator.

The fix is for `MouseRecorder::fillin_recorder()` not to use `parse_params()`, or for `parse_params()` to be changed to return a reference instead, but that probably requires changing how that method is invoked.

**Comment by Moguri** [comment]
Is this a release blocker, or can we punt this to 1.11?

**Comment by rdb** [comment]
It's a fairly trivial fix, so let's put it in 1.10.14.  See #1564.
