### ISSUE TITLE
Inconsistent compute shader behavior

### ISSUE THREAD

**Issue by Schwarzbaer** [panda3d/panda3d#1576]
Here is a working reproduction of the manual's compute shader example: https://github.com/Schwarzbaer/panda_examples/blob/master/shaders/compute/main_basic_compute.py
Short summary: A compute shader gets a red texture as input, flips the red and green channel, writes the result to the output texture. The shader is dispatched once. The output texture is present on a quad in front of the camera. It should look green. For some people, it is black.

For me, it works. I am on a Panda3D 1.10.13.
```
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) HD Graphics 520 (SKL GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.3.5
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.3.5
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
```

**Comment by janEntikan** [comment]
I can confirm (and that output of glxinfo is mine). Important to note that when I write the pixel green in the shader, instead of flipping the red and green channels, I do get a green texture. This might mean that the input texture might not be getting through correctly.

**Comment by rayanalysis** [comment]
I can confirm that this program works and displays as expected with Intel HD Graphics 630 running on Ubuntu 22. It displays as a black quad only running with a dedicated NVIDIA GPU on the same machine and OS.

**Comment by janEntikan** [comment]
I wonder if this is a mesa regression.

**Comment by Schwarzbaer** [comment]
```
from panda3d.core import PandaSystem
from direct.showbase.ShowBase import ShowBase


ShowBase()
gsg = base.win.getGsg()

print(f"Panda3D version: {PandaSystem.get_version_string()}")
print(f"git commit     : {PandaSystem.get_git_commit()}")
print()
print(f"Driver vendor  : {gsg.get_driver_vendor()}")
print(f"Driver version : {gsg.get_driver_version()}")
print(f"Shader version : {gsg.get_driver_shader_version_major()}.{gsg.get_driver_shader_version_minor()}")
```
yields
```
Panda3D version: 1.10.13
git commit     : 470e352ab87ceae6e30429720e4690c8371f5a55

Driver vendor  : Intel
Driver version : 4.6 (Compatibility Profile) Mesa 20.3.5
Shader version : 4.60
```

**Comment by janEntikan** [comment]
both with
```
Panda3D version: 1.10.14
git commit     : 26fae21cb9ffed023a3dda385b88ebe213c5c200

Driver vendor  : Intel
Driver version : 4.6 (Compatibility Profile) Mesa 23.3.0
Shader version : 4.60
```
and
```
Panda3D version: 1.11.0
git commit     :  ( doesn't show, it's commit 6f89b8e72090c4ab4302dbe357b8d005cf60a847 from main, October 13)

Driver vendor  : Intel
Driver version : 4.6 (Compatibility Profile) Mesa 23.3.0
Shader version : 4.60
``` 

on both wayland and x11 (though I doubt this matters),
with gl-immutable-texture-storage true, false or default,
and with the explicit read/write kwargs,
still only a black square.

I'll repeat that writing the pixels explicitly green in the shader, bypassing the input texture, does produce a green square, meaning the shader is producing output.

**Comment by michaeladams** [comment]
I get the black square with:

Windows 10
Nvidia GTX 1660 Ti

Panda3D version: 1.10.13
git commit     : 470e352ab87ceae6e30429720e4690c8371f5a55

Driver vendor  : NVIDIA Corporation
Driver version : 4.6.0 NVIDIA 535.98
Shader version : 4.60

**Comment by rdb** [comment]
There's no bug here, not really, but a serious usability defect.

When you call `texture.load(...)`, it replaces all information about a texture, including its format. In this case, the format is being set to `F_rgba`. By default, for floating-point data, that translates to `GL_RGBA16F`, which doesn't match what you have in the shader, so you get undefined behaviour.

Panda can't catch this because it doesn't know what format you wrote in your shader.  With the new shader pipeline, we'll be able to catch format mismatches.  I will add a note to #1381.

To fix the sample code, add a line to `texture_in.set_format(Texture.F_rgba32)` (also for `texture_out`) _after_ the call to `load()`.  Remove the lines to `setup_2d_texture`, since whatever that does gets overridden by `load()`.

An alternative way to create an empty texture using `setup_2d_texture` is to use `set_clear_color`, without `load()`.
