### ISSUE TITLE
Setting array of shader input results TypeError

### ISSUE THREAD

**Issue by sulyi** [panda3d/panda3d#161]
Following script and it's output clearly states the problem, using Panda3d 1.9.4:

```
#!/usr/bin/env python
from direct.showbase.ShowBase import ShowBase
from panda3d.core import NodePath, PTAFloat, Shader

v_shader = """
uniform float foo[8];

void main() {
}
"""

f_shader = """
void () main {
}
"""


class MyApp(ShowBase):

    def __init__(self):
        ShowBase.__init__(self)

        array = [0.5 / (i + 1) for i in range(8)]
        array_sh = Shader.make(Shader.SL_GLSL, v_shader, f_shader)

        self.array_np = NodePath('arrayNode')
        self.array_np.set_shader(array_sh)

        try:
            self.fail(array)
        except Exception as e:
            print e
            try:
                self.success(array)
            except Exception as e:
                print e

    def fail(self, arr):
        print "I'm a failure"
        self.array_np.set_shader_input('foo', arr)

    def success(self, arr):
        print "I'm the winner"
        pta = PTAFloat()
        for v in arr:
            pta.push_back(v)
        self.array_np.set_shader_input('foo', pta)

if __name__ == '__main__':
    app = MyApp()
    app.run()

```
results (bold pars are the error stream): 
> **Known pipe types:
>   glxGraphicsPipe
> (all display modules loaded.)**
> I'm a failure
> **TypeError: PointerToArray.push_back() argument 1 must be UnalignedLMatrix4f, not float
> TypeError: Element 0 in sequence passed to PointerToArray constructor could not be added
> TypeError: Element 0 in sequence passed to PointerToArray constructor could not be added
> TypeError: Element 0 in sequence passed to PointerToArray constructor could not be added
> TypeError: PointerToArray.push_back() argument 1 must be UnalignedLVecBase4i, not float
> TypeError: PointerToArray.push_back() argument 1 must be UnalignedLVecBase4f, not float
> TypeError: PointerToArray.push_back() argument 1 must be LVecBase3i, not float
> TypeError: PointerToArray.push_back() argument 1 must be LVecBase3f, not float
> TypeError: PointerToArray.push_back() argument 1 must be LVecBase2i, not float
> TypeError: PointerToArray.push_back() argument 1 must be LVecBase2f, not float
> TypeError: PointerToArray.push_back() argument 1 must be LMatrix3f, not float**
> Element 0 in sequence passed to PointerToArray constructor could not be added
> I'm the winner

**Comment by rdb** [comment]
OK, I see why.  Figuring out which overload of `set_shader_input` to choose is quite tricky when you pass in a list because it has to try every possible overload to see whether they will accept the arguments you are passing in.  Unfortunately this means it will first have to try adding every element in the list to each variant of PointerToArray.  Because it is reporting the TypeError every time it does so, this is why you see the slew of errors.

The easy workaround that also saves Panda a lot of trouble would be to just explicitly indicate the type to Panda:
```python
self.array_np.set_shader_input('foo', PTAFloat(arr))
```

To fix this in Panda, we could roll a custom version of the `set_shader_input` binding that is much cleverer about this, however this is unlikely to make it to the 1.9 branch.
