### ISSUE TITLE
bam_model_extensions changes external path references in distributions

### ISSUE THREAD

**Issue by izzyboris** [panda3d/panda3d#1642]
## Description
If a model file is converted using the bam_model_extensions from #714 and it references any external resources by pathname (textures, etc.), the write_bam_file() that saves the file changes the relative paths of these models and they may point into the *source* directory. Ideally I think the relative path references in the .bam outputs from the converter should be left alone so they point to the texture relative to their current location.

## Steps to Reproduce
- Create a model with an external texture (e.g., a .blend using blend2bam or .gltf)
- Put ".blend" or .gltf in the bam_model_extensions list
- Run bdist_apps
- The external texture path will get munged during the file write_bam_file() within commands.py:_model_to_bam and point at the *source* directory instead of a texture copied into the build directory.

## Environment
 * Operating system: Windows (probably happens in Linux too)
 * System architecture: 64-bit Intel
 * Panda3D version: 0.10.13
 * Installation method: pip
 * Python version (if using Python): 3.11
 * Compiler (if using C++): N/A

**Comment by rdb** [comment]
Ah, yes, the default bam-texture-mode is "relative", which is trying to be clever and keep the paths relative, but that makes them point into the source directory.

As a workaround, set bam-texture-mode to "unchanged" in your Config.prc.  I will make build_apps do this automatically.

Ideally, it would actually keep it to "relative", but make them relative to the target directory, so that absolute paths are converted.

**Comment by rdb** [comment]
Noticing in my tests that the file got absolute paths with "unchanged", I made the mode always forced to "relative" but changed the path they were being made relative to.

To accommodate people who might have been previously setting `bam-texture-mode rawdata`, I added a new `bam_embed_textures` option.  If you set it to true, the textures will be embedded into the .bam files.
