### ISSUE TITLE
Odd Interrogate Inheritance Issue

### ISSUE THREAD

**Issue by theclashingfritz** [panda3d/panda3d#169]
I haven't been able to really recreate this very specific bug expect in the code i found it in. 

The bug occurs within the Nametag2d interrogate within my project's branch. (https://github.com/theclashingfritz/libotp/tree/Nametag-RE)

Oddly enough when trying to re-create the bug the issue doesn't happen. Perhaps it really is super specific.

This bug was found on Panda3D 1.10.0 (Opt 4)

**Comment by rdb** [comment]
Hmm, that codebase has quite strange inheritance.  Why does everything virtually inherit from TypedObject?  Only one base need do so; since ClickablePopup already inherits indirectly from TypedObject, for example, there's nothing to gain from a class that derives from ClickablePopup also inheriting from TypedObject.

Which class in question is interrogate erroring about, though?  It would help to also see the error message itself.

**Comment by theclashingfritz** [comment]
The error itself is "2>..\src\nametag_igate.cxx(2542): error C2385: ambiguous access of 'as_typed_object'
2>          could be the 'as_typed_object' in base 'TypedObject'
2>          or could be the 'as_typed_object' in base 'TypedObject'
2>..\src\nametag_igate.cxx(2542): error C3861: 'as_typed_object': identifier not found
2>..\src\nametag_igate.cxx(4028): error C2385: ambiguous access of 'as_typed_object'
2>          could be the 'as_typed_object' in base 'TypedObject'
2>          or could be the 'as_typed_object' in base 'TypedObject'
2>..\src\nametag_igate.cxx(4028): error C3861: 'as_typed_object': identifier not found"

and i can't get rid of TypedObject for either of the bases for Nametag2d as both bases have things that need to be published. The rest of the virtual bases are for inheritance or to prevent conflicting class usage.

**Comment by theclashingfritz** [comment]
And both sections the error happens just in case you're curious about that

"/**
 * Python function wrapper for:
 * Nametag2d &Nametag2d::operator =(Nametag2d const &tag)
 */
static PyObject *Dtool_Nametag2d_operator_86(PyObject *self, PyObject *arg) {
  Nametag2d *local_this = NULL;
  if (!Dtool_Call_ExtractThisPointer_NonConst(self, Dtool_Nametag2d, (void **)&local_this, "Nametag2d.assign")) {
    return NULL;
  }
  // 1-Nametag2d &Nametag2d::operator =(Nametag2d const &tag)
  Nametag2d const *arg_this = (Nametag2d *)DTOOL_Call_GetPointerThisClass(arg, Dtool_Ptr_Nametag2d, 1, "Nametag2d.assign", true, true);
  if (arg_this != NULL) {
    (*local_this).operator =(*arg_this);
    Nametag2d *return_value = local_this;
    if (return_value != (Nametag2d *)NULL) {
      return_value->ref();
    }
    if (Dtool_CheckErrorOccurred()) {
      if (return_value != (Nametag2d *)NULL) {
        unref_delete(return_value);
      }
      return NULL;
    }
    if (return_value == NULL) {
      Py_INCREF(Py_None);
      return Py_None;
    } else {
      return DTool_CreatePyInstanceTyped((void *)return_value, *Dtool_Ptr_Nametag2d, true, false, return_value->as_typed_object()->get_type_index());
    }
  }
  if (!_PyErr_OCCURRED()) {
    return Dtool_Raise_BadArgumentsError(
      "assign(const Nametag2d self, const Nametag2d tag)\n");
  }
  return NULL;
}"

"/**
 * Python function wrapper for:
 * Nametag2d *NametagGroup::get_nametag_2d(void)
 */
static PyObject *Dtool_NametagGroup_get_nametag_2d_131(PyObject *self, PyObject *) {
  NametagGroup *local_this = NULL;
  if (!Dtool_Call_ExtractThisPointer_NonConst(self, Dtool_NametagGroup, (void **)&local_this, "NametagGroup.get_nametag_2d")) {
    return NULL;
  }
  // 1-Nametag2d *NametagGroup::get_nametag_2d(void)
  Nametag2d *return_value = (*local_this).get_nametag_2d();
  if (return_value != (Nametag2d *)NULL) {
    return_value->ref();
  }
  if (Dtool_CheckErrorOccurred()) {
    if (return_value != (Nametag2d *)NULL) {
      unref_delete(return_value);
    }
    return NULL;
  }
  if (return_value == NULL) {
    Py_INCREF(Py_None);
    return Py_None;
  } else {
    return DTool_CreatePyInstanceTyped((void *)return_value, *Dtool_Ptr_Nametag2d, true, false, return_value->as_typed_object()->get_type_index());
  }
}"

**Comment by rdb** [comment]
This is not really an issue of Interrogate, but of your odd inheritance that makes the call to the inherited method `as_typed_object()` ambiguous.  This applies to any code that calls it, including the interrogate-generated code.  The compiler gets confused; since your object inherits from TypedObject several times, it won't know which version of the inherited method to pick.

(In theory, interrogate could pick a class and force a devirtualised call.  But how would it know which one to pick?)

It's usually a bad idea to inherit multiple times from TypedObject.  But if you must do so, you need to define a method in the class that inherits multiple times, to disambiguate the call to `as_typed_object()`.

CollisionVisualizer is a Panda class that inherits multiple times from TypedObject, and it defines the following methods to resolve this conflict:

https://github.com/panda3d/panda3d/blob/0fcfb8e372c71e5c15a20bfd064b51f8db831469/panda/src/collide/collisionVisualizer.h#L62-L64
https://github.com/panda3d/panda3d/blob/0fcfb8e372c71e5c15a20bfd064b51f8db831469/panda/src/collide/collisionVisualizer.I#L65-L85

**Comment by rdb** [comment]
Oh, and for the record:

> and i can't get rid of TypedObject for either of the bases for Nametag2d as both bases have things that need to be published. The rest of the virtual bases are for inheritance or to prevent conflicting class usage.

You don't need to inherit from TypedObject to publish anything via Interrogate.  It will wrap the types just fine without any TypedObject in your inheritance tree.

(It's only needed for dynamic upcasting; so that a method that returns a PandaNode pointer will automatically upcast to a GeomNode on the Python side if it's really a GeomNode.  Even then, you only need one TypedObject in the class hierarchy; adding multiple inheritances to TypedObject will just confuse matters.)

Needing virtual inheritance is usually a sign that you may need to rethink your class hierarchy.  It's a tool that should be used sparingly; I don't believe virtual inheritance is needed in any part of the Panda3D codebase.

**Comment by loblao** [comment]
I wrote this code a few years ago. It's broken and unfinished (how did it even get leaked?). I do not recommend using it.

**Comment by theclashingfritz** [comment]
It was public Loblao. Also i only plan on using it as a base as i slowly RE Disney's Nametags

**Comment by theclashingfritz** [comment]
Also thanks for the help rdb. (Didn't know you didn't need a TypedObject to publish...) And the class hierarchy will now finally be able to under go some renovations as i needed that to compile to do some testing and etc.
