### ISSUE TITLE
get image data from ram image

### ISSUE THREAD

**Issue by ox9osub** [panda3d/panda3d#173]
After this code, I get the 2d texture data
        base.graphicsEngine.renderFrame()
        tex = base.win.getScreenshot()
2d_texture 
  2-d, 128 x 128 pixels, each 4 bytes, rgba
  sampler wrap(u=repeat, v=repeat, w=repeat, border=0 0 0 1) filter(min=default, mag=default, aniso=0) lod(min=-1000, max=1000, bias=0)  65536 bytes in ram, compression off

But 
tex.getRamImageAs("RGB").getData()
or
tex.getRamImageAs("RGBA").getData()
or
tex.getRamImage().getData()
doesn't work.

Error Message is here.

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

My Panda3d Version is panda3d (1.10.0.dev1189) and python 3.6.2

**Comment by rdb** [comment]
You have not specified which exact version of Panda3D and Python you are using.

**Comment by rdb** [comment]
The best and fastest way to access a RAM image's data is with a [memoryview](https://docs.python.org/3/library/stdtypes.html#memoryview):

```python
view = memoryview(tex.getRamImage())
```

This can be read out in a number of ways, or converted into a `bytes` object using `bytes(view)`.

However, I will fix the (now redundant) `get_data()`, which is currently trying to decode it as utf-8 string rather than a `bytes` object, hence the error.

**Comment by rdb** [comment]
I checked in a fix for `get_data()`.  That said, it is easier to just do `bytes(tex.getRamImage())` (Python 3 only) or `bytearray(tex.getRamImage())` (Python 2 or 3), or to use the memoryview approach above.
