### ISSUE TITLE
Problem with off-screen buffers on OSX

### ISSUE THREAD

**Issue by ankeshanand** [panda3d/panda3d#183]
Hi,

I am facing issues when creating off-screen buffers on OSX Sierra (`makeOutput` reutrns `None`). The error message I get is `AttributeError: 'NoneType' object has no attribute 'makeDisplayRegion'`.

Here's the code:
````
winprops = WindowProperties.getDefault()
winprops = WindowProperties(winprops)
winprops.setSize(self.size[0], self.size[1])

fbprops = FrameBufferProperties.getDefault()
fbprops = FrameBufferProperties(fbprops)
fbprops.setRgbColor(1)
fbprops.setColorBits(24)
fbprops.setAlphaBits(8)
fbprops.setDepthBits(1) 

selection = GraphicsPipeSelection.getGlobalPtr()
self.pipe = selection.makeDefaultPipe()

flags = GraphicsPipe.BFFbPropsOptional | GraphicsPipe.BFRefuseWindow
buf = self.graphicsEngine.makeOutput(self.pipe, 'RGB buffer', 0, fbprops, winprops, flags)

dr = buf.makeDisplayRegion()
````

I can verify that my Panda3D installation works fine since I am able to run basic examples. Do I need to do any OSX specifc config changes in `Config.prc`?

**Comment by Moguri** [comment]
I believe BFRefuseWindow requires pbuffers, which are not supported for OSX. I don't remember if this is an OSX limitation or a Panda one.

**Comment by ankeshanand** [comment]
@Moguri I tried setting `glx-support-pbuffer` to `false`, and `glx-support-pixmap` to `true` but still get the same errors.

**Comment by rdb** [comment]
`glx-support-pbuffer` is not relevant for macOS.  It is only used on Linux and FreeBSD.

Moguri is right about the fact that Apple deprecated support for pbuffers in Cocoa.  That means you always have to pass in a "host" window into the `make_output` call so that Panda can make an FBO.

Does your use case require creating an offscreen window without having an onscreen window open at all?

**Comment by chatonn** [comment]
Hi,

I am sorry for 'reopening' this issue but I am trying to run the following code on Mac (High sierra) and panda3d 1.10 and I really need to save graphial buffer without having to open a window:

from panda3d.core import loadPrcFileData
loadPrcFileData("", "window-type offscreen" ) # Make sure we don't need a graphics engine (Will also prevent X errors / Display errors when starting on linux without X server)
loadPrcFileData("", "audio-library-name null" ) # Prevent ALSA errors
import direct.directbase.DirectStart

and I always end up with the error:

-MacBook-Pro:sampleNODISPLAY $ python test.py 
Using deprecated DirectStart interface.
Known pipe types:
  CocoaGraphicsPipe
(all display modules loaded.)
:ShowBase(warning): Unable to open 'offscreen' window.
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    import direct.directbase.DirectStart
  File "/Users/-/anaconda/lib/python3.6/site-packages/direct/directbase/DirectStart.py", line 24, in <module>
    base = ShowBase.ShowBase()
  File "/Users/-/anaconda/lib/python3.6/site-packages/direct/showbase/ShowBase.py", line 276, in __init__
    self.openDefaultWindow(startDirect = False, props=props)
  File "/Users/-/anaconda/lib/python3.6/site-packages/direct/showbase/ShowBase.py", line 925, in openDefaultWindow
    self.openMainWindow(*args, **kw)
  File "/Users/-/anaconda/lib/python3.6/site-packages/direct/showbase/ShowBase.py", line 961, in openMainWindow
    self.openWindow(*args, **kw)
  File "/Users/-/anaconda/lib/python3.6/site-packages/direct/showbase/ShowBase.py", line 710, in openWindow
    raise Exception('Could not open window.')
Exception: Could not open window.

I understand I used a depreciated DirectStart interface but I would like to know how I can create a 'fantom' buffer and render texture without opening a graphical window. I obtain the same error if I don't use the DirectStart interface but use ShowBase():

Known pipe types:
  CocoaGraphicsPipe
(all display modules loaded.)
:ShowBase(warning): Unable to open 'offscreen' window.
Traceback (most recent call last):
  File "sampleND.py", line 827, in <module>
    demo = DistortionDemo()
  File "sampleND.py", line 732, in __init__
    ShowBase.__init__(self)
  File "/Users/-/anaconda/lib/python3.6/site-packages/direct/showbase/ShowBase.py", line 276, in __init__
    self.openDefaultWindow(startDirect = False, props=props)
  File "/Users/-/anaconda/lib/python3.6/site-packages/direct/showbase/ShowBase.py", line 925, in openDefaultWindow
    self.openMainWindow(*args, **kw)
  File "/Users/-/anaconda/lib/python3.6/site-packages/direct/showbase/ShowBase.py", line 961, in openMainWindow
    self.openWindow(*args, **kw)
  File "/Users/-/anaconda/lib/python3.6/site-packages/direct/showbase/ShowBase.py", line 710, in openWindow
    raise Exception('Could not open window.')
Exception: Could not open window.

I know mac and cocoa had some issue due to depreciated version of some library (or library not supported anymore)  but I would like to know if there exist any workaround which will allow me to create a buffer, render object (with texture) in this graphical buffer and save it as an image without having to open a window.

Thank you for your help !

**Comment by rdb** [comment]
This is now implemented via FBOs.  (It turns out that macOS conveniently does not require a context to be made current to a surface before it can be used, so the use of pbuffers is not necessary for windowless rendering.)

Buildbot builds should appear on the devel download page shortly.  It would be great if you could check it out and see whether everything works as you expect.
