### ISSUE TITLE
egg-palettize: margin option that doesn't sample from the texture

### ISSUE THREAD

**Issue by nosyliam** [panda3d/panda3d#192]
Referencing issue #181, I was having issues with the egg-palettize tool because of the :margin option sampling from the edge of my textures and creating a margin from that resulting in strange effects around the images. Because of this, I've had to manually add transparent and colorless pixels around my images which is tedious and time-consuming. 

If an option such as :colorlessmargin or something along those lines could be developed for the egg-palettize tool it would save me plenty of time :)

**Comment by rdb** [comment]
This is now implemented; you can use the options `border_color_u` and `border_color_v` (instead of `clamp_u` and `clamp_v`).  There is no way to override the border color for a texture, but it defaults to the background color.  Let me know if it works for you.

I've also implemented `mirror_u` and `mirror_v` for completeness' sake.
