### ISSUE TITLE
In Actor class, default parent of exposed joint is odd

### ISSUE THREAD

**Issue by bluekyu** [panda3d/panda3d#221]
I found an odd case while building joint tree.
I knew that a exposed joint is parented to the actor instance in Actor class without first node parameter.
However, if a character node (child of Actor) is transformed, then the exposed joint is not affected by the transform.

In [looking and gripping example](https://github.com/panda3d/panda3d/blob/master/samples/looking-and-gripping/main.py), I moved the character node to (0, 0, 1) and then it is rendered as below.
(`self.eve.get_child(0).set_pos(0, 0, 1)`)

![image](https://user-images.githubusercontent.com/937305/34562642-a3614d4a-f192-11e7-98cc-d04ffdcc5d49.png)

And I can fix it by reparenting the exposed joint to the Character node: `self.rightHand.reparentTo(self.eve.getChild(0))`

OR, by changing the parent node to NodePath of part bundle in Actor class from 

https://github.com/panda3d/panda3d/blob/1073f5abded8b7c406945bf502a203211778f8d8/direct/src/actor/Actor.py#L1107

to
```
node = partDef.partBundleNP.attachNewNode(jointName)
```

So, I wonder which solution is right.
(or, shouldn't I transform the Character node?)

**Comment by rdb** [comment]
Hmm, I guess it stands to reason that the actor interface wasn't designed to allow transforming the character node.  It sounds like your proposed change to Actor.py would handle that situation properly, though, so that sounds like a good change to make; I just hope it wouldn't break anyone's code if they happen to be relying on the current behaviour.

**Comment by bluekyu** [comment]
Thanks for reply. And is it possible to merge the Actor.py changes if I make pull request?

**Comment by rdb** [comment]
I'll take care of it, thanks.

**Comment by bluekyu** [comment]
Thank you very much for the commit.

However, control joint has also similar behavior, but it is not critical as expose joint.
https://github.com/panda3d/panda3d/blob/b5e9f23e3b4cc73e953e91bf36976c9e1cc69fa8/direct/src/actor/Actor.py#L1294

The current issue happens only when **reading** the net transform (world transform) of control joint of the root or the transform of tree of control joints. (I knew that the reading the net transform of control joint is meaningless in general cases.)

What do you think about control joint?

**Comment by rdb** [comment]
Does that not only use the relative transformation rather than the absolute one?  I don't think that's very meaningful for any joints other than the root one, though perhaps it is useful if one is reflecting the entire tree into a node graph, since otherwise the net transform won't really make sense.  (I would argue that because of that reason, the returned node shouldn't be parented to anything, and we should instead rely on the user to parent the node as they wish.)
