### ISSUE TITLE
Graphics window unclickable using CocoaGraphicsPipe on High Sierra

### ISSUE THREAD

**Issue by darktohka** [panda3d/panda3d#227]
The commit https://github.com/panda3d/panda3d/commit/ef7f856c46299f4d14711130269f11afad49e4c3 seems to have caused a regression on Mac OS X, atleast as tested on High Sierra.

Any graphics windows created using Cocoa are unclickable. As such, keyboard input and mouse input becomes impossible. In addition, the application no longer appears on the Dock.

Reverting this commit resolves the issue.

Much appreciated.

**Comment by rdb** [comment]
Hmm, the only issue I'm noticing is that windows seem to open in the background when not launched from an application bundle.

Anything particular you're doing in your application?  Does pview exhibit the same issue?

**Comment by darktohka** [comment]
I'm not sure. My virtual machine does not have 3D acceleration, so I will have to ask somebody with a real Mac to help me gather more information.

I will reply shortly with some tests.

**Comment by rdb** [comment]
I'll be able to look into it next week, when I will have access to my mac again.

I think it probably has something to do with the fact that app initialisation was moved from CocoaGraphicsPipe constructor to the CocoaGraphicsWindow constructor.  The reason I did that was so that headless applications wouldn't end up with an ever-bouncing dock icon.  You'd think the "activateIgnoringOtherApps" selector would take care of it, though.

Do you have any tk/wx stuff enabled?  I know there's some old code in ShowBase that calls `init_app_for_gui()`, which spawns an NSApplication if one is not already started.  I wonder if that is getting called for you—you could try commenting out those two lines in ShowBase.py.

**Comment by darktohka** [comment]
No, I am not using any TK or WX code - it's just a simple Panda3D app.

**Comment by rdb** [comment]
Looks like a silly oversight on my part, my apologies!

Could you let me know whether it's all good on your end now?
