### ISSUE TITLE
OpenAL buffer segfault on OSX

### ISSUE THREAD

**Issue by nosyliam** [panda3d/panda3d#230]
My application is unexpectedly crashing because of an OpenAL segfault.  
A full crashlog can be found here: https://hastebin.com/putikewuxo.go

Any ideas? It doesn't happen immediately: after a few minutes of running and excellent audio it'll segfault.

**Comment by rdb** [comment]
Are there specific circumstances that trigger this?  It would be very helpful if I am somehow able to reproduce the crash on my own mac.

That said, it may be good if we compile the macOS builds with OpenAL Soft going forward rather than relying on the built-in Apple implementation, if it turns out that OpenAL Soft is just more stable.

**Comment by nosyliam** [comment]
It occurs in statically-built applications like mine. Frameworks like Nirai (https://github.com/nirai-compiler) are very similar to how my application functions. Other than that, there are no circumstances that trigger this.

**Comment by CFSworks** [comment]
It's hard to say for sure without a disassembly of your built version of `push_fresh_buffers()`, but reading a memory offset of 0x10 that early on in the function should correspond to `  if (_sd->_sample) {`.

This means `_sd` is NULL (further suggested by rax=0x0), but because `push_fresh_buffers()` is called it means the sound is in the manager's `_sounds_playing`. As I understand the OpenAL plugin, that's meant to be impossible. There are two ways this could happen:

1. `_sd` was never set but the sound somehow ended up getting played anyway.
2. `_sd` was nulled without the sound being removed from `_sounds_playing`.

Possibility 1 is easy to eliminate because the only mechanism for adding the sound to `_sounds_playing` is the call to `_manager->starting_sound(this)` from `play()`, which ensures that `_sd` is set (via `require_sound_data()`) before it can even reach that point.

So it must be possibility 2 - `_sd` is getting nulled. The two ways for *that* to happen are through `stop()` and `cleanup()`, but since `stop()` calls `_manager->stopping_sound(this);` before touching `_sd`, we can be sure it's not `stop()` but `cleanup()` that's the culprit.

However, `cleanup()` checks if there's a `_source` and calls `stop()` first if so, which would prevent this bug. So we need to look for a way for the sound to be in `_sounds_playing` without `_source`. **That** is only possible if `_source` is zeroed after the fact (since `OpenALAudioManager` checks `_source` immediately before adding to `_sounds_playing`).

But, the only thing that zeroes `_source` is `OpenALAudioManager::stopping_sound()` which removes the sound from `_sounds_playing`. So either I made a mistake somewhere in my reasoning above, or there's a memory issue going on somewhere.

@nosyliam I feel like the best way to help us track this down would be to add debug prints to each of the functions above, printing `this` and the various member variables in each one, and providing (or carefully studying yourself) the call trace to deduce the order in which these things get out of sync.

@rdb Come to think of it, the OpenAL code needs a few asserts to verify its invariants. There's a lot of "implicit" things like `_source != NULL` meaning the sound is playing. I can take a crack at some of them - might force a few bugs to make themselves known.

**Comment by nosyliam** [comment]
Thanks for the interest, I'll debug the issue as soon as I have an OSX machine available.

**Comment by CFSworks** [comment]
The crash was definitely coming from `cleanup()` alright - an earlier `pull_used_buffers()` had errored and called `cleanup()` in the middle of `OpenALAudioManager::update()`'s loop - which meant it cruised right along to `push_fresh_buffers()` and *that* tried to access `_sd` when it was NULL from the earlier error.

I'm finishing up the testing on a patchset to clean up OpenAL a little bit. I'll PR it when it's ready.

**Comment by nosyliam** [comment]
Any crashes in my application are gone now, so fantastic! Glad to see other games that use OpenAL like Toontown Rewritten now have audio, as well.
