### ISSUE TITLE
Move the loader to a separate thread

### ISSUE THREAD

**Issue by nosyliam** [panda3d/panda3d#255]
In many large applications, it's essential to preload many assets at one time (usually before gameplay). Doing this, however, will cause the Panda's main thread to not respond to any user input. This removes the ability to add interactivity during these loading phases, such as a spinning loading image. It's also generally unpleasant for the window to stop responding entirely, sometimes even showing the "This application has stopped responding..." notice on Windows. Instead of having developers working with Panda3D develop a complex loading system, it would be incredibly better to have Panda do all the threading automatically while still keeping the application responsive. 

You can reproduce this issue by loading a large amount of textures/models at once using Panda's default loader.

**Comment by Moguri** [comment]
If you pass a callback to loadModel(), it will lead asynchronously: https://www.panda3d.org/manual/index.php/Threading#Asynchronous_Operations

**Comment by nosyliam** [comment]
My only issue with this is that it's incredibly hard to implement it into existing (large) codebases. Almost all the time models need to be used directly after they are loaded with no room for any async operation. What I'm looking more for is to keep the window/render thread separate from the python/loading thread.

**Comment by CFSworks** [comment]
If a model is used directly after it's loaded as you say, it wouldn't even help to put the loader in a separate thread, because by definition the app thread cannot continue until the model is ready. (That is, while Panda already supports running loading operations asynchronously and in a different thread, it wouldn't do any good if the app doesn't have a way of proceeding without the model being available yet.)

If passing a callback and refactoring the model-loading routines is too prohibitive, a good third option would be to update to Python 3 and use Panda3D's [recently-added support for coroutines](http://www.panda3d.org/blog/november-2017-development-update/). This would let you write asynchronous code that behaves as @Moguri suggested, while writing it the same way you'd write a blocking loading routine. Coroutines would allow direct's event loop to continue running even though your app logic is waiting on assets to be ready.

**Comment by nosyliam** [comment]
I see. I guess I'll have to try and port over every single load operation to asynchronous. Thanks for the insight, though!

**Comment by rdb** [comment]
There's nothing preventing you from creating your own thread and doing the load operations on there.  But the loader does have asynchronicity built-in as described above, and coroutines are a great approach for making use of it.

Depending on your code, you may alternatively be able to use a wrapper around loadModel that simply returns an empty NodePath, and uses a callback to parent the loaded model to that NodePath when complete.  However, this will not work if you need to do any operation whatsoever after loading that requires the model's structures to be present, such as a flatten or find operation.

**Comment by drewc5131** [comment]
What liam probably means is to have a way for the game to still render, like for a loading screen, but the loading stuff would still happen

**Comment by rdb** [comment]
@drewc5131 yes, that is what asynchronous loading means, and this is already implemented as described above.
