### ISSUE TITLE
Dropping support for MSVC 2010

### ISSUE THREAD

**Issue by rdb** [panda3d/panda3d#288]
I'm opening this as an issue to see if anyone will raise objections.  Dropping support for MSVC 2010 and MSVC 2012 will give us access to a lot of interesting C++11 features.  Furthermore, thirdparty libraries have been dropping support for older compilers, making it more difficult to build with recent versions of those libraries.

Windows XP can still be targeted by MSVC 2015, which I have tested to work, albeit without support for thread-safe magic statics.

If there are no objections, what should we raise the minimum to; could we go straight to 2015?  Is anyone building with 2013?

Raising the compiler requirement to 2013 would already be a great improvement, allowing us to use the following features, among others:
* Defaulted and deleted functions
* Enum classes
* Forward declared enums
* Non-static data initializers
* Templated typedefs (via. `using`)
* Delegated constructors
* `explicit` for conversion operators
* Range-based for loop
* Initializer lists

Raising the requirement to 2015 enables full support for C++11, including:
* Rvalue/lvalue overloading in methods
* Standardised `[[attributes]]`
* Inheriting constructors
* Better unicode support
* Custom literals
* Inline namespaces
* Fewer restrictions on unions

Table of features:
https://msdn.microsoft.com/en-us/library/hh567368.aspx

**Comment by theclashingfritz** [comment]
I have no issue with Visual Studio 2015 as i already use it compile and have been dropping support for 2010 in my Panda3D projects already. So i'm all for this improvement.

**Comment by CFSworks** [comment]
I'd say we're just going to push for the 2015 features eventually anyway, so why not save us an extra migration and skip 2013?

The thing I'd like to ask is "how would it inconvenience anybody?" I realize having to install a new compiler on your build environment just to keep working is a chore, but since Microsoft makes the SDKs available for free and they pretty much install themselves, would this cause anybody to go more than an hour out of their way? (e.g. if they'd have to make their downstream projects specifically support MSVC 2015 or if they'd have to migrate a bunch of solution files or if operating system upgrades are necessary)

**Comment by theclashingfritz** [comment]
Yeah it shouldn't be much of hassle. The only issues i could see is projects that build statically having some issues but that's about it from what i can find. (Not even from Panda3D itself however on my side. Just Python acting a fool.)

**Comment by nosyliam** [comment]
I'm very much in favor of this. Right now, I'm building Panda with 2010 and it's a hassle to run two separate build environments (with my other applications building with 2015). Having the minimum at 2015 would definitely save me tons of time having to dig up 2010 in brand-new environments. I'm also presuming that it's faster and optimizes better, so 👍

**Comment by CFSworks** [comment]
@nosyliam What are your reasons for not using 2015 to build Panda already? What is the advantage to using 2010 over 2015 currently?

**Comment by nosyliam** [comment]
Being completely honest, it's just because there aren't any prebuilt thirdparty libraries for it. rdb provided prebuilt libraries for 2010 a while ago, so I've just been using them. I can't express how much of a hassle it is to build all of them, so probably the only thing that would motivate me to convert everything would be if the minimum was changed.

**Comment by Moguri** [comment]
@nosyliam [this thread](https://www.panda3d.org/forums/viewtopic.php?f=9&t=18775) has some pre-built libraries for MSVC 2015.

**Comment by nosyliam** [comment]
Oh wow, for some reason I didn't come across that while I was searching, thanks! I'll definitely be switching to MSVC 2015 now, there's pretty much no benefit to using 2010.

**Comment by Moguri** [comment]
+1 for going to 2015. I do not do any building on Windows (outside of buildbot builds), so I cannot speak to any issues for dropping 2010 or 2013. However, looking at your list, #291 will not build on 2010 (range-based for loops, maybe some other stuff).

**Comment by theclashingfritz** [comment]
The only issue i had with 2015 was Python. But that's because Python doesn't normally build with 2010 so you have to fix like 2 files. You can find the patches for that online which is what i did except for the 1 error i had to manually fix. So i'd recommend adding python to the thirdparty builder for Panda3D if 2010 is in fact dropped. As a custom one will be REQUIRED.

**Comment by rdb** [comment]
Glad to hear there's no objections to setting 2015 as the minimum.  If there's no more negative feedback on this in the next week or so I'll start making changes to change the default in makepanda and add an error message if 2010 is selected, and to replace existing macros like `DEFAULT_CTOR` with appropriate `=default` and other such things.

Python 3.5+ builds with MSVC 2015 already, and I've been building with unmodified previous versions of Python with MSVC 2015 for quite a while, so I'm not aware of any such issues.  But sure, we will continue to ship Python as part of the thirdparty packages on Windows.

**Comment by Nickdoge** [comment]
I have been building Panda3D with MSVC 2017, I do think MSVC 2015 should be the default. VS 2010 can be hard to find a download nowadays, for a Build Environment sometimes. MSVC 2015 or 2017 is easily able to be found (they're both supported). A few cons however that there may be is, current people using MSVC 2010 might not want to update to 2015 and have to set everything up. However, I think the pros outweigh the cons. I do believe having VS2010 is easier for Windows XP support, but I doubt many people use Windows XP anymore. The main reason why I support MSVC2015 support is for std::future/std::async support, and many other modern features, but async specifically caught my attention.

**Comment by rdb** [comment]
Thanks for the feedback, all.  Glad to hear there is no objection to this.  I have made some commits to clean up all the compatibility hacks that existed to support pre-C++11 compilers, so Panda3D no longer compiles with MSVC versions before 2015.
