### ISSUE TITLE
Having a significant amount of Actors causes massive fps dropage

### ISSUE THREAD

**Issue by drewc5131** [panda3d/panda3d#292]
In games like Toontown, having as much as like 8 toons in the area, causes the fps to go down from what would be normally around 80-90 in an area, down to about 30. This is the biggest place the engine needs optimization in if you ask me.

**Comment by drewc5131** [comment]
I will provide a test case as soon as I get home.

**Comment by thetestgame** [comment]
I've run into frame rate issues on Pirates Online too. 5 actors is enough to drop the frame rate below 15 on a machine with a i7, 32gb of ram, and a 1080 gtx. I experimented with this further and it seems to be related to loading actors in general on python. C++ tests ran perfectly

**Comment by theclashingfritz** [comment]
Python is a major bottleneck in terms of stuff like this. I've been considering converting core classes to C++ just for the speedup.

**Comment by drewc5131** [comment]
yes i know its from actor

**Comment by xseano** [comment]
@theclashingfritz How would the size of Actor have anything to do with lag?

**Comment by theclashingfritz** [comment]
[actor.zip](https://github.com/panda3d/panda3d/files/1844899/actor.zip)
Here's the split up Actor fin a base and Actor if anybody else wants it. It should help performance just a bit.
Optimized a bit of the code as well.

**Comment by theclashingfritz** [comment]
@xseano It can cause long times to find a function by dict hashing in python and the like. Remember everything in Python is hashed and listed. So if a file is massive it can cause longer search times in the hash tables. And the more classes you have of the bloated file. The effect practically stacks.

**Comment by wezu** [comment]
Are You sure the bottleneck is Python dict lookup (usually O(1) for str keys) and not having to calculate dozens of matrices and multiply thousands of vertices by these matrices each frame? As far as I know the best way to make animations faster is to move the skinning to the vertex shader.

**Comment by rdb** [comment]
The idea that this performance decrease is caused by Python is extremely unlikely.  Also, the size of a class' code or dictionary doesn't affect performance in any measurable way (certainly not at a scale of only 80-90 instances), so @theclashingfritz's suggestions are just muddying the waters here.

A more likely cause is the vertex animation code, as wezu suggested, which is implemented in C++ already.  A quick way to check whether this might be it would be to comment out all the play()/loop() calls to see if disabling the animations makes the performance issue go away.  If this is the cause, the easiest way to fix the problem is to switch to doing the vertex animation on the GPU rather than the CPU.  Panda provides an easy way to enable this in the shader generator nowadays.

Rather than speculating, we need to do real performance analysis to be able to understand where the problem is.  Could you use PStats to zero down on the performance issue, and post screenshots of the graphs?

This might be a duplicate of #222.

**Comment by thetestgame** [comment]
@rdb We tried moving the animation over to the gpu on one our projects and it had no measurable difference. My earlier python VS. C++ tests involved manually loading the model and animating it on the C++ side and it performed significantly better. It might be related to the Actor.py

**Comment by rdb** [comment]
Could we see some PStats charts in this issue report?

**Comment by theclashingfritz** [comment]
Will do. I'll get some as soon as possible.

**Comment by treamology** [comment]
I'm curious about this, so I ran a quick test in both C++ and Python, featuring 100 walking pandas:

<img width="401" alt="pandas" src="https://user-images.githubusercontent.com/13398095/38176918-4ec4b55a-35bd-11e8-8255-541ede0ebfd6.PNG">

This is a 64-bit Panda on Python 3.6.3 compiled from a recent master.
**CPU**: i7-3770K @ 3.9 GHz
**GPU**: NVIDIA GeForce GTX 1060 6GB

## Python
<img width="774" alt="python-pandas" src="https://user-images.githubusercontent.com/13398095/38176907-fd864cf8-35bc-11e8-94b1-a1a08cee4beb.PNG">
<img width="936" alt="python-anim" src="https://user-images.githubusercontent.com/13398095/38176908-ffcd052e-35bc-11e8-8d6b-4f36a944fbca.PNG">

## C++
<img width="898" alt="cpp-pandas" src="https://user-images.githubusercontent.com/13398095/38176910-11679510-35bd-11e8-8cca-8850c55f650d.PNG">
<img width="997" alt="cpp-anim" src="https://user-images.githubusercontent.com/13398095/38176911-1379c51c-35bd-11e8-924d-f1ba39676228.PNG">

It seems that the C++ version is about 50% faster than the Python version in terms of frametime, but both are still taking a while to calculate the animations.

**Comment by rdb** [comment]
Also, does this go away if you enable hardware skinning?  This involves putting this in Config.prc
```
hardware-animated-vertices true
basic-shaders-only false
```
And calling this to enable the shader generator for your model:
```
model.setShaderAuto(True)
```

It is a bit worrying that the Python version is so different in performance from the C++ version.  There should not be a difference in performance at all.  I would very much like it if you could post your test code.

**Comment by treamology** [comment]
With C++, hardware skinning marginally improves performance. With Python, however, I'm actually seeing a slight performance decrease (it's still taking the same amount of time to skin, but there's also an added draw time overhead):

## Python
<img width="815" alt="python-hardware" src="https://user-images.githubusercontent.com/13398095/38178479-aa86196c-35d9-11e8-86ae-b9fd44cc6a5d.PNG">
<img width="815" alt="python-hardware-anim" src="https://user-images.githubusercontent.com/13398095/38178481-ad229aec-35d9-11e8-80b4-ac134433f1e7.PNG">

```
from direct.showbase.ShowBase import ShowBase
from direct.actor.Actor import Actor

from panda3d.core import PStatClient

showbase = ShowBase()

actor_list = []

for x in range(10):
    for y in range(10):
        panda_actor = Actor(
            'models/panda',
            {'walk': 'models/panda-walk'}
        )
        panda_actor.set_pos(x * 10, 0, y * 10)
        panda_actor.loop('walk')
        panda_actor.reparent_to(base.render)
        panda_actor.set_shader_auto(True)
        actor_list.append(panda_actor)

PStatClient.connect()

showbase.run()
```

## C++
<img width="844" alt="cpp-hardware" src="https://user-images.githubusercontent.com/13398095/38178466-4c2418ce-35d9-11e8-909d-3d1c3a3ed64d.PNG">
<img width="844" alt="cpp-hardware-anim" src="https://user-images.githubusercontent.com/13398095/38178468-50fd9c76-35d9-11e8-9f56-9c1aed05343b.PNG">

```
#include "pandaFramework.h"
#include "pandaSystem.h"

#include "pStatClient.h"

int main(int argc, char *argv[]) {
	PandaFramework framework;
	framework.open_framework(argc, argv);

	WindowFramework *window = framework.open_window();
	window->setup_trackball();				

	for (int x = 0; x < 10; x++) {
		for (int y = 0; y < 10; y++) {
			NodePath pandaActor = window->load_model(framework.get_models(), "models/panda");
			pandaActor.reparent_to(window->get_render());
			pandaActor.set_pos(x * 10, 0, y * 10);
			pandaActor.set_shader_auto(true);
			window->load_model(pandaActor, "models/panda-walk");	
		}
	}
	window->loop_animations(0);

	PStatClient::connect();

	framework.main_loop();
	framework.close_framework();
	return 0;
}
```

**Comment by CFSworks** [comment]
I'm noticing a lot of PStats time going into the `*` category in Python.

Any chance this is caused by `garbage-collect-states`?

**Comment by treamology** [comment]
Well, damn, my Python results were actually coming from a 1.9.4 installation (my path variable was pointing to it). When running the Python version of the test under the same newer build as the C++ version, there is little to no performance decrease, which makes much more sense. My apologies for misleading you all.

**Comment by rdb** [comment]
That would make sense, since 1.10 is generally faster than 1.9 in many things, including the animation system.  I would not expect to see a significant difference between the Python and C++ versions.

Without HW skinning, most time seems spent in the `*/Animation` category, which makes sense.  I can see from your C++ example that the '*' time goes to almost nothing with HW animation enabled.  I take it that the reason you were still seeing time in `*` in the Python version was because you were editing the wrong configuration file to enable hardware animation?  In other words, are you seeing the same drastic increase when enabling HW skinning in the Python example in 1.10?

I am seeing a few milliseconds spent in Draw on my end, though nowhere near the time you are seeing.  Odd, as I'm using a 1070, which shouldn't be massively different.  We will want to investigate why this is taking so much time, especially since we're just rendering the same model many times.  I suspect the Geoms are getting duplicated at some point despite the fact that they're being loaded from the model-cache; could you confirm this by pulling up the **Graphs** > **Geoms** menu, with HW skinning enabled, and checking whether you see 1000 or just a few?

For the record, I see very little future in optimizing CPU animation; I think the only way to get good performance out of animating many models is by using GPU skinning, so that's what I'll be focusing on optimizing.

**Comment by theclashingfritz** [comment]
GPU skinning is a better concept overall as is and should be a default. That's a GPU's job, To process graphics. The CPU should be able to worry about other things then processing graphics.

**Comment by CFSworks** [comment]
Panda doesn't (yet) support hardware skinning in all circumstances - only when using the shader generator (i.e. when compiled with Cg) or the DX9 fixed function renderer.

At a minimum we'd probably want to add support for GL_ARB_vertex_blend before we consider pushing this as a default - and even then it should probably be based on autodetection rather than defaulting enabled since it can still lead to broken animations.

That being said, I agree: hardware skinning is much better than having to push fresh vertex buffers every frame. Every modern GPU supports it, and because it's a performance detail that many novice game developers don't know about, Panda should try to do the expected thing when not told otherwise.

I'd be willing to take a crack at GL_ARB_vertex_blend if there's no solid reason why Panda shouldn't have it. But autodetection for hardware skinning support would be another issue altogether. 

@rdb thoughts? Would love to do some GL coding!

**Comment by rdb** [comment]
@cfsworks: we have supported GL_ARB_vertex_blend for a very long time, but recently removed it because no modern driver actually implements it.  Sorry to disappoint.

Shaders are the way to go; the intent is to replace the Cg shader generator with a more integrated approach that uses GLSL and supports PBR (I plan on working on this later in the year).  Eventually we don't even want to use the fixed-function pipeline at all by default.

**Comment by CFSworks** [comment]
Killing the fixed-function pipeline altogether sounds great, especially considering that Vulkan and GLES don't have a "fixed function" at all.

It's a little beyond the scope of this issue and we might want to move this discussion elsewhere, but I have some doubts about GLSL being the way to go. As much as I disliked the proprietary and non-portability of Cg, it did serve as a reasonable cross-API abstraction layer. Do we have some plan for compiling to SPIR-V and D3D shader bytecode? Do we have some strategy for shipping shaders in a binary format for the organizations that don't want to distribute their shader source code? (Or maybe GLSL does all of the above and I just haven't yet discovered the right tools for it.)

Still, I'd love to take some swings at the graphical side of Panda - definitely hit me up if you could use a hand.

**Comment by rdb** [comment]
Yeah, I think for a shader generator it would make sense to write SPIR-V directly (through use of some wrapper API to write instructions readably), especially with OpenGL 4.6 supporting SPIR-V natively, and we can cross-compile from there to other languages if needed.  I actually have been sitting on SPIR-V shader support on my local branch for many months now but have yet to find the time to clean it up.

I think killing the fixed-function pipeline altogether might not be a very popular idea (Panda prides itself on still being able to run on OpenGL 1 hardware), but one idea I have is to try and modularise the FFP code into its own type of shader context (pretending that FFP is a type of shader) so that we can cleanly separate it out from the rest of the GSG code.

But, all this goes far beyond the scope of this issue, so let's take this discussion elsewhere.

**Comment by treamology** [comment]
To answer the previous question, yes, Python has the same performance as C++ in this instance, with almost no time being spent in `*` as expected. Both my PC with the 1060 (with hardware skinning) and my macOS machine (w/o hardware skinning) are showing 1000 geoms.

**Comment by rdb** [comment]
I looked a bit into why @treamology's code is creating 1000 separate Geoms even with hardware skinning, and it's because GeomVertexData (which lives under the Geom) is storing the TransformTable that reference the joints on the Character node. When you load the model again, it copies the scene graph—including all the Character nodes—which then requires duplicating the all the TransformTable objects because they reference this Character, meaning there need to be 1000 different GeomVertexData objects and 1000 different Geoms.

So, even if hardware skinning is used, Panda nonetheless ends up creating and uploading a separate VBO for every instance. I think one (API-breaking) way to remedy this might be to move the TransformTable to the Geom level; this will still cause 1000 separate Geoms, but at least the underlying vertex and index buffers won't be duplicated except if the animation happens on the CPU.

(In this specific example code, using `instanceTo` would of course be much better, but this does not allow the actors to be independently animated.)

**Comment by drewc5131** [comment]
A tad bit of a late response. But using hardware animation seems to work fine in most places, however, when trying to integrate it into a Toontown Online source, i get these results
![image](https://user-images.githubusercontent.com/31282527/44315466-74b17480-a3f2-11e8-8370-d146b6267281.png)

![image](https://user-images.githubusercontent.com/31282527/44315483-9a3e7e00-a3f2-11e8-8d5e-e8c9d1921cd1.png)

This also applies in game, not just on this screen, and it applies to any sort of object the character holds. It just doesn't render it.

**Comment by rdb** [comment]
Please send me the models in question, with corresponding animation files.

**Comment by drewc5131** [comment]
The models aren't the problem. Loading the models in a simple app with HW rendering works fine, I'm trying to look further into the code to see if i can find the problem.

**Comment by drewc5131** [comment]
I meant to write this a while ago but I forgot to. So the reason there were problems with instancing and stuff was just because the shader was incredibly basic. Using SetShaderAuto() worked. However, It seems to be giving me less performance now. Most of my DRAW time is taken up by SetState.
![image](https://user-images.githubusercontent.com/31282527/47237320-acb24500-d3ac-11e8-95bc-15cb63ecfc2b.png)

**Comment by drewc5131** [comment]
The set state takes up almost no time initially, but then when the actor is displayed, it triples.
![image](https://user-images.githubusercontent.com/31282527/47237430-0b77be80-d3ad-11e8-9d35-e23cd77ed1e4.png)

The extreme spike is where i click on the icon to show the model

**Comment by drewc5131** [comment]
@xseano yeah i probably should

**Comment by rdb** [comment]
I am not convinced that the issue you are describing is something that would be helped by the specific optimization suggested in #421.

**Comment by drewc5131** [comment]
@rdb shall I reopen this?
I'm assuming it's due to the the fact that the torso and head are parented to joints of the model below it.
