### ISSUE TITLE
Dropping support for Mac OS X 10.6 "Snow Leopard"

### ISSUE THREAD

**Issue by rdb** [panda3d/panda3d#300]
Similar to #288, I'm opening this issue to see if there are any objections to this.  Supporting Snow Leopard is getting more and more of a nuisance, since we need libc++ in order to get C++11 library features on macOS, but Mac OS X 10.6 only supports libstdc++.

An additional advantage would be that 10.7+ only runs on 64-bit Intel processors, so we would no longer have to ship a universal build, which cuts down the size of the SDK download.

I can understand that it might be controversial to effectively drop support for 32-bit macs though, so if you or anyone you know is targeting their Panda game to run on Snow Leopard, please make your voice heard.

Furthermore, let us know what you think should be the minimum version we should support on macOS.  There's something to be said for raising the minimum to 10.9, ~~but I suggest we go to 10.7 for now until we find a good reason to raise it further~~.

FWIW, statcounter is showing Snow Leopard market share at about 1.68% of all macOS users.

**Comment by jwcotejr** [comment]
Honestly, I don't imagine that too many people will miss Snow Leopard support if it's dropped. Dropping support for 32-bit Macs may not be as controversial as it may seem; Apple hasn't supported 32-bit Macs for years, and, based off your last point about Snow Leopard currently holding a low market share, I would imagine that a **very** low percentage of Panda3D users are relying on Snow Leopard/32-bit Mac support, especially as that number will only continue to decrease. Also, most macOS software hasn't had this support for a while. I just think that, at this point, it is more trouble than it is really worth to support Snow Leopard.

Having said that, 10.7 would be a nice minimum to move up to. I imagine a lot more people are using 10.7 than 10.6, since the early Core 2 Duo Macs max out at 10.7, but it probably wouldn't be too long into the future where 10.9 being the minimum would make more sense. Just my two cents, though.

**Comment by Moguri** [comment]
@rdb can we drop 10.6 for 1.10, or do we need to first mark it as deprecated?

**Comment by rdb** [comment]
So far, there haven't been any unovercomeable issues yet, so there isn't a big reason not to keep building 1.10 for Snow Leopard.  (I am having some issues with building Assimp against the 10.6 SDK, though.)

Unless we encounter significant difficulties, I'm inclined to just mark SL as "deprecated" in 1.10 and drop it entirely on the master branch after 1.10.0 is out.

**Comment by rdb** [comment]
Any objection to setting the minimum to 10.9 for the next major release?

**Comment by Moguri** [comment]
As part of dropping 10.6 support, we should remove osxdisplay (Carbon support) as per the discussion in #440.

I have no objections to setting the minimum to 10.9, but I am not a macOS user.

**Comment by jwcotejr** [comment]
I have no objections either. I am currently targeting 10.9 as a minimum anyway.

**Comment by rdb** [comment]
I raised the minimum to 10.7 for now, and switched to libc++, but there appear to be substantial bugs with the libc++ library in 10.7 needing workarounds in Panda such as 3ccfbfaba722d068bce535225979c13ad0e19fd1 and 3e5f2cf67215adf36d4b7fc26098f84483f9e967.  If it turns out not to be worth the trouble, we'll just skip straight to 10.9.

**Comment by rdb** [comment]
I can't find an announcement for this, but it appears that Python 3.8 no longer supports anything lower than 10.9, as [the 10.6 build is no longer on the download page](https://www.python.org/downloads/release/python-380/).

I think we should not waste time running builds against different SDKs for different Python versions, so this definitely sets our new minimum to 10.9 on the master branch.

**Comment by el-dee** [comment]
While investigating for https://github.com/panda3d/panda3d/issues/795, I noticed that panda built **on Catalina** using SDK 10.6  crash immediately at startup due again to, I believe, a mix up between libc++ and libstdc++ (it's a segfault when initializing the graphic pipe, in the alloc method of basic_traits) even though the 10.6 SDK  is properly installed and referenced.

**Comment by rdb** [comment]
Noted—I think we will distribute two builds in 1.10.5, one that will work with 10.6-10.14 and another that will work with 10.9-10.15.

**Comment by barracuda156** [comment]
Well, both statements are inaccurate: you don’t need libc++ for C++11, and 10.6 can use libc++ (though it is not shipped as a part of the OS).
