### ISSUE TITLE
Tasks with the same sort value do not preserve their order between frames

### ISSUE THREAD

**Issue by amras0000** [panda3d/panda3d#309]
The following code creates `TASK_COUNT` tasks, giving them all the same sort value. It then tracks what order they are executed each frame. On my machine at least, the order is not persistent between frames, except when `TASK_COUNT = 2`

``` python
from direct.showbase.ShowBase import ShowBase
from direct.showbase.DirectObject import DirectObject

TASK_COUNT = 6

order = []
this_frame = []
index = 0

class Test():
    def __init__(self):
        global index
        index += 1
        self.index = index
        super().__init__()
        base.task_mgr.add(self.test, sort=10)
        
    def test(self, task):
        if self.index not in order:
            order.append(self.index)
        elif len(this_frame) == len(order):
            if (this_frame != order):
                print('WRONG ORDER!\nWas expecting {} but got {}\n'.format(order, this_frame))
            this_frame.clear()
        print('running test %d'%self.index)
        this_frame.append(self.index)
        last_test = self.index
        return task.cont

base = ShowBase()
for _ in range(TASK_COUNT):
    Test()

base.run()
```

**Comment by rdb** [comment]
We don't guarantee any particular order for tasks that have the same sort value, because tasks with the same sort value may even run in parallel in a multithreaded task chain.

However, I can see how it is useful to have more defined behaviour in the case of a single-threaded task chain, so I have checked in a change that makes tasks with the same sort and priority values sorted in the order in which they were added to the task chain.

I would still recommend that people do not rely on this and instead simply specify a correct sort value (for strict ordering in multithreaded chains) or a priority value (for weak ordering).

More concise test case for verifying the behaviour:
```python
from direct.task.TaskManagerGlobal import taskMgr, Task

def printTask(i):
    print(i)
    return Task.cont

taskMgr.add(printTask, "test1", extraArgs=[1])
taskMgr.add(printTask, "test2", extraArgs=[2])
taskMgr.add(printTask, "test3", extraArgs=[3])
taskMgr.add(printTask, "divider", extraArgs=["===="], sort=10)
taskMgr.run()
```
