### ISSUE TITLE
Transitions Don't work properly for wider Aspect Ratios

### ISSUE THREAD

**Issue by drewc5131** [panda3d/panda3d#311]
When using a wider aspect ratio, the transitions like fade and iris don't scale properly.

I wrote a simple application that just does a 0.5 alpha fade, which is very visible where it doesn't extend.

![image](https://user-images.githubusercontent.com/31282527/39591214-1aa8ff24-4ed1-11e8-8c0e-157759156553.png)
```
from direct.showbase.ShowBase import ShowBase

class fadeTest(ShowBase):
    def __init__(self):
        ShowBase.__init__(self)
        base.transitions.fadeScreen(.5)
        
fadeTest().run()
```

**Comment by rdb** [comment]
Fixed. For the default fade screen it now simply parents to `render2d`, but not for the iris transition, which would otherwise look distorted. Instead, it applies an appropriate scale to the iris card based on the aspect ratio.

**Comment by rdb** [comment]
This fix will need to be backed out due to #475, since parenting to `render2d` no longer makes it obscure mouse clicks properly.  We'll need to come up with a different fix.

**Comment by ArsThaumaturgis** [comment]
Could this not perhaps be fixed by having Transitions just resize at least some of its overlays (such as the fade-screen) when they're requested, using either the size of the parent window or the scale of aspect2d relative to render2d?

In addition, could changes in the window-size perhaps be handled by having Transitions register for window-events when one of its overlays is shown (clearing the event when all overlays have been removed)?

**Comment by rdb** [comment]
Yeah, that sounds like it would work; or it could register a task to do the same.  An alternative would be to create a new PGTop under `render2d` just for the transitions and register it with the MouseWatcher; or to directly add a custom MouseWatcherRegion to the mouse watcher when the transition starts, obviating the need for the DirectFrame altogether.

I kinda wish there were an aspect2d alternative that scaled *up* instead of down.
