### ISSUE TITLE
Can't free MovieTexture's memory

### ISSUE THREAD

**Issue by cflavio** [panda3d/panda3d#333]
Hi! I would like to free the memory which is occupied by a MovieTexture. As instance, I've this code (it loads 4 movies named *0.mp4*, *1.mp4*, *2.mp4*, *3.mp4*):

```
from panda3d.core import *
import gc, resource, direct.directbase.DirectStart
 
 
card_maker = CardMaker('movie card')
card = NodePath(card_maker.generate())
card.reparentTo(render2d)
 
 
def load_movie(i):
    movie = MovieTexture('')
    movie.read('%s.mp4' % i)
    card.set_texture(movie)
    gc.collect()
    TexturePool.release_all_textures()
    print 'used: %s MB' % round(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss / 1024.0, 2)
 
 
map(load_movie, range(4))
run()
```

But, if I run it, I observe this:

```
Known pipe types:
  glxGraphicsPipe
(all display modules loaded.)
:ffmpeg(error): bad src image pointers
used: 125.66 MB
:ffmpeg(error): bad src image pointers
used: 147.68 MB
:ffmpeg(error): bad src image pointers
used: 169.76 MB
:ffmpeg(error): bad src image pointers
used: 180.85 MB
```

Is there any way to free that memory? Thanks!

**Comment by rdb** [comment]
Great.  To explain, the issue is that assigning a texture to a node creates a `RenderState` referencing that `Texture`, which (when the state cache is enabled) will not be removed until the next call to `RenderState.garbage_collect()`.  This normally happens automatically each frame though, so you usually don't need to call it explicitly.
