### ISSUE TITLE
[Bullet Physics] Softbody rope and anchored rigid body : certain mass combinations cause physics glitch

### ISSUE THREAD

**Issue by UFaction** [panda3d/panda3d#337]
I haven't tested all different combinations of shapes, scales, object types, etc... but I found that when anchoring a box-shaped bullet rigid body to a bullet softbody rope via 'appendAnchor', certain combinations of mass between the rope and the rigid body will cause the node to which the rigid body was anchored to glitch out.

The rope node will pull upwards until it or the rigid body crash into one of the other nodes. When seen in debug view, the wireframe of the node will be stretched out and jitter between two opposite positions on the XY plane.

The glitch only occurs after some force has been applied to either object. An example of mass combination where the glitch occurs is 10 for the rope and 50 for the rigid body. The severity of the glitch is proportional to the mass difference between the two objects. 
The number of subdivisions in the rope seems not to affect the glitch unless there are none, i.e. the only nodes in  the rope are the start and end node. To which node the rigid body is anchored also seems to make no difference.

Here is a file illustrating the issue. The relevant code is in the "setupweightedrope" function:
[Softbody_Rope_Mass_Glitch.zip](https://github.com/panda3d/panda3d/files/2058493/Softbody_Rope_Mass_Glitch.zip)

**Comment by Moguri** [comment]
Do you have reason to suspect that this is an issue with Panda's Bullet wrapper rather than an issue with Bullet itself?

**Comment by UFaction** [comment]
> Do you have reason to suspect that this is an issue with Panda's Bullet wrapper rather than an issue with Bullet itself?

No, insofar that my technical knowledge of both Panda3D's inner workings is by far insufficient to make any judgement past my observation of the glitch; and I have never worked with Bullet in a way that didn't involve a wrapper.

**Comment by JoelStienlet** [comment]
Could this be a collision problem? When I offset the box from the rope:
`object_weight.setPos(end_point + LPoint3f(0,0,-1.))`
I don't see the glitch anymore.

**Comment by UFaction** [comment]
> Could this be a collision problem? When I offset the box from the rope:
> `object_weight.setPos(end_point + LPoint3f(0,0,-1.))`
> I don't see the glitch anymore.

It probably is some collision problem, but not a logical one.

On one hand, it shouldn't occur since both the softbody rope and the weight are set to mask 0, which is is set not to collide with itself: `world.setGroupCollisionFlag(0,0,False)` 
That is, if I'm not misunderstanding something about how masks are supposed to work, or how collisions work in this type of compound object in Bullet.

According to the Bullet API, the last argument to `.appendAnchor`, a boolean, is supposed to deactivate collisions between linked bodies; if this transfers to the P3D wrapping of `.appendAnchor`, then it does not solve the problem since the glitch still occurs with `rope.appendAnchor(rope.getNumNodes()-1, weight, True)`

On the other hand, the glitch is explicitly exacerbated, if not caused, by a difference in mass between the rope and the weight. If you set the weight object's mass to something like 10, no glitching occurs.

**Comment by JoelStienlet** [comment]
I tried again setting the collision masks to BitMask32.alloff() (without position offset) and I still see the bug, so maybe the offset I set in the previous test stabilized the numerical scheme somehow, and it has nothing to do with collisions after all...
I also tried to set the same mass ratio in panda's bullet sample 21 (SoftbodyRope), and it also reproduces this kind of glitch.
We could also report this bug to the bullet team, following Moguri's intuition.

**Comment by UFaction** [comment]
As said, I don't have the necessary insight into how Panda3D and Bullet interact to make any call on the subject. I can report to the Bullet dev team on your word, but that's about it.

**Comment by JoelStienlet** [comment]
From what I could read from Panda's source code, in this case it is basically just wrapping bullet functions. So I would recommend you to report this bug to the Bullet dev team indeed.

In the meantime I also did some tests setting dt manually, for different combinations of rope and box masses. 
`self.bullet_world.doPhysics(dt, 0, 0)`
I also removed the initial force (-250,250,0), and only kept the gravity + a small perturbation (1, 0, 0) set when pressing "d" (in order to trigger the instability).
rope subdivisions = 5 for all tests, unstable when dt < dt_lim:
BoxMass = 100  RopeMass = 20 : dt_lim = ~0.012
BoxMass = 100  RopeMass = 10 : dt_lim = ~0.01
BoxMass = 30   RopeMass =  6 : dt_lim = ~0.013
It looks like the threshold value for dt does not strongly depend on the mass, but the mass ratio has to be in some interval to trigger the instability as you said in a previous post. (Also close to the threshold values this instability can grow rather slowly.)

**Comment by JoelStienlet** [comment]
After playing with bullet's demo "NewtonsRopeCradle.cpp", I found that changing the number of iterations of the position solver made the bug appear/disappear (when setting you mass ration 1:10 with Box100 and rope10, dt=0.01):
`softBodyRope0->m_cfg.piterations = 5;`

You can set this value in your panda python code using:
```
rope.getCfg().setPositionsSolverIterations(5)
```
I did a test and apparently that removes the instability.

**Comment by UFaction** [comment]
> From what I could read from Panda's source code, in this case it is basically just wrapping bullet functions. So I would recommend you to report this bug to the Bullet dev team indeed.

All right, I'll send them a report as soon as I can, then.
Should I link the report here in a next comment, so as to keep track of the issue?

> After playing with bullet's demo "NewtonsRopeCradle.cpp", I found that changing the number of iterations of the position solver made the bug appear/disappear (when setting you mass ration 1:10 with Box100 and rope10, dt=0.01):
> `softBodyRope0->m_cfg.piterations = 5;`
> 
> You can set this value in your panda python code using:
> 
> ```
> rope.getCfg().setPositionsSolverIterations(5)
> ```
> I did a test and apparently that removes the instability.

It does indeed! I've tried lower values like 2, and that seems to solve the issue too, at first glance. Trial and error'll show what works best in practice case-by-case I suppose.
Thank you very much for your work!

**Comment by JoelStienlet** [comment]
You're welcome!
I don't think a bug report to bullet is necessary any more, as the bug is identified now, and was caused in-fine by the default value of this parameter not being adequate in this configuration, and adjusting it made the numerical scheme stable again. In fact it is pretty common for numerical simulations to have some kind of "black magic" parameters to adjust in order for the numerical scheme not to diverge. But these parameters should be easier to find, and perhaps better documented.
I'll see what I can do to improve the "softrope" demo in this sense.
Perhaps [panda's web page about bullet config](https://www.panda3d.org/manual/?title=Bullet_Softbody_Config) could also be improved somehow, but as the whole Panda site is being upgraded this may be done in a second time.

**Comment by UFaction** [comment]
> You're welcome!
> I don't think a bug report to bullet is necessary any more, as the bug is identified now, and was caused in-fine by the default value of this parameter not being adequate in this configuration, and adjusting it made the numerical scheme stable again. In fact it is pretty common for numerical simulations to have some kind of "black magic" parameters to adjust in order for the numerical scheme not to diverge. But these parameters should be easier to find, and perhaps better documented.
> I'll see what I can do to improve the "softrope" demo in this sense.
> Perhaps [panda's web page about bullet config](https://www.panda3d.org/manual/?title=Bullet_Softbody_Config) could also be improved somehow, but as the whole Panda site is being upgraded this may be done in a second time.

I see. Less work is less work, and less work is good.
Well, I'll look forward to your work on more in-depth documentation on this and related matters!
As for this issue, should I now close it?

**Comment by JoelStienlet** [comment]
Yes I think this issue can now be closed :)

**Comment by Moguri** [comment]
Thanks @UFaction and @JoelStienlet for digging into this!
