### ISSUE TITLE
[MacOS] Metal support and OpenGL depreciation

### ISSUE THREAD

**Issue by judge2020** [panda3d/panda3d#339]
Currently, the best option for rendering Panda3D applications on the OS X/MacOS platform is via the cross-platform OpenGL API. As of yesterday's keynote with the reveal of MacOS 10.14, the [what's new page](https://developer.apple.com/macos/whats-new/#deprecationofopenglandopencl) of developer.apple.com states that support for OpenGL is being depreciated:

> Deprecation of OpenGL and OpenCL
Apps built using OpenGL and OpenCL will continue to run in macOS 10.14, but these legacy technologies are deprecated in macOS 10.14. Games and graphics-intensive apps that use OpenGL should now adopt Metal. 

Without moving to Metal or another Mac compatible graphics API, Panda applications running via OpenGL on MacOS may stop working in the future once the depreciated APIs are removed.

**Comment by CFSworks** [comment]
While a Metal renderer could be a great addition to the Panda ecosystem, Apple is not likely to remove OpenGL any time soon. This deprecation suggests, if anything, that they will no longer be updating their OpenGL implementation for future versions of the specification, and instead encourage the use of Metal for new applications and those that need state of the art graphics performance beyond what the current level of OpenGL support can offer.

I'd expect that the GL API will remain in the Apple APIs in some shape or form for at least another 15 years, as the API is heavily used by a lot of legacy software that nobody's going to update, and users would not appreciate Apple removing compatibility outright.

**Comment by rdb** [comment]
I think it might be a better use of our time if we finish the Vulkan implementation and then use [MoltenVK](https://github.com/KhronosGroup/MoltenVK) on macOS/iOS, which is a Khronos-provided implementation of Vulkan on top of Metal.

**Comment by mfwass** [comment]
It's rather frustrating that Apple is doing this. I'm heavily biased here, but they rarely seem to care about how their decisions will impact consumers or developers. Apple has their magic ecosystem that they're the supreme rulers of, and if you don't conform to that standard you're dead to them.

This is a horrible decision on Apple's part. There's something to be said about having cross-platform software readily available and properly supported. If an application developer can easily port their Windows-based software to macOS because all of the libraries are cross-platform, they're able to expand their software across the board. This also makes a consumer more inclined to buy a Mac if the programs they rely on are able to be used on Mac. It's a win-win situation for all parties involved. Apple killing OpenGL is going to lock out a huge part of the industry, and it's going to be felt across the board.

They're shooting themselves in the foot here, and it's only making the lives of developers and consumers more difficult.

**Comment by corbinu** [comment]
You could use this: https://github.com/gfx-rs/portability

**Comment by drewc5131** [comment]
Yeah, I wouldn't focus on it. Vulkan would be much OpenGL isnt being removed completely as @CFSworks said. Just apple trying to force their software on everyone with no actual benefit. Hopefully these decisions actually deter people from buying macs so apple can learn a lesson.

**Comment by rdb** [comment]
It seems that there is pretty much concensus on prioritising a Vulkan back-end over spending effort on a Metal port, so I'm closing this until plans change or someone offers to do the work.
