### ISSUE TITLE
Can we pull in a Python dependency such as enum34?

### ISSUE THREAD

**Issue by rdb** [panda3d/panda3d#351]
I'd like to discuss a policy on whether we want to be able to mark other Python packages as dependencies of the core Panda3D modules (at least for the Python integration).

The example at hand is that if we want to be able to expose C++11 enum classes, the best way to do that would be to map them to Python enums (which interrogate indeed does), however these are only available in Python 3.4 onward.  To remain compatible with older Python versions, we could mark the [enum34](https://pypi.org/project/enum34/) polyfill package as a dependency.

For pip/debian installations, this is the best and easiest approach, since pip/apt will automatically pull in dependency packages, keep them up-to-date and prevent unnecessary duplication.  For the Windows SDK builds, it means we will need to ship the dependencies with the Python build that comes with the SDK, possibly by doing a `pip install` step during the packaging process.  On macOS, we don't ship a Python build so I'm not sure what we would do; perhaps we would have to just ship the dependencies along after all.

However, I can imagine that this might add more complication for people who use a non-standard distribution/deployment method, so I'm opening this up for others to weigh in on.  (It is not a problem for anything freeze-based such as deploy-ng, since it is a pure-Python module, and deploy-ng fetches dependencies via pip anyway.)

If we go with this approach, I would recommend that we follow the same approach with dependencies like Pmw, so that we can be relieved of the burden of keeping that up-to-date.  The alternative would be to take the enum module, and distribute it as part of Panda3D alongside the Pmw module, or even to freeze it as part of the Python bindings.

**Comment by CFSworks** [comment]
In direct (with Pmw), I have no objections at all to Python dependencies - provided they're recorded using a typical/standardized way (e.g. a `requirements.txt`).

For Interrogate-generated binary modules to depend on a pure-Python package, however, seems a little odd to me. I see it just uses `PyImport_ImportModule`, so I guess there's nothing very strange going on. Even [CPython itself](https://github.com/python/cpython/blob/bfe4fd5f2e96e72eecb5b8a0c7df0ac1689f3b7e/Modules/timemodule.c#L844) does this in a few cases. I do maintain a VERY non-standard deployment method, and situations like this involve a little bit of trickery to get working right. But, I suppose this is **the** Pythonic way of doing enums, so that offsets my discomfort I'd say.

In a way, we already have a (build-time) dependency on pytest. It would be nice to memorialize our Python dependencies somehow (e.g. a `requirements.txt` in the repo root) in a way that they can be automatically installed on CI nodes and recorded as whl dependencies.

When shipping the SDK to a platform that has its own Python implementation, I think the best thing to do (long-term) would be to ship direct and the Panda3D bindings as whl, and have the Panda3D installer install the Python side of things by invoking pip.

**Comment by rdb** [comment]
I'm closing this because I ended up having interrogate provide a built-in mimic for the Python 3.4 enum class that supports all the main uses of enums.  We can reopen this when the discussion becomes relevant again.

Having the installer invoke `pip` is an interesting idea, but since each whl has its own copy of the Panda core libraries and binaries, this would mean that the core libraries get duplicated for each Python version we install.  I think we should keep using wheels for the pip install but not for the SDK installers.
