### ISSUE TITLE
sweepTestClosest with BulletTriangleMeshShape causes AssertionError

### ISSUE THREAD

**Issue by UFaction** [panda3d/panda3d#356]
Performing a `BulletWorld.sweepTestClosest(shape, ts_from, ts_to)` where `shape`  is an instance of BulletTriangleMeshShape seems to invariably cause the following AssertionError and crash Panda3D:

```
AssertionError: convex->isConvex() at line 954 of c:\buildslave\sdk-windows-amd64\build\panda\src\bullet\bulletWorld.cxx
```

Whether the shape was converted from the Geom of a loaded model, or was created with 'BulletTriangleMesh.addTriangle(p0,p1,p2)'  seems to make no difference. I have not tested other methods of creating a triangle mesh.

**Comment by rdb** [comment]
This is not a bug, just poorly documented.  The Bullet sweep test that this method uses only accepts convex shapes.

You could consider using `BulletConvexHullShape` instead of `BulletTriangleMesh`, which also accepts either an arbitrary number of points or a `Geom` object.  Note that creating a convex hull of a mesh is essentially what you get when you shrink-wrap the mesh in foil, which may be acceptable for near-convex meshes but may not be suitable for highly concave meshes, eg.:
![image](https://user-images.githubusercontent.com/194842/41562503-20d45d6c-734d-11e8-8f7e-a4ed6c2ceb27.png)
