### ISSUE TITLE
Mouse cursor position reporting

### ISSUE THREAD

**Issue by lachbr** [panda3d/panda3d#359]
The project I'm working on requires first-person, mouse look-around camera controls. So, each frame, I'm checking the distance of the mouse cursor from the center of the window, rotating the camera according to that delta, and then re-centering the cursor. For some reason, there seems to be a problem with the cursor position reporting, especially at low frame rates. You can see the cursor physically moving from the center between frames then being forced back, however the reported positions show little to no movement. This causes extremely choppy and inconsistent look-around controls at lower frame rates.

From my experimentation, it may have something to do with the Panda mainloop. I have another Panda application where the mainloop is controlled by Qt, and it is able to pick up the change in cursor positions at even the lowest frame rates, therefore maintaining a consistent and smooth look-around speed.

Both are limited to 10 frames per second.
Panda mainloop: https://gyazo.com/c749ab77bde2a2904cfbb7b6e743c898
Qt mainloop: https://gyazo.com/9f12ea056d22989419c62fc8416e7b12

```from panda3d.core import *
loadPrcFileData("", "clock-mode limited")
loadPrcFileData("", "clock-frame-rate 10")
from direct.showbase.ShowBase import ShowBase
from direct.showbase.InputStateGlobal import inputState

base = ShowBase()

def __mouseTask(task):
    mw = base.mouseWatcherNode
    if mw.hasMouse():
        md = base.win.getPointer(0)
        print md
        base.win.movePointer(0, base.win.getXSize() / 2, base.win.getYSize() / 2)
        
    return task.cont

base.accept("s", taskMgr.add, [__mouseTask, "mt"])
base.accept("r", taskMgr.remove, ["mt"])

base.setFrameRateMeter(True)

base.run()

**Comment by rdb** [comment]
Yeah, I can confirm this.  The issue seems to be that the cursor position is updated during the window loop, but the mouse may have moved quite a bit between the time that this happens and `move_pointer` is called.  This intermediate movement is therefore hidden, which can be a lot if the framerate is particularly low.

Firstly, we can fix most of this by making `get_pointer` call the Win32 API `GetCursorPos` to update the current mouse position straight away.  This means repeated calls to `get_pointer` within the same frame will cause different coordinates to be returned, but that seems more like a feature than a bug to me.

This is still not *quite* perfect since the mouse may continue to move between the calls to `get_pointer` and `move_pointer`.  So I think we would ideally wrap these up in a single call that "pseudo-atomically" returns the current mouse position and resets the mouse back to the center.  (Alternatively, we could let `move_pointer` check the current difference and add it to the target position, ie. pretend that the mouse move happened *after* the call to `move_pointer`, but this does not cover all uses of `move_pointer`.)

We should also make a Windows emulation for the `M_relative` mouse mode that automatically resets the mouse cursor as soon as the event comes in.  This means that users will no longer need to write different mouse handling code for different platforms.

I think we should implement all three solutions, but the first solution will by itself fix most of the imprecision here without requiring changes to application code, so I will check that in shortly.

This is only really an issue on Windows, since other platforms you should be using relative mouse mode anyway, though I'll also fix this for X11 for code that does not use the relative mode.  However, we should ideally just emulate `M_relative` on Windows so that we can get everyone to just use that.
