### ISSUE TITLE
Unclear behaviour of locking material attributes

### ISSUE THREAD

**Issue by Epihaius** [panda3d/panda3d#370]
After applying a material to a model, attempting to clear any of its attributes leads to an AssertionError, e.g. `clear_diffuse` leads to:

`AssertionError: !is_attrib_locked() at line 133 of c:\buildslave\sdk-windows-amd64\build\built-py3.6\include\material.I`

Similarly, trying to set a diffuse color on an applied material that has no diffuse color yet, leads to:

`AssertionError: !is_attrib_locked() at line 142 of c:\buildslave\sdk-windows-amd64\build\panda\src\gobj\material.cxx`

IIRC, there was a time that it wasn't possible to change any locked material color either, but that limitation was apparently lifted at some point.
This seems a bit inconsistent to me.

The following code sample can be used to try and clear the diffuse color of an applied material (press "C"):

```
from panda3d.core import *
from direct.showbase.ShowBase import ShowBase


class MyApp(ShowBase):

    def __init__(self):

        ShowBase.__init__(self)

        dir_light = DirectionalLight("light")
        light_np = self.render.attach_new_node(dir_light)
        light_np.set_hpr(-20., -20., 0.)
        self.render.set_light(light_np)
        self.render.set_shader_input("light", light_np)
        self.render.set_shader_auto()

        self._mat = mat = Material()
        mat.set_diffuse((1., 0., 1., 1.))
        smiley = self.loader.load_model("smiley")
        smiley.reparent_to(self.render)
        smiley.set_material(mat)

        self.cam.set_pos(0., -5., 2.)
        self.cam.look_at(0., 0., 0.)
        self.accept("c", self.__clear_diffuse)

    def __clear_diffuse(self):

        # the following causes an AssertionError
        self._mat.clear_diffuse()


app = MyApp()
app.run()
```

Tested with Panda version 91b01e5, Python 3.6 64-bit on Windows 10.

**Comment by rdb** [comment]
This is intended.  While you can change specific colours of a material after you have assigned it to a model, you cannot change whether it has or doesn't have said colour.  This is because changing this would require the model's shader to be regenerated.  Tracking whether such a change happened would be prohibitatively expensive and incur non-obvious lag, so we just forbid it.  You could just create a copy of the material, make the change, and reassign it onto the node.

When we introduce a new material model, we will probably change this behaviour.  We will probably do this by introducing a new material subclass that always returns true for `has_diffuse`, etc. and does not support calling `clear_diffuse`, etc.

If you are not using the shader generator you could also just consider setting the `enforce-attrib-lock` setting to `false` in Config.prc.

**Comment by rdb** [comment]
Come to think of it, I did make changes some time ago that allowed certain changes to TextureStage objects and have those tracked properly by the shader generator.  The cost, however, was that the cache of generated shaders had to be rehashed.

Do you think I should maybe apply the same fix to the material system?  That would allow you to clear/set colours on materials and have it work the way you expect, at a slight performance cost when rendering the next frame.

You can effectively already make this happen by setting `enforce-attrib-lock false` and calling `base.win.gsg.shader_generator.rehash_generated_shaders()` after such a material modification is made.

**Comment by Epihaius** [comment]
> Come to think of it, I did make changes some time ago that allowed certain changes to TextureStage objects and have those tracked properly by the shader generator. The cost, however, was that the cache of generated shaders had to be rehashed.

Yes, it was in a comment on that issue that I mentioned that reassigning an altered copy of the material was indeed how I changed any of its colours. You then replied that this was no longer necessary, which gave me the idea that locked attributes were something I no longer needed to worry about in general (which is kinda true, I just didn't realize that the config setting and `rehash_generated_shaders` call affected materials as well as texture stages).

> Do you think I should maybe apply the same fix to the material system? That would allow you to clear/set colours on materials and have it work the way you expect, at a slight performance cost when rendering the next frame.

That would definitely make things a lot more straightforward, so if you would be willing to do that, I for one would certainly appreciate it, thanks!

> When we introduce a new material model, we will probably change this behaviour. We will probably do this by introducing a new material subclass that always returns true for has_diffuse, etc. and does not support calling clear_diffuse, etc.

Okay, but then I do have one small concern. How would this new material model work with vertex colours?
With the current model it's possible to show the vertex colours by not explicitly setting a diffuse colour, while e.g. a specular colour can still be set to be mixed in with those vertex colours.

On a related note, if a node shows its vertex colours (i.e. no flat scenegraph colour is applied to it), the following glgsg error is generated (although no crash occurs) when a diffuse colour is set on it:

```
:display:gsg:glgsg(error): Could not find Cg varying vtx_color : ATTR3 (ATTR3) in the compiled GLSL program.
:display:gsg:glgsg(error): Try using a different semantic.
```

**Comment by rdb** [comment]
OK, I decided to just get rid of `enforce-attrib-lock`, since we can just have Panda do the right thing and invalidate all the states' shader keys, like I did in the solution to #178.  Now, everything should work as expected, and there are no non-obvious assertion errors.  Of course, you may experience a little performance chug after you do this if you have a lot of different states in your application.

> Okay, but then I do have one small concern. How would this new material model work with vertex colours?
> With the current model it's possible to show the vertex colours by not explicitly setting a diffuse colour, while e.g. a specular colour can still be set to be mixed in with those vertex colours.
We would probably have the behaviour toggled via the ColorAttrib rather than by whether or not a particular colour is set on the material.  The default setting would probably be to multiply the material's diffuse colour with the vertex colour.

As for the `vtx_color` error, I suspect that this is because the GLSL compiler is smart enough to optimise out that variable whereas the Cg compiler isn't.  I have checked in a change making ShaderGenerator a bit smarter such as not to write out this variable when not needed.  If you still encounter it after my change just yet, please give me a test case.

**Comment by Epihaius** [comment]
> I decided to just get rid of enforce-attrib-lock, since we can just have Panda do the right thing and invalidate all the states' shader keys, like I did in the solution to #178. Now, everything should work as expected, and there are no non-obvious assertion errors.

Thanks!

> We would probably have the behaviour toggled via the ColorAttrib rather than by whether or not a particular colour is set on the material. The default setting would probably be to multiply the material's diffuse colour with the vertex colour.

Sounds great!

> As for the vtx_color error, I suspect that this is because the GLSL compiler is smart enough to optimise out that variable whereas the Cg compiler isn't. I have checked in a change making ShaderGenerator a bit smarter such as not to write out this variable when not needed.

It's still happening, specifically when `set_color_off` is called on the node (before or after setting the diffuse material colour doesn't seem to matter).
See the following sample code:

```
from panda3d.core import *
from direct.showbase.ShowBase import ShowBase


class MyApp(ShowBase):

    def __init__(self):

        ShowBase.__init__(self)

        dir_light = DirectionalLight("light")
        light_np = self.render.attach_new_node(dir_light)
        light_np.set_hpr(-20., -20., 0.)
        self.render.set_light(light_np)
        self.render.set_shader_input("light", light_np)
        self.render.set_shader_auto()

        smiley = self.loader.load_model("smiley")
        smiley.reparent_to(self.render)
        mat = Material()
        mat.set_diffuse((1., 0., 1., 1.))
        smiley.set_material(mat)
        # the following line causes the vtx_color error
        smiley.set_color_off()

        self.cam.set_pos(0., -5., 2.)
        self.cam.look_at(0., 0., 0.)


app = MyApp()
app.run()
```

**Comment by rdb** [comment]
I think this is fixed now.

**Comment by Epihaius** [comment]
Yes, I can confirm that it works. Thanks again!
