### ISSUE TITLE
Interrogate-generated C++ files use Panda-styled absolute paths

### ISSUE THREAD

**Issue by CFSworks** [panda3d/panda3d#386]
If Interrogate is given an absolute path to a header, the generated C++ file will contain an absolute #include using a Panda-style (`/c/` vs. `C:\`) path; it should use an OS-specific path in order to be understood by the compiler.

Also, Interrogate might benefit from always using a relative path instead. However, I'm not sure about the ramifications of this. One upside is it allows the directory containing the generated C++ file (and all includes) to be relocated.

**Comment by rdb** [comment]
I've fixed this by calling `to_os_generic()` (which is like `to_os_specific()`, except that it uses forward slashes even on Windows).

I'm not opposed in principle to making it relative to the current source file automatically, but I think it'd be also safe to say that if people pass absolute paths, they should not expect to get relative paths out of it.  (Also note that it might actually make the resulting generated file less relocatable, not more, since moving it will invalidate references to other parts of a code base that aren't moved along with it.)
