### ISSUE TITLE
ShaderTerrainMesh has a different shape to BulletHeightfieldShape with same heightmap

### ISSUE THREAD

**Issue by typewriter1** [panda3d/panda3d#390]
When using ShaderTerrainMesh together with Bullet, what parameters do I need to set to make both shapes the same when using the same heightmap? Can they be synchronised?

**Comment by tcdude** [comment]
You need to offset the BulletHeightfieldShape by terrain 0.5 * (size_x, size_y, size_z). This is due to BulletHeightfieldShape having it's origin in the center of the shape, while ShaderTerrainMesh has it's origin at 0, 0, 0 (lower bottom left corner...).

This works, if you create both a TerrainShaderMesh and BulletHeightfieldShape of 
the same size/scale (eg. X/Y/Z as shown below): 

```python
shader_terrain_np.set_scale(X, Y, Z)
shape = BulletHeightfieldShape(YOUR_HEIGHTFIELD_IMAGE, Z, ZUp)
bullet_terrain_np = bullet_world_np.attach_new_node(BulletRigidBodyNode('Ground'))
bullet_terrain_np.node().add_shape(shape)
bullet_terrain_np.set_pos(X / 2, Y / 2, Z / 2)
```

**Comment by typewriter1** [comment]
OK
