### ISSUE TITLE
Crash when re-mounting multiple Multifiles in combination with AudioSound.play()

### ISSUE THREAD

**Issue by kamgha** [panda3d/panda3d#428]
I'm on Windows 7, Python 3.7.1 and OpenAL:

When mounting a Multifile, playing an Audio (via FlacAudio and/or VorbisAudio) inside it, stopping and unmounting and then repeating the first step (mounting + playing), Panda will crash. The crash will occur when the Multifile has been mounted and unmounted before once and when multiple Multifiles or Audio are involved. The crash will only occur, when re-mounting and .play()ing the Audio inside it are called immediately inside the same Frame. .play()ing the Audio after a while since the Multifile has been loaded, e. g. through an in-game user event will not cause a crash.

Sample code and media attached.

Steps to reproduce:
1. Press '1' to mount two Multifiles and load/play the Audio inside the files
2. Press '2' to stop and uncache the Audio, unmount the Multifiles
3. Repeat step '1' which will result in a crash

[mtest.zip](https://github.com/panda3d/panda3d/files/2499698/mtest.zip)

**Comment by rdb** [comment]
There's two issues here:

(1) Unmounting a multifile means that any open streams currently pointing to it become invalid, and will crash upon the next read
(2) `uncache_sound` does not properly clean up sounds that are loaded as streams.

It's not clear to me how to fix the first issue, but I do have a fix for the second issue.  I will merge this momentarily.  Then, calling `stop()` followed `uncache_sound()` should at least properly clean up the sound from the cache, so that it won't reuse a now-invalid sound object upon reloading it.

Thanks for reporting this issue!
