### ISSUE TITLE
Crash when re-mounting multiple Multifiles in combination with MovieTexture

### ISSUE THREAD

**Issue by kamgha** [panda3d/panda3d#449]
Similar to #429 , a crash when re-mounting a Multifile and re-reading a video file (MovieTexture) within may occur. The crash is reproducible, but several tries may be neccessary to trigger it.

Sample code attached, which is an extended variant of the sample code from #429. Repeat pressing keys 1 and 2 on the keyboard, until the crash occurs.

This issue may be related to #398.

**Stack trace:**
![mtseqf](https://user-images.githubusercontent.com/7195621/48320528-6a7ecb00-e61b-11e8-9345-f74a73bd70ef.png)

**Sample code:**
[mtest.zip](https://github.com/panda3d/panda3d/files/2570105/mtest.zip)

**Comment by rdb** [comment]
Thanks for the excellent test case!

The problem in this case is that even though the ffmpeg cursors are neatly closed, there may still be FFMpeg threads running that are using streams derived from the multifile, which will crash because the streams stop being valid the instant the multifile is closed.

This is essentially the same basic problem as #428, but this time I'm going to address the general problem: I'm going to keep the `.mf` file stream open as long as there are open substreams pointing to it, by counting the references to it.  I see no other way to fix this robustly; the alternative is that we suddenly return EOF on any open streams, but that would probably end up manifesting itself as a different crash in the ffmpeg decoder.

I also noticed some memory leaks in unloading streams properly; particularly, FlacAudioCursor doesn't close the stream when it's done with it.  I'm checking in a fix for that as well.
