### ISSUE TITLE
PStats heaps up old Threads

### ISSUE THREAD

**Issue by kamgha** [panda3d/panda3d#450]
(1) Threads will be listed in the menu-section at the top in the PStats UI. Once Threads finish, they will appear to be still alive in PStats.

(2) Sometimes/oftentimes, a created Thread will not appear in PStats.

Use the sample code from #449, which creates MovieTextures (MovieTextures create their own Thread). Repeat pressing 1 and 2 on the keyboard and observe, that Threads will not appear in PStats or will stay once finished.

May be related to #398 and/or #449.

**Screenshot:**

![pstats](https://user-images.githubusercontent.com/7195621/48320663-92baf980-e61c-11e8-8095-e170191786a3.png)

**Comment by rdb** [comment]
Darn, this appears to be an architectural limitation in PStats; it's designed to add threads but not to remove or rename them.  This would need to be changed in the client and in all the servers.

The fact that it sometimes doesn't seem to add a thread is because of an implementation detail; FFMpeg uses the pointer value of the thread as identifier, and PStats will reuse the same thread object if a new thread comes up with the same name and identifier.  So when the memory allocator happens to reuse the same bit of memory when allocating a new thread object, it will also reuse an existing thread in PStats.

**Comment by rdb** [comment]
This is fixed now (fix requires master version of client *and* server).

PStats no longer reuses a thread object with the same name.  An old thread will still linger in PStats now, but only as long as there is still data for it.  This means that after `pstats-history` (by default 60) seconds elapse, the thread information will be removed.  In theory we could also add a menu item to manually remove a thread sooner if this is desirable.

Perhaps, though, we should revisit the menu layout, grouping together threads under a single menu item.
