### ISSUE TITLE
sync-video 1 with multiple windows causes insane time in Wait:Flip:End

### ISSUE THREAD

**Issue by lachbr** [panda3d/panda3d#470]
Test case:
```
from panda3d.core import *
loadPrcFileData("", "load-display pandagl")
loadPrcFileData("", "sync-video 1")

PStatClient.connect()

from direct.showbase.ShowBase import ShowBase
base = ShowBase()

base.openWindow()
base.openWindow()
base.openWindow()

base.run()
```

[PStats with sync-video 0, four windows](https://gyazo.com/22665ec001a43f02b3d219bd2bda0778)
[PStats with sync-video 1, four windows](https://gyazo.com/c4c6f21ef0af8a76388bb412a7a6f2b2)

This is on Windows 10 with an integrated Intel graphics card, 60 Hz monitor refresh rate.

**Comment by rdb** [comment]
Well, intuitively, it kind of makes sense: after rendering every window, it waits until the next vblank opportunity before swapping the buffers.  But, it is not very useful behaviour here.

I do note that your code creates four different OpenGL contexts.  What happens if you create the other windows with the same OpenGL context?  This will allow you to share resources as well, so this is probably wise to do either way:

```python
base.openWindow(gsg=base.win.gsg)
base.openWindow(gsg=base.win.gsg)
base.openWindow(gsg=base.win.gsg)
```

If that doesn't help, we could look into the [WGL_NV_swap_group](https://www.khronos.org/registry/OpenGL/extensions/NV/WGL_NV_swap_group.txt) extension, although it is only supported on Quadro and AMD cards.

**Comment by lachbr** [comment]
Passing in the GSG fixes the problem. Thanks, I’ll close the issue.
