### ISSUE TITLE
Commit 49b72fb1985a40515eab9a1783d2a9d1bb7d8a47 breaks linking into a static .exe

### ISSUE THREAD

**Issue by theclashingfritz** [panda3d/panda3d#478]
This commit causes issues when statically linking to a .exe, The issue is that standard_type_members is now compiled into multiple of the python libs instead of the single it used to be in libp3interrogatedb. The resulting error is below.

core.lib(core_module.obj) : error LNK2005: "struct PyMemberDef * standard_type_members" (?standard_type_members@@3PAUPyMemberDef@@A) already defined in fx.lib(fx_module.obj)
physics.lib(physics_module.obj) : error LNK2005: "struct PyMemberDef * standard_type_members" (?standard_type_members@@3PAUPyMemberDef@@A) already defined in fx.lib(fx_module.obj)
ode.lib(ode_module.obj) : error LNK2005: "struct PyMemberDef * standard_type_members" (?standard_type_members@@3PAUPyMemberDef@@A) already defined in fx.lib(fx_module.obj)
egg.lib(egg_module.obj) : error LNK2005: "struct PyMemberDef * standard_type_members" (?standard_type_members@@3PAUPyMemberDef@@A) already defined in fx.lib(fx_module.obj)
direct.lib(direct_module.obj) : error LNK2005: "struct PyMemberDef * standard_type_members" (?standard_type_members@@3PAUPyMemberDef@@A) already defined in fx.lib(fx_module.obj)

Because of this i'm forced to locally revert the commit for now.

**Comment by darktohka** [comment]
Having the same issue: seems like when the Python libraries are built statically, a lot of these support symbols are built seperately into each module. Therefore, linking two static Python modules together results in these duplicate symbol errors.

**Comment by rdb** [comment]
Stopgap patch is this change to `interrogate_module`:

```
diff --git a/dtool/src/interrogate/interrogate_module.cxx b/dtool/src/interrogate/interrogate_modul
index 85c318f..1f5630d 100644
--- a/dtool/src/interrogate/interrogate_module.cxx
+++ b/dtool/src/interrogate/interrogate_module.cxx
@@ -639,8 +639,10 @@ int main(int argc, char *argv[]) {
      if (build_python_native_wrappers) {
        write_python_table_native(output_code);

-        // Output the support code.
-        output_code << interrogate_preamble_python_native << "\n";
+#ifdef LINK_ALL_STATIC
+        if (imports.empty())
+#endif
+          output_code << interrogate_preamble_python_native << "\n";
      }
    }
  }
```

**Comment by loblao** [comment]
I prefer 3. Options 1 and 2 feel a bit too hacky to me.

**Comment by CFSworks** [comment]
It looks like 7995d483abb addresses this. Should this be closed? Or does that commit only solve the specific errors reported above?

**Comment by rdb** [comment]
They're functions.  They can't be made static because they are used in multiple translation units (I tried going down that route but it added more bloat).

To leverage the ODR, I suppose we would have to mark all the functions inline.  Are we allowed to do that without actually providing the definition to the compiler in the translation unit where it's used?  I'm not sure whether that would work, but it seems worth a try.

I guess explicit weak linkage will work if the former option doesn't.  Might be the easiest solution for now.

**Comment by CFSworks** [comment]
I do know `extern inline` is a thing, but I haven't used it since I haven't needed to solve this kind of problem before. It might obviate the need to provide a definition in every translation unit, while still allowing multiple (equal) definitions throughout the program.

Weak linkage is fine but I do want to find something that's part of the core C++ standard, if possible. There's always the idea of using a dummy template, but that seems like it'd make the code look really messy.

**Comment by CFSworks** [comment]
Well, weak linkage can be achieved with `__attribute__((weak))` on GCC-style compilers and `__declspec(selectany)` on MSVC. Just stick it on the function/variable definition and we're good to go.

Something like this *feels* like it belongs in `dtoolbase_cc.h`, but if we're planning on refactoring later, maybe it should go in `py_panda.h` or somewhere else more specific to Interrogate. (Especially as we don't want to encourage this practice in the future.)

**Comment by rdb** [comment]
Yeah, the weak linking with GCC works, but `selectany` actually only works on data members and not on functions.

However, with some experimentation, it seems that MSVC 2015 *does* happily accept `extern inline`, despite it being a C++ feature.  So I'm just going to use the weak attribute on GCC-compatible compilers and for everything else, hope the compiler likes `extern inline`, as a stop-gap measure for the `LINK_ALL_STATIC` case in 1.10.

All that said, `py_panda.h` might as well be split up into a C and C++ header, since the functions in there only manipulate POD structures and call the Python API, with a C header for the core functions and a C++ header for the templates.  It nicely lets us circumvent this issue because C *does* support this feature.  But we can leave that for a cleanup effort; I don't have the time to spend on it right now.
