### ISSUE TITLE
NotImplementedError (unsupported format) using memoryviews

### ISSUE THREAD

**Issue by Epihaius** [panda3d/panda3d#485]
To optimize the geometry generation code of my project, I tried using memoryviews to efficiently copy the contents of one GeomVertexArrayData to another, with code similar to this:

```
from panda3d.core import *
from direct.showbase.ShowBase import ShowBase

class MyApp(ShowBase):
    def __init__(self):
        ShowBase.__init__(self)
        cm = CardMaker("card")
        cm.set_frame(0, 10, 0, 10)
        node1 = cm.generate()
        node2 = cm.generate()
        from_array = node1.get_geom(0).get_vertex_data().get_array(0)
        to_array = GeomVertexArrayData(from_array.array_format, from_array.usage_hint)
        to_array.unclean_set_num_rows(from_array.get_num_rows() * 2)
        size = from_array.data_size_bytes
        from_view = memoryview(from_array)
        to_view = memoryview(to_array)
        to_view[:size] = from_view  # this causes a NotImplementedError
        to_view[size:] = from_view
        node2.modify_geom(0).modify_vertex_data().set_array(0, to_array)

app = MyApp()
app.run()
```

However, it throws the following error:

`NotImplementedError: memoryview: unsupported format ffffffff`

Tested with Panda3D version 1.10.0.dev2100 (Python 3.7) on Windows 10 64-bit.

**Comment by rdb** [comment]
Panda3D will set the `format` string to something that matches the `GeomVertexFormat`.  From the Python documentation about the `format` string:

> A string containing the format (in struct module style) for each element in the view. A memoryview can be created from exporters with arbitrary format strings, but some methods (e.g. tolist()) are restricted to native single element formats.

So, the format in question does not support some operations.  As it happens, the slice operator is also subject to the same limitations (for some reason).

To get around this, you can cast the format to bytes:
```
        size = from_array.data_size_bytes
        from_view = memoryview(from_array).cast('B')
        to_view = memoryview(to_array).cast('B')
        to_view[:size] = from_view  
        to_view[size:] = from_view
```
Or to float, since the data seems to be entirely made out of floating-points anyway:
```
        size = from_array.data_size_bytes // 4
        from_view = memoryview(from_array).cast('B').cast('f')
        to_view = memoryview(to_array).cast('B').cast('f')
        to_view[:size] = from_view  
        to_view[size:] = from_view
```

I'm closing this since this is a shortcoming in Python, unless there is a good reason why we need to be returning something that is cast to bytes in the first place.

**Comment by Epihaius** [comment]
Ah, I see. Thank you for the clarification!
