### ISSUE TITLE
Assertion error while using the same heightfield texture to generate a mesh twice.

### ISSUE THREAD

**Issue by thetestgame** [panda3d/panda3d#492]
While attempting to build a test case for #489 I encounter this 
```
Assertion failed: _heightfield_tex->has_ram_image() at line 159 of c:\buildslave\sdk-windows-amd64\build\panda\src\grutil\shaderTerrainMesh.cxx
```
Seems to be directly linked to using the same heightfield image to generate a section of ShaderTerrainMesh instances more then once.
[shader-terrain-issue.zip](https://github.com/panda3d/panda3d/files/2713349/shader-terrain-issue.zip)

To test press f5 then f4 to clear and regenerate the terrain.

**Comment by rdb** [comment]
This is due to the fact that Panda automatically unloads textures from RAM after they have been uploaded to the GPU to save on memory.  The fix for this is calling `tex.keep_ram_image = True` on the heightfield texture after load if you intend to reuse it.

But, maybe ShaderTerrainMesh just needs to call `tex.reload()` or something in this situation.  Or it should call `set_keep_ram_image(true)` itself.

**Comment by thetestgame** [comment]
In a normal case I don't know as though it would be worth call it on its own. I will note however while working our game we encountered this same assertion as our first call for the texture for a ShaderTerrainMesh. We ended up having to bypass it with a PNMImage buffer to get it to load.
