### ISSUE TITLE
Advance cartoon-shader sample broken with Intel HD Graphics 630

### ISSUE THREAD

**Issue by Moguri** [panda3d/panda3d#495]
OS: Arch Linux (kernel: 4.19.12-1-ck-skylake)
GPU: Intel HD Graphics 630 (AMD Vega M GL displays correctly)
Panda3D version: 5d74411

When running advance.py in the cartoon-shader sample, I get random triangles getting outlined. Which triangles are outlined change frame by frame. It looks like the normals render-to-texture result is garbage.

![screenshot](http://pasteall.org/pic/show.php?id=b036d8234b1aa06c122a2a0c6b2cd5de)

**Comment by Moguri** [comment]
Upon further inspection, the AMD Vega M GL may also be displaying incorrectly. The render-to-texture result is all black on the AMD GPU.

![screenshot](http://pasteall.org/pic/show.php?id=29b229c6897f561a58ca7df6142a33fd)

**Comment by rdb** [comment]
An apitrace file would be helpful, thanks.

**Comment by Moguri** [comment]
[cartoon-shader.trace.log](https://github.com/panda3d/panda3d/files/2717717/cartoon-shader.trace.log)

Attached is an apitrace renamed to `.log` so it can be uploaded to GitHub.

**Comment by rdb** [comment]
This problem only seems to happen with `basic-shaders-only false`.  It seems to occur because the `normalGen.sha` shader declares the `vtx_normal` as `float4`.

The Cg runtime's GLSL generator, buggy as it is, doesn't deal with this well.  It makes a half-hearted attempt to adjust the column to `float3`, but ends up generating a shader that reads the w coordinate from random memory.

So, I'm just going to make a change that displays an error message when a `vtx_normal` column is not declared as a `float3`.
