### ISSUE TITLE
Issue when trying to call "ppython" or importing the panda3d modules after installation on Mac OS 10.14 Mojave.

### ISSUE THREAD

**Issue by AnythingTechPro** [panda3d/panda3d#502]
There seems to be an issue when trying to install a prebuilt panda3d binary from panda3d.org, when trying to install panda it installs to "/Developer" but you cannot import the modules from either "ppython" nor "python", also when building panda from the source it as well installs to "/Developer" but when trying to import it, it does indeed import but it seems to be importing from another path because i deleted all of the files in the "/Developer" directory and it was still able to import the "panda3d.core" module...

**Comment by rdb** [comment]
Thanks.  We should address this ASAP since 1.10 release is imminent.  Where did you install Python from?

Which Python versions did you tick in the Panda3D installer?

Do you have a file for your Python version called `/Library/Python/{ver}/site-packages/Panda3D.pth` ?  Does it contain `/Developer/Panda3D` ?

How did you install after building Panda from source?

**Comment by treamology** [comment]
There seems to be two separate issues here.

The first is that the `ppython` symlink is based on the location of the version of python used to generate the installer, so it may not point to a valid location once installed on another system. Also, if more than one version of python is supported in a single installer, the symlink is not written at all, which may not be the most intuitive choice.

The second issue is that it appears Python 3 no longer uses "/Library/Python/\*.\*/site-packages" as a directory for site packages, so the Panda3D.pth file that is written there will not be used. I'm not sure what another installation-location independent place would be for it. [This excerpt may be of relevance:](https://docs.python.org/3/library/site.html)

> If a file named “pyvenv.cfg” exists one directory above sys.executable, sys.prefix and sys.exec_prefix are set to that directory and it is also checked for site-packages (sys.base_prefix and sys.base_exec_prefix will always be the “real” prefixes of the Python installation). If “pyvenv.cfg” (a bootstrap configuration file) contains the key “include-system-site-packages” set to anything other than “false” (case-insensitive), the system-level prefixes will still also be searched for site-packages; otherwise they won’t.

**Comment by rdb** [comment]
Shoot.  OK, we need to find a solution for this today, since I'm about to make the release builds.  Is there any other location that Python 3 does search in on macOS, or a file we can install somewhere to make it look somewhere?

I see that on my mac, `/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages` is on `sys.path`, so I suppose we can try installing there, but I am guessing it wouldn't work with homebrew Python; is someone with a mac wiling to look into this for me?

**Comment by rdb** [comment]
I just did an experiment and apparently Python 3.4-3.6 do add `/Library/Python/{ver}/site-packages` to sys.path, but Python 3.7 does no longer.  I verified this by doing `import site; print(site.getsitepackages())`.

It would be great if some other macOS user could confirm this if they have time.

**Comment by tcdude** [comment]
I did as @rdb on El Capitan and got the same result:
Python 3.6 there is `/Library/Python/{ver}/site-packages` but with 3.7 I get `/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages` 

Tell me if I can do some other tests that could be useful for this issue

**Comment by rdb** [comment]
Thanks a lot.  My own build of Python 3.7 does add that directory but it is an older version of 3.7.  So I've checked in a change that makes it write the Panda3D.pth file additionally to the site-packages dir within the Python.framework dir for 3.7.

**Comment by rdb** [comment]
For the record, I researched this and apparently Python 2.7.13 is also affected.  I will check in a change that makes the fix apply to 2.7 (and 3.8+) as well.  Apparently [bpo-28440](https://bugs.python.org/issue28440) explains the context of the changed behaviour.
