### ISSUE TITLE
eggSaver doesn't properly handle exposed joins.

### ISSUE THREAD

**Issue by theclashingfritz** [panda3d/panda3d#507]
The current eggSaver doesn't properly handle exposed joints. This will result in exposed joints not being animated in a proper manner however they will still be present. The pictures below showcase the results.

**Comment by theclashingfritz** [comment]
Ok, Also dee4cd62017853f44bb54f6e6c764ba2b18cf90f might of fixed the issue originally but it also broke other processes and such we could never see the results of the fix in this scenario.

**Comment by lachbr** [comment]
@theclashingfritz This may be a bit off-topic, but there is an indirect solution that I came up with a while ago to work around this problem.

In a Python script, you can load the original .bam file, and make note of the joints that have been exposed and the geometry that has been flagged.

To find an exposed joint, the name of the node must exist as a CharacterJoint in the Character's joint hierarchy.
Any other node underneath the Character was originally flagged in egg-optchar, otherwise it wouldn't be visible.

You also have to make note of the children underneath each exposed joint, these nodes will have to be reparented to the respective joints later.

Once you get this data, run bam2egg, then egg-optchar, flagging and exposing the correct nodes and joints.

Convert the .egg back to .bam, then reparent any nodes that were once children of an exposed joint to that joint in the new .bam file. This does a pretty good job at preserving the original structure of the .bam file.

**Comment by theclashingfritz** [comment]
While this is good to know, It doesn't completely help. But thanks for the advice.

**Comment by Moguri** [comment]
Since this issue no longer has a repro example and we are unlikely to ever fix this (bam2egg is lossy, a huge time sync, and not very useful to general Panda users), I am closing this. Feel free to re-open this if you have new information or a repro example.

PRs for bam2egg are still welcome.
