### ISSUE TITLE
assimp: Add GenNormals and SmoothGenNormals support

### ISSUE THREAD

**Issue by el-dee** [panda3d/panda3d#511]
It would be nice to be able to configure in assimpLoader the post processing steps aiProcess_GenNormals and aiProcess_GenSmoothNormals.

GenNormals should be like assimp-calc-tangent-space, GenSmoothNormals requires an additional parameter for the smooth angle (or it could be enabled if the angle is != 0).

**Comment by rdb** [comment]
This looks like a rather simple task; we already have Config.prc variables for various Assimp flags defined in the `read()` function in `assimpLoader.cxx`.  Perhaps someone from the community could try their hand at this?

**Comment by tcdude** [comment]
@rdb: I would love to try my hand at it, but not sure if I'm up to it just yet. Looking at the code, this would mean to:
1. Add the missing config variables as requested above (assimp-gen-normals=false and assimp-smooth-normal-angle=0)
2. Define the new flags in read(), where one would distinguish if an angle != 0 is defined in smooth-normal-angle and thus deciding wheter to use GenNormals or GenSmoothNormals.
3. that's all? does the _importer.ReadFile(...) call do the rest, or would this need other changes as well?

**Comment by rdb** [comment]
@tcdude that sounds perfect.  You'd want to declare that config var as `ConfigVariableDouble`, and you'd need to use something like `importer.SetPropertyFloat(AI_CONFIG_PP_GSN_MAX_SMOOTHING_ANGLE, assimp_gen_smooth_normal_angle);` in order to specify the value to Assimp.

**Comment by tcdude** [comment]
@el-dee Since I haven't used assimp yet, could you test this for me before I submit a pull request to see if the expected result is achieved with my changes?
I've committed the change to my [fork](https://github.com/tcdude/panda3d/tree/assimp-gen-normals) of Panda3D in the branch called `assimp-gen-normals` with two new Config.prc variables called:

| Config Variable | Type | Default | Description |
| --- | :---: | --- | --- |
| `assimp-gen-normals` | bool | `false` | Set to true to generate normals<br> (if absent from file). |
| `assimp-smooth-normal-angle` | double | default=`0.0` | Crease Angle (in degrees, 180 = PI).<br> Face normal if set to 0, otherwise <br>smooth normal calculation is <br> performed |

It builds w/o error on my machine (Ubuntu 18.10 with Python 3.6) and I tested some of panda samples on the build, but as I stated before, I haven't used assimp and would like to make sure, the change provides the expected result.

**Comment by el-dee** [comment]
It works like a charm :)

Here is the loaded .obj model by default :

![screenshot-thu-jan-10-22-59-45-2019-664](https://user-images.githubusercontent.com/44778133/50999831-93dcaa00-152b-11e9-947a-66dab4772d64.jpg)

The same with "assimp-gen-normals #t"

![screenshot-thu-jan-10-22-59-59-2019-985](https://user-images.githubusercontent.com/44778133/50999839-97703100-152b-11e9-947b-24b44f5842fa.jpg)

And with "assimp-smooth-normal-angle 90"

![screenshot-thu-jan-10-23-00-15-2019-1107](https://user-images.githubusercontent.com/44778133/50999863-a656e380-152b-11e9-9137-ed9e3064f153.jpg)

Now if you could make the PR against the release/1.10.x branch instead of master it would be nice :)

**Comment by rdb** [comment]
Hmm… sure, I'd be OK with having this in 1.10.1, as long as these settings are disabled by default, given that this is a minor feature that does not affect the ABI.  So go ahead and make that PR against `release/1.10.x`.
