### ISSUE TITLE
Headless Nvidia

### ISSUE THREAD

**Issue by bhack** [panda3d/panda3d#557]
Is the egl headless context available for Nvida?

https://devblogs.nvidia.com/egl-eye-opengl-visualization-without-x-server/

**Comment by bhack** [comment]
This could be very useful in server-side/cloud contexts where GLX is not available. 
See https://github.com/nvidia/nvidia-docker/wiki/Frequently-Asked-Questions#is-opengl-supported

**Comment by Moguri** [comment]
As far as I can tell, Panda does not support this. The only EGL code I am seeing is for Android.

**Comment by rdb** [comment]
We do have an EGL back-end, but it's for OpenGL ES.  It would require some modifications to allow it to create an OpenGL context instead.  Panda's display architecture does not allow for this to be switched out at runtime.

Are you able to recompile Panda from source?

**Comment by zdens** [comment]
I see there is no answer from issue author, but I also faced with the problem running Panda3d on headless machine.
I have recompiled panda from source with some changes in `eglGraphicsPipe`-constructor at eglGraphicsPipe.cxx for testing purpose in order to use eglGraphicsPipe:

```c++
if (!_display) {
    static const int MAX_DEVICES = 4;
    EGLDeviceEXT eglDevs[MAX_DEVICES];
    EGLint numDevices;

    PFNEGLQUERYDEVICESEXTPROC eglQueryDevicesEXT = (PFNEGLQUERYDEVICESEXTPROC) eglGetProcAddress("eglQueryDevicesEXT");

    eglQueryDevicesEXT(MAX_DEVICES, eglDevs, &numDevices);

    printf("Detected %d devices\n", numDevices);

    PFNEGLGETPLATFORMDISPLAYEXTPROC eglGetPlatformDisplayEXT = (PFNEGLGETPLATFORMDISPLAYEXTPROC) eglGetProcAddress("eglGetPlatformDisplayEXT");

    _egl_display = eglGetPlatformDisplayEXT(EGL_PLATFORM_DEVICE_EXT, eglDevs[0], 0);
  }
  else
  {
    _egl_display = eglGetDisplay((NativeDisplayType) _display);
  }
```

with these modifications graphicsPipe was created successfully:
```python
>>> from panda3d.core import *
>>> loadPrcFileData('', 'window-type none')
ConfigPage , 1 declarations.
>>> base = ShowBase()                      
:audio(error):   load_dso(libp3openal_audio.so) failed, will use NullAudioManager
:audio(error):     libopenal.so.1: cannot open shared object file: No such file or directory
>>> ConfigVariableString('window-type', 'none').setValue('none')
>>> base.makeAllPipes()
Known pipe types:
  eglGraphicsPipe
(all display modules loaded.)
:display:x11display(error): Could not open display ":0.0".
Detected 1 devices
>>> base.pipe.type
eglGraphicsPipe
```
but unfortunately the next part was not successful:
 ```python
>>> pipe = base.pipe
>>> fbProps = FrameBufferProperties.getDefault()
>>> winProps = WindowProperties.getDefault()
>>> sort_order = 0
>>> bf = base.graphics_engine.makeOutput(pipe, 'def0', sort_order, fbProps, winProps, GraphicsPipe.BFRefuseWindow)
>>> bf == None
True
```
In my Config.prc-file there are strings:
```
load-display pandagles2

aux-display pandaegl
aux-display pandagles2
```
I understand that simply using `_egl_display = eglGetPlatformDisplayEXT(EGL_PLATFORM_DEVICE_EXT, eglDevs[0], 0);` is not enough because `_display` is null and all other attributes of parent `x11GraphicsPipe` object should also be determined, but what minimum list of attributes must be defined in order to create offscreen/no-screen buffer?

My original task is to render (obtain a screenshot) my model by means of panda3d on headless server with Nvidia GPU without Xserver.

Any help is appreciated!

**Comment by rdb** [comment]
It looks like the x11GraphicsPipe base class is setting `_is_valid = false;` due to the XOpenDisplay call failing.  You can try overriding it by setting it to true in the eglGraphicsPipe constructor.

**Comment by rdb** [comment]
I got curious enough to try it for myself and it turns out there more changes necessary.

I've just implemented those changes on the master branch—it's now possible to get a headless GLES 2 pipe, open an offscreen buffer and get it to render to a texture.  You can compile Panda without X11 support and pandagles2 will still be available.

What's missing is support for binding it to the OpenGL API; right now you'll get OpenGL ES.

**Comment by zdens** [comment]
Wow! Great work! Thank you!

I managed to compile your code but in my environment the line `_egl_display = eglGetDisplay(EGL_DEFAULT_DISPLAY);` still  throws the EGL_NOT_INITIALIZED error while trying to do `base = ShowBase()`.

After I've added code from [my previous post](https://github.com/panda3d/panda3d/issues/557#issuecomment-630955455) with `_egl_display = eglGetPlatformDisplayEXT(EGL_PLATFORM_DEVICE_EXT, eglDevs[0], 0);` that error had been vanished.

And the next part of my python code did not get me screenshot, I need to research the subject "render to texture".

**Comment by rdb** [comment]
I noticed that as well; `eglGetDisplay(EGL_DEFAULT_DISPLAY);` did work for me but only when compiling Panda without X11 support (`--no-x11` in makepanda).  I would add the `eglGetPlatformDisplayEXT` to Panda as a fallback but only when we can come up with a more robust system to do the device selection.

I recall I used something like this to get a screenshot:
```
base = ShowBase(windowType='offscreen')

model = loader.loadModel("environment.egg")
model.reparentTo(base.render)

base.graphicsEngine.renderFrame()
base.graphicsEngine.renderFrame()
base.screenshot()
```
Avoiding ShowBase and instead using the more low-level makeOutput method should in principle work too (but you might want to disable back-buffers in Config.prc, which are otherwise part of the default FrameBufferProperties—I don't think offscreen buffers are double-buffered!), though you would additionally need to call addRenderTexture to bind a texture and probably set the RTM_copy_ram flag to tell Panda to transfer the texture contents to system memory automatically.

**Comment by zdens** [comment]
I recompiled with `--no-x11` key, yet no luck with `EGL_DEFAULT_DISPLAY`. I'll try to check it once again later on clean machine.

Screenshot getting problem is probably connected with double-buffering because either `pnmimage.write()` with the low-level `makeOutput` technique or `base.screeenshot()` both do create an image file but it is empty.

**Comment by rdb** [comment]
Be sure to call renderFrame, possibly twice if necessary due to double-buffering.  Also, be sure you are working with the latest master (and haven't just cherry-picked that one commit)—I did find a bug in code that copies textures to RAM in OpenGL ES, but I fixed that in a separate commit.

If you can't get it to work, even with my code, install apitrace and create a trace file with `apitrace -a egl trace python yourcode.py`, and share the .trace file.  By loading it into qapitrace we can then see all the OpenGL ES calls being made by Panda and we'll be able to find out why the texture data isn't being copied.

Setting `gl-debug true` in Config.prc, if the driver supports it, will cause more error messages to be generated by the GL back-end.

My full testing script was this:
```python
from panda3d.core import *

load_prc_file_data("", "load-display pandagles2")
load_prc_file_data("", "notify-level-egldisplay spam")
load_prc_file_data("", "gl-debug true")

from direct.showbase.ShowBase import ShowBase

base = ShowBase(windowType='offscreen')

model = loader.loadModel('environment')
model.reparentTo(base.render)

base.graphicsEngine.renderFrame()
base.graphicsEngine.renderFrame()
base.graphicsEngine.renderFrame()
base.graphicsEngine.renderFrame()

base.screenshot('test.jpg', defaultFilename=False)
```

**Comment by zdens** [comment]
I recompiled again my `EGL_PLATFORM_DEVICE_EXT` and with keys:
```sh
--everything --wheel --no-x11 --no-gles
```
and your test script managed to save screenshot.

In case the key `--no-gles` is not specified the compilation is failing with the "file <GLES/egl.h> not found" error (as it is included in eglGraphicsPipe.h).

I'll try to check `EGL_DEFAULT_DISPLAY` tomorrow.

Could you please explain why `renderFrame` is called 4 times?
In my low-level script I called if 2 times and got empty file...

**Comment by rdb** [comment]
Overabundance of caution.  Two calls seem to work just fine for me.  Normally you need one to do the rendering and an extra one because the back buffer of the previous frame is flipped at the beginning of the next one.

Sidenote, I just added support for using regular OpenGL through EGL.  If you compile Panda3D without X11 support, libpandagl will be built using EGL, and it should work headless.  I've done only limited testing, though.

**Comment by zdens** [comment]
I've pulled code of new revision and rebuilt it, , .trace file is [attached](https://github.com/panda3d/panda3d/files/4662755/python3.7.trace.zip).

**Comment by rdb** [comment]
That's just a trace of eglInitialize failing.  I meant a trace that had the copy-to-texture operation fail to produce a texture.

**Comment by zdens** [comment]
with the fresh version of code and my patch with 
```c++
_egl_display = eglGetPlatformDisplayEXT(EGL_PLATFORM_DEVICE_EXT, eglDevs[0], 0);
```
the script
```python
from panda3d.core import *
load_prc_file_data("", "load-display pandagles2")
load_prc_file_data("", "notify-level-egldisplay spam")
load_prc_file_data("", "gl-debug true")
loadPrcFileData("", "audio-library-name null") # Prevent ALSA errors
from direct.showbase.ShowBase import ShowBase
ConfigVariableString('window-type', 'none').setValue('none')
    base = ShowBase()
    base.makeAllPipes()
    pipe = base.pipe
    fbProps = FrameBufferProperties.getDefault()
    winProps = WindowProperties.getDefault()
    sort_order = 0
    bf = base.graphics_engine.makeOutput(pipe, 'def0', sort_order, fbProps, winProps, GraphicsPipe.BFRefuseWindow)
dr = bf.makeDisplayRegion()
    base.setBackgroundColor(0, 0, 0, 0, bf)
    cam_node = Camera('cam')

    cam_np = NodePath(cam_node)
    # camNP.setHpr(0, 30, 0)
    dr.setCamera(cam_np)

    render2 = NodePath('render2')  # the string parameter is important
    cam_np.reparentTo(render2)
    node = GeomNode('gnode')
    node.addGeom(gc)
    node_path = NodePath(node)
    node_path.setPos(LPoint3f(0, 5, 0))
    node_path.reparentTo(render2)
    print('position: {}; bounds: {}'.format(node_path.getPos(), node_path.get_bounds()))

    directional_light = DirectionalLight('directionalLight')
    directional_light.setShadowCaster(True, 512, 512)
    directional_light_np = render2.attachNewNode(directional_light)
    directional_light_np.setHpr(-45, 0, 0)
    render2.setLight(directional_light_np)
    # base.camera = camNP
    base.graphicsEngine.renderFrame()
    #base.graphicsEngine.flipFrame()
    base.graphicsEngine.renderFrame()
    pnmimage = PNMImage()
    if dr.getScreenshot(pnmimage):
        pnmimage.write("/panda/screenshot3.png")
```
created an image file with the rendered model without any error.
in `node.addGeom(gc)` gc stands for my shape geometry container, the shape is simple rectangular box.
so I think I can move further in my task.
@rdb , thank you very much!

**Comment by rdb** [comment]
Great!  Please note that with the latest changes you should be able to just use `pandagl` as well, and get all the features of desktop OpenGL.

**Comment by ohouha** [comment]
I successfully build panda3d on my headless docker, but I notice I just use opengles2 in my docker, is there anyway I can just use pandagl+egl? and also I find this awesome git https://github.com/tobspr/RenderPipeline, I want to put it in the docker, do you think I can use pandagl to use this git? cuase I think it just supports opengl 4.3+. Thank you.

**Comment by rdb** [comment]
Yes, you can just use pandagl+egl, which is what you get when you compile without X11.

I *think* the RenderPipeline requires 4.3 so it may work.

**Comment by ohouha** [comment]
when I tried to use pandagl+egl, and it shows the error:
Known pipe types:
  eglGraphicsPipe
(all display modules loaded.)
Detected 1 devices
:display:egldisplay(error): Could not create EGL context!
EGL_BAD_ATTRIBUTE
:display:egldisplay(error): Could not find a usable pixel format.
:display:gsg:glgsg(warning): Unable to query GL_VENDOR
:display:gsg:glgsg(warning): Unable to query GL_RENDERER
:display:gsg:glgsg(warning): Unable to query GL_VERSION
:display:gsg:glgsg(error): Unable to detect OpenGL version
:display:gsg:glgsg(warning): Unable to query GL_VENDOR
:display:gsg:glgsg(warning): Unable to query GL_RENDERER
:display:gsg:glgsg(warning): Unable to query GL_VERSION
:display:gsg:glgsg(error): Unable to detect OpenGL version
:ShowBase(warning): Unable to open 'offscreen' window.
Traceback (most recent call last):
  File "test_egl.py", line 9, in <module>
    base = ShowBase(windowType='offscreen')
  File "/usr/local/lib/python3.8/dist-packages/direct/showbase/ShowBase.py", line 333, in __init__
    self.openDefaultWindow(startDirect = False, props=props)
  File "/usr/local/lib/python3.8/dist-packages/direct/showbase/ShowBase.py", line 1014, in openDefaultWindow
    self.openMainWindow(*args, **kw)
  File "/usr/local/lib/python3.8/dist-packages/direct/showbase/ShowBase.py", line 1049, in openMainWindow
    self.openWindow(*args, **kw)
  File "/usr/local/lib/python3.8/dist-packages/direct/showbase/ShowBase.py", line 794, in openWindow
    raise Exception('Could not open window.')
Exception: Could not open window.
 
Do you have any hints that I can check?

**Comment by Clockwork-Muse** [comment]
@ohouha - How are you getting that to build?

@rdb - I've been trying to get this working, but for whatever reason `libpandagl.so` never gets built at all:
```
python makepanda/makepanda.py --everything --threads 6 --optimize 4 --no-opencv --use-egl --no-x11 --verbose --outputdir /some_build_dir/built-wheel > /some_build_dir/build_output.txt
```
[build_output.txt](https://github.com/panda3d/panda3d/files/5718085/build_output.txt)

As near as I can tell, it's finding EGL (`/some_build_dir/tmp/dtool_have_egl.dat` contains `1`).  Leaving off `--no-x11` does result in a working panda version (installed as a wheel).  Otherwise the build succeeds, but fails at runtime when `ShowBase.run()` is called (because no display pipe).

**Comment by rdb** [comment]
@Clockwork-Muse Well, you're trying to build the 1.10.7 source, but the changes you need are on the master branch.  Build the latest sources from GitHub and it should work.

**Comment by Clockwork-Muse** [comment]
@rdb - Yes, that's done it, thank you (I guess I was expecting the branching strategy to be different)

**Comment by Clockwork-Muse** [comment]
@ohouha - 
I haven't seen that error, but I've been able to get it to run in a container (and get rendered images out).
I'm using the `nvidia/opengl:1.2-glvnd-runtime` image as my base (since that one is already set up for EGL/glvnd).
After installing whatever missing dependencies are needed, you run it with something like:
```
// --gpus=all tells the docker runtime to expose the gpu to the container
// You need to mount /dev/input.  This might be able to be eliminated, or point to an empty directory.  This is technically a security hole.
docker run --gpus=all --mount source=/dev/input,target=/dev/input,type=bind,consistency=cached <image name here>
````

**Comment by duburcqa** [comment]
> Yes, you can just use pandagl+egl, which is what you get when you compile without X11.

@rdb Will this feature be available without recompiling Panda3d in the future ? I critically need it for both linux and windows, but I cannot resuest the user of my own project to compile Panda3D by themself :/ I'm working on machine learning applications computing on cluster without graphical server, requiering rendering for both monitoring and training.

**Comment by rdb** [comment]
@duburcqa I'm open to thinking about a quick temporary solution, but let's discuss that in #1086.

**Comment by rdb** [comment]
I just checked in a pair of changes (2e38ca10429d904455bcfdeb395e2f20c50b01f2 and 2d9cc2dea0ba543958037454712669acc0afa433) that add support for the EGL_EXT_platform_device extension.  Panda will now iterate through the list of available EGL devices until it finds one that works.  This should hopefully fix the EGL_NOT_INITIALIZED issue with EGL_DEFAULT_DISPLAY.

**Comment by zdens** [comment]
@rdb , thank you!
we'll try to apply these changes a bit later after we finish exploration of memory leak problem with `self.base.graphicsEngine.renderFrame()` in our scripts.

**Comment by rdb** [comment]
For the record, these changes have been backported to 1.10.9, which will be released later this week.
