### ISSUE TITLE
Sound effects continue playing after stop has been called.

### ISSUE THREAD

**Issue by mfwass** [panda3d/panda3d#559]
`set_active(true)` on a sound manager will resume all paused sounds.

If you call the `stop` method within `libpanda.AudioSound` while `base.enableSoundEffects` is set to `False`, the audio does not stop as it should. When you re-enable `base.enableSoundEffects`, the existing sound effect(s) will continue to play unless `stop` is called a second time after being re-enabled.

[test-case-audio-issue.zip](https://github.com/panda3d/panda3d/files/2873719/test-case-audio-issue.zip)

**Comment by rdb** [comment]
The problem is that `manager.set_active(x)` basically calls `sound.set_active(x)` on every one of its sounds in the OpenAL implementation, and `sound.set_active(x)` will stop/play a sound.  What you're expecting is that deactivating and activating a sound is different than stopping/playing it, which is not how the system is designed to work.

It's arguable that how it's designed is not particularly useful in this case.  We could possibly remedy this by decoupling the "active" state of a manager from the "active" state of any of its sounds, or by decoupling the "active" state of a sound from its play/stopped state, but in either case this is a non-trivial change.

I added the "discussion" label; I'm hoping to see some feedback from others about what the most intuitive way to handle this is.

**Comment by ArsThaumaturgis** [comment]
Hmm... I don't think that I've bumped into this behaviour myself, so my thoughts are speculative, and thus should perhaps be taken with salt.

That said, the current behaviour, as described above, seems unintuitive to me. 

I think that I would expect that a sound that has been stopped would remain stopped, with activation of the relevant audio manager being irrelevant to its state.

Conversely, I would expect sounds that were playing to stop when their audio manager was disabled, and then resume when it was enabled.

Or in short, I would expect that deactivating an audio manager would cause all of its sounds to cease playing, and that activating an audio manager would put all of its sounds into the state to which they've been set: playing if they were set to play, and not playing if they were stopped.

**Comment by rdb** [comment]
Changing this back to "bug".  While we *should* have a discussion about the unintuitive behaviour of the active flag, in further review of this, the problem in question really is a bug; the _paused flag should be set to `false` by `stop()` in order to prevent the sound from being resumed when sounds are reenabled.
