### ISSUE TITLE
Issue Prioritization

### ISSUE THREAD

**Issue by Kupoman** [panda3d/panda3d#598]
In order to improve collaborator alignment on tasks that offer the most value to Panda3D users, it would be nice if issues were prioritized in some way. My suggestion is to use a GitHub project to create a prioritized backlog. This would include most to all tasks sorted by priority, with the highest priority tasks at the top of the list.

Alternatively, GitHub labels could be used to indicate groups of priority (e.g. high, medium, low).

**Comment by Moguri** [comment]
To expand on this a bit with some things that @Kupoman and I have been talking about, I have the following suggestions/thoughts:
* Create a generic "Roadmap" project that includes "core" tasks (ones deemed important enough to spend core contributor resources on). We can try to re-purpose the existing 1.11 board for this or scrap that board and make a new one.
* Create the following columns: Design, Ready, In Progress, Review, Done (I can go more into the reasoning behind these specific columns if desired)
* All items in the project should link to an issue with clear goals or conditions of satisfaction (probably look into something like  [INVEST](https://en.wikipedia.org/wiki/INVEST_(mnemonic)))
* Break projects down into independent, parallel tasks (e.g., "shaderpipeline" or "cmake" can be broken down a lot)
* When enough/appropriate tasks are in the done column (i.e., goals for the release have been met), we can clear the column and do a release

**Comment by rdb** [comment]
I agree that a clearer organisation of tasks can help collaborators get involved.  It would be ideal to find a way to do so involving minimal bureaucracy.  It does sound like @Kupoman's suggestion aligns with the GitHub project I had already created to manage the roadmap.  If that's not what you had in mind, I'd like to hear more.

I agree with the idea of breaking down large tasks.  That said, I'm not convinced that a single Roadmap is a good idea; I worry that it quickly threatens to ruin the main advantage of a Project, which is that it provides an easy overview of the tasks that matter the most at the moment, by filling it with too much stuff at once.  I would maybe suggest that eg. "CMake" and "New shader system/PBR" should have their own Projects, since these don't interact and are generally done by separate people.  (I don't think that projects should reflect releases like we have now, since this is inflexible and we already have milestones for that after all.)

While we're on the topic, I also think we should establish a policy on what to do with lower-priority issues.  While it's unlikely that a core contributor is able to get to certain issues or finish certain abandoned PRs, it might be worth leaving them open so that external contributors can find things to get their feet wet with.  Thoughts?

**Comment by Kupoman** [comment]
I think a single project or multiple projects can work. With multiple projects it might be easier for someone to find tasks that align more with their area of interest. A task can be part of multiple projects, which gives us some flexibility with multiple boards. For example, a task can be part of a "Shader Pipeline" and "Roadmap" project. I don't know if tracking a task through multiple boards would become too much of a burden, but it is nice to now we have that flexibility.

I don't think low priority issues are too much of a problem, as long as they are well prioritized and labeled. In general the open bug count should be kept low, but I would not worry about other issues piling up a bit. I would only worry about a solution for low priority issues when they start becoming a problem.

Abandoned PRs are a bit more tricky. On the one hand, they clutter things up and could make it look like project maintainers are not addressing PRs well. On the other hand, I can see not wanting to abandon partially done work. In general I would be aggressive about closing pull requests since they could always be re-opened later. Maybe something like closing any PR that has been marked as "requires change" and has not been responded to by the PR owner in 3 months.

**Comment by Kupoman** [comment]
Closing this issue since the discussion seems more or less complete.
