### ISSUE TITLE
Rendering multiple cameras in parallel

### ISSUE THREAD

**Issue by andyljones** [panda3d/panda3d#630]
Short version: how difficult would it be for me to adapt panda3d's renderer to render multiple cameras in parallel?

Long version: I'm using panda3d as a simulator for some reinforcement learning work. Reinforcement learning involves simulating millions of instances of a task, and many of those instances can be run in parallel. The easiest way to parallelise a simulator is to spin up a bunch of processes, and run an entirely separate copy of the simulator in each process. That involves a lot of overhead though, so a popular trick is to stick a bunch of instances in the same simulator, [a la](https://www.youtube.com/watch?v=nilcJY5Kdt8):

![image](https://user-images.githubusercontent.com/662606/56612296-e722c600-660b-11e9-94da-1c3e8270e971.png) 

That example is bottlenecked by the physics engine. My work is bottlenecked by the renderer: each instance has its own camera, and rendering those cameras is done sequentially. As such, I don't get much speedup from the many-instances-one-simulator trick. There's no fundamental reason that should be the case though, and so my question: how difficult would it be for me to modify panda3d's renderer to render multiple cameras in parallel?

To be clear, this isn't a feature request. It's a very niche issue and I'm just curious whether it's a simple thing I could knock out in a few days, or if it'd require changing huge chunks of panda3d's renderer.

**Comment by rdb** [comment]
For the record, I think this kind of open-ended question is generally better suited to the forums, rather than on the bug tracker.  The issue tracker is specifically used as a developer TODO list, so it needs to contain actionable items.

Could you clarify what you mean by "in parallel?"  Do you want the same render pass to render the same scene from many different viewpoints at the same time?  This is actually possible in Panda, with a bit of effort.  The way this works is by instancing the scene multiple times, having each instance render with a different projection matrix, and having each instance write to a different part of the render target texture.

First, you need to disable culling by setting `view-frustum-cull false` in Config.prc or by setting an `OmniBoundingVolume()` on the scene or as your camera bounds.  Second, you need to enable instancing with `setInstanceCount` on your entire scene, for as many cameras as you have.  Third, use your own mechanism for passing the view projection matrix of each camera to the shader in a big array, and writing your vertex shader to use that instead of `p3d_ViewProjectionMatrix`.  Fourth, you need to choose between two methods to output the render result:
* Use layered render-to-texture; this works by binding an array texture using render-to-texture as render target, with `RTM_bind_layered` mode.  You use a geometry shader applied to your scene to write the current instance index to `gl_Layer` to tell it to render the current instance to its own layer.
* Use a big atlas texture where you render the different scene instances into different subregions of the same texture.  This is done by calling `setNumRegions(n)` on the DisplayRegion, setting the dimensions of each using `setDimensions(i, (l, r, b, t))`, and writing the current instance index to `gl_ViewportIndex` in a geometry shader.

The big downsides of this approach are:
* No culling, since Panda needs to pass the full scene to the GPU, not just the objects that are in view of a camera.  If you have many cameras, though, the cost of sending the scene to the GPU many times might far outweigh the benefits of culling, so this may be worth it.  Doing some amount of culling in the geometry shader may be possible.
* There is overhead associated with even having a geometry shader active.  Some IHVs have specific extensions to get around this; the most straightforward one being GL_AMD_vertex_shader_layer / GL_AMD_vertex_shader_viewport_index, which allow you to write the index in the vertex shader, obviating the need for a geometry shader.  I think NVIDIA might have a passthrough shader that does something similar.

**Comment by andyljones** [comment]
Thanks very much @rdb, that's exactly the information I was after. It's complex enough that it pushes the idea down my work schedule, but still plausible as a whole.

And pardon me, will use the forum in future.
