### ISSUE TITLE
Suggestion: More verbose deprecation prints

### ISSUE THREAD

**Issue by mfwass** [panda3d/panda3d#669]
When tracking down deprecations in a large project, it can be difficult to be able to locate the specific line and file in which a deprecation print originates.

For example, the `NodePath.remove()` deprecation print shown below will spam in the program output. It would be extremely helpful to be able to see which file and line in particular is raising this warning.

```
Warning: NodePath.remove() is deprecated.  Use remove_node() instead.
```

A potential improved output could be the following:

```
Warning (fakepath.YourNodePathFile:L32): NodePath.remove() is deprecated.  Use remove_node() instead. 
```

This could be accomplished using `inspect`.

```python
from inspect import currentframe, getframeinfo
frameinfo = getframeinfo(currentframe())
print(frameinfo.filename, frameinfo.lineno)
```

Source: https://stackoverflow.com/questions/3056048/filename-and-line-number-of-python-script

**Comment by rdb** [comment]
I'd be OK with some sort of a traceback protected under an `if __debug__:` block.

Another option is to use the `warnings` module which allows you to run Python with `-W error` to turn every warning into a fatal error (or create a Panda config variable with similar effect).

**Comment by paustian** [comment]
This one looks like some simple line switching and would be a good first effort for me. Just to make sure I am understanding, all the Warnings for deprecations in the code would need to just have the file and line no. where they occur added. This should be pretty easy to do. 

For example in NodePath_extenstions.py on line 17 it says

print("Warning: NodePath.id() is deprecated.  Use hash(NodePath) or NodePath.get_key() instead.")

Would be changed to:

print("NodePath_extentions.py:L17 - Warning: NodePath.id() is deprecated.  Use hash(NodePath) or NodePath.get_key() instead.")

I think I would prefer to make these changes semi-manually since there are a ton of them.
Let me know if this is what's desired and I can get at it.

**Comment by rdb** [comment]
I think we should look at leveraging the Python warnings module, or something else that can look at the call stack and figure out which file it's being called from.  It would be a maintenance burden if we had to update the line number every time we moved around some code.

**Comment by paustian** [comment]
True. I will look into the python warning module.

**Comment by paustian** [comment]
So it looks like every file with a warning would need a bit different code. The old code is:

`print("Warning: NodePath.id() is deprecated. Use hash(NodePath) or NodePath.get_key() instead.")`

You would need at the top of the file:

`import warnings`

Then later in the file:
`warnings.warn("NodePath.id() is deprecated. Use hash(NodePath) or NodePath.get_key() instead.", DeprecationWarning, stacklevel=2)`

By doing stacklevel=2 it will list the line that called the function, not the deprecated function.
