### ISSUE TITLE
Add better support for hybrid graphics

### ISSUE THREAD

**Issue by Moguri** [panda3d/panda3d#680]
The NVIDIA driver does not automatically use the stronger NVIDIA card in an Optimus setup when running OpenGL games. It only automatically uses the NVIDIA GPU if the application is statically linked with one of the following libraries: vcamp110.dll, vcamp110d.dll, nvapi.dll, nvapi64.dll, opencl.dll, nvcuda.dll, and cudart*.*. There is a `NvOptimusEnablement` symbol we can export to "direct the Optimus driver at runtime to use the High Performance Graphics." Looks like AMD uses a similar symbol called `AmdPowerXpressRequestHighPerformance`. I believe we can set these both to 0x1 by default and find a way to let users disable them (e.g., via a PRC variable).

[Docs for Optimus](https://docs.nvidia.com/gameworks/content/technologies/desktop/optimus.htm)
[Docs for AMD](https://gpuopen.com/amdpowerxpressrequesthighperformance/)

**Comment by rdb** [comment]
I looked into this a while ago.  I don't believe that overwriting it at runtime works.  But, we can add the symbols to deploy-stub, and have deploy-ng rename the symbol in the exports table if need be.

**Comment by Moguri** [comment]
That's unfortunate. I guess we could have a section in the manual on hybrid graphics and letting people know to use something like the NVIDIA control panel while using SDK builds?

**Comment by rdb** [comment]
That sounds like a good idea to me.

**Comment by treamology** [comment]
This may be a good opportunity to do something similar on macOS, though for the opposite reason. macOS automatically switches to dedicated graphics  when it detects an OpenGL context, and there’s no easy way to manually switch it back to integrated on the part of the user. I believe there’s a way to hint to the OS that you’d prefer integrated graphics, but I’ll have to look into it.

**Comment by rdb** [comment]
I looked into supporting this on Linux.  It's possible to do this for the [NVIDIA drivers](https://download.nvidia.com/XFree86/Linux-x86_64/435.17/README/primerenderoffload.html), by setting `DRI_PRIME=1` in the environment, but I have to use additional settings to force it to use the proprietary NVIDIA drivers, otherwise it will try to use nouveau, which probably isn't what you want with this option, and they may not even be available causing the application to fail to start.  I also have to use the modesetting instead of the intel driver, which has horrible flickering issues for me.  I don't feel confident about the reliability of being able to set this on Linux, so I suggest we don't mess with these settings.  If the user really wants to do this, they can manipulate `os.environ` before opening the Panda window, which appears to be effective.

In a .desktop file, there is the `PrefersNonDefaultGPU=true` key we can set.  This could be considered as part of #733.
