### ISSUE TITLE
DS_interrupt doesn't interrupt all task chains

### ISSUE THREAD

**Issue by loblao** [panda3d/panda3d#692]
When a Python exception happens in a task it returns DS_interrupt which causes the current chain to stop polling.

However, the task manager goes ahead and polls the next chain which may shadow the Python exception or trigger an [assertion](https://github.com/python/cpython/blob/3.6/Python/ceval.c#L1141) when Python is built in debug mode.

**Comment by el-dee** [comment]
I reported what I think is a similar problem a few months ago, see https://discourse.panda3d.org/t/task-aborted-with-an-exception-is-respawned-endlessly/24701 for more details and code to reproduce the problem. It seems DS_interrupt has a faulty behaviour with task chains.

As I never got any feedback about it and as I don't know if this is a bug or a feature, I stopped investigating and used instead a crappy workaround in my code :)

**Comment by rdb** [comment]
Ah, I think this is a bug since I think DS_interrupt is intended to interrupt the entire task manager.  I'm not entirely sure how it's intended to work with threaded task chains, though.

I did remember @el-dee's issue but I could not find it in the issue tracker when I searched for it.

I think this has a straightforward fix, and I think it's worth getting this into 1.0.4.

**Comment by el-dee** [comment]
Sadly the problem is still present in 1.10.4.1 with threaded taskchain (I should have tested it before the release :( ) A task belonging to a threaded taskchain raising an exception is restarted again and again.

Here is the test code :

```python
#!/usr/bin/env python

from direct.showbase.ShowBase import ShowBase
from panda3d.core import PandaSystem

import platform

def processTask(task):
    print("Hello")
    raise Exception()
    print("Goodbye")
    return task.done

base = ShowBase()

print("Python version:", platform.python_version())
print("Panda version: %s (%s)" % (PandaSystem.getVersionString(), PandaSystem.getGitCommit()))

base.taskMgr.setupTaskChain("chain",
                            numThreads = 1,
                            tickClock = False,
                            threadPriority = None,
                            frameBudget = -1,
                            frameSync = False,
                            timeslicePriority = True)

process_task = base.taskMgr.add(processTask, 'ProcessTask', taskChain="chain")

base.run()
```

Here is the output :
<pre>
Known pipe types:
  glxGraphicsPipe
(all display modules loaded.)
Python version: 3.5.2
Panda version: 1.10.4.1 (1318fd80d7fd48a84394ee86bad6a57c245206e1)
Hello
:thread(error): Exception occurred within Thread TaskManager_chain_0
Traceback (most recent call last):
  File "tests/test_tc.py", line 10, in processTask
    raise Exception()
Exception
:task(error): Exception occurred in PythonTask ProcessTask
Hello
:thread(error): Exception occurred within Thread TaskManager_chain_0
Traceback (most recent call last):
  File "tests/test_tc.py", line 10, in processTask
    raise Exception()
Exception
:task(error): Exception occurred in PythonTask ProcessTask
Hello
:thread(error): Exception occurred within Thread TaskManager_chain_0
Traceback (most recent call last):
  File "tests/test_tc.py", line 10, in processTask
    raise Exception()
Exception
:task(error): Exception occurred in PythonTask ProcessTask
Hello
</pre>

**Comment by rdb** [comment]
@el-dee Could you create a new issue for that?  That seems subtly different since it is happening in the multi-threaded case.  The single-threaded case is what was fixed here.

**Comment by el-dee** [comment]
Done, see #710
