### ISSUE TITLE
Mouse control in Wayland

### ISSUE THREAD

**Issue by Schwarzbaer** [panda3d/panda3d#746]
Constraining / setting the mouse requires special protocols in Wayland for security reasons.

https://github.com/wayland-project/wayland-protocols/tree/master/unstable/pointer-constraints
https://github.com/wayland-project/wayland-protocols/tree/master/unstable/relative-pointer

**Comment by rdb** [comment]
I'm afraid I don't quite understand the nature of this issue, as we do not support Wayland at present.  Are you running into issues using Panda3D in Wayland using an emulation layer?  Or are you requesting Wayland support to be added to Panda3D with specific support for mouse control?  If you are simply documenting the relevant APIs for future reference, then I'm afraid I must close this as that isn't something actionable; Dropbox Paper would be a better place for such documentation.

**Comment by TheCheapestPixels** [comment]
I expect this program to move the mouse pointer to the center of the window each frame, but for me, it does nothing.

```
import sys

from direct.showbase.ShowBase import ShowBase


def center_mouse(task):
    if base.mouseWatcherNode.has_mouse():
        base.win.movePointer(
            0,
            base.win.getXSize() // 2,
            base.win.getYSize() // 2,
        )
    return task.cont


s = ShowBase()
s.disable_mouse()
s.accept('escape', sys.exit)
s.task_mgr.add(center_mouse)
s.run()
```

**Comment by rdb** [comment]
Could you add the output of `notify-level-x11display debug` for the record?

**Comment by phro** [comment]
To clarify above code works acceptably under x11, but fails when running with Wayland. Is there planned support for Wayland in the future?

**Comment by rdb** [comment]
I will try implementing a fallback for doing relative mouse using XInput2 if XF86DGA is not supported.  Maybe this will work better in Wayland.

**Comment by rdb** [comment]
I implemented a fallback relative mouse mode using XInput2, in d0337b8233c8ec388c0d623dcc9799c40def2d39.  XInput2 lets us get raw mouse deltas unconstrained by the window bounds, so combined with confining the cursor to the window, Panda can effectively emulate relative mouse mode. This lets you implement FPS-style mouselook without cursor warping (which isn't supported on Wayland).

I have tested this with Wayland and it seems to work.  All you need to do is request relative mouse mode from Panda.

I am closing this issue as fixed.  Wayland, by design, does not support cursor warping, but the above fix means you don't actually need it.
