### ISSUE TITLE
sfx.setTime() doesn't seem to function as intended.

### ISSUE THREAD

**Issue by NathanX-S** [panda3d/panda3d#770]
**Expected Behaviour**
Calling setTime on the OpenALAudioSound should skip it to the time provided but instead does nothing.

**Example**
```
from direct.showbase.ShowBase import ShowBase
base = ShowBase()
global time
time = 0
track = base.loader.loadMusic("ex2.ogg")
def pandaPaused():
	base.disableAllAudio()
	time = track.getTime()
	print(track.getTime())
def pandaRestarted():
	base.enableAllAudio()
	track.setTime(time)
	print(track.getTime())
base.accept('PandaPaused', pandaPaused)
base.accept('PandaRestarted', pandaRestarted)
track.setLoop(True)
track.setVolume(1.0)
track.play()
base.run()
```

**Expected Output**
```
2.092177152633667 - Closing window.
2.092177152633667 - Opening window.
```

**Actual Output**
```
2.092177152633667 - Closing window.
0.0 - Opening window.
```

I used the following ogg as an example. https://drive.google.com/open?id=1G1EK5WDEVexof_PsT-wEmVWeykU5-JfM

**Comment by rdb** [comment]
There are two problems in your example.
Firstly, the method that assigns the `time` needs to declare `global time`, otherwise it is assigning the time to a local variable named `time`, and setTime would always be receiving 0.

The second problem is that you need to call `play()` again after calling `setTime`.  According to the API documentation for `setTime`:
> The current time position will not change while the sound is playing; you must call play() again to effect the change.

**Comment by rdb** [comment]
I'm reopening this as a usability issue.  The manual actually contradicts this behaviour.  I also tested with the FMOD back-end, and it behaves as expected.
