### ISSUE TITLE
setuptools: TCL/Tk extra files are copied only for window platform

### ISSUE THREAD

**Issue by el-dee** [panda3d/panda3d#780]
In order to include TCL/TK in a binary, extra files and libraries are required, however setuptools copy those files only for the Windows platform and only when performed on Windows.

https://github.com/panda3d/panda3d/blob/f1b235e06594f4c0a2c028adfe2ef2241e4091e0/direct/src/dist/commands.py#L808

Without those extra files, TCL/TK does not initialize.

See forum thread for more details : https://discourse.panda3d.org/t/setuptools-and-tk/25206

**Comment by Moguri** [comment]
@rdb Do you remember why only Windows was supported for this? Were there actually issues on Linux and macOS, or is it just a matter of putting in the time to get the platforms running?

**Comment by rdb** [comment]
@Moguri It's because only on Windows do we have a chance of actually having deploy-time access to the Tcl/Tk files belonging to the same Python build.

On Linux, the version of Tcl/Tk shipping with the manylinux container will often not be the same as the version shipping on the Linux machine that we are deploying on, so we won't have the right data files.

What we should be doing is including the Tcl/Tk data files into the panda3d wheel (not my preferred solution, though maybe including them in a zip file is OK), or create a separate "tkinter" wheel that contains the Tcl/Tk stuff that can be downloaded by deploy-ng as needed.

At the time I was looking at this, I simply did not have time to do this so I only added support for the easy case.

**Comment by el-dee** [comment]
On Mac also there is I a compatibility problem,  I tried to manually copy the to files from the installed python but there were incompatibilities.  (though I did not spend a lot of time looking at the problem)

**Comment by rdb** [comment]
Fixed now on `release/1.10.x` branch. I have created separate wheels for tkinter which deploy-ng can get at:
https://archive.panda3d.org/thirdparty/tkinter/

Scripts to produce these wheels:
https://github.com/panda3d/tkinter

To use, you just have to add `tkinter` to `requirements.txt`. You also need to be using Python 3.6 or higher, because I can't be bothered to build wheels for unsupported versions of Python.
