### ISSUE TITLE
macOS: set profile for GLSL 3.2+

### ISSUE THREAD

**Issue by NathanX-S** [panda3d/panda3d#848]
reference:
https://stackoverflow.com/questions/20931528/shader-cant-be-compiled

**Comment by rdb** [comment]
This is already possible by adding `gl-version 3 2` to Config.prc.

**Comment by rdb** [comment]
For the record, in case this question comes up, we can't quite yet set this by default, because doing so enables the "core profile" which disables the fixed-function pipeline.  This means anything requiring shading more complex than a simple textured or coloured object will require a custom shader.

In the future, we will be providing better shaders by default, as well as the ability to automatically cross-compile shaders to older/newer OpenGL targets, and at that point we can reconsider making core-only OpenGL profiles the default.
