### ISSUE TITLE
TransparencyAttrib::M_dual should only be respected for fixed-function pipeline

### ISSUE THREAD

**Issue by CFSworks** [panda3d/panda3d#852]
The `TransparencyAttrib::M_dual` mode works by putting the affected geometry into both the `opaque` and `transparent` bins: the opaque parts require > ~99% alpha (and render without any blending applied), and the transparent parts require > 0% alpha (and render with the usual alpha blending). The main advantage to doing this is that it avoids writing invisible pixels to depth/stencil/etc. buffers. A secondary advantage is that this renders the fully-opaque pixels first, reducing the chances of depth-sorting artifacts.

The problem is that this requires use of the alpha test, which has been removed in OpenGL's core profile since discarding fragments with a shader is very easy to do. Therefore, it's workable (and saves duplicating draw calls) to use `M_alpha` mode and use a shader to avoid writing to the depth buffer for alpha=0.

The `m-dual` PRC variable can already be used to disable support for `M_dual` (causing a fallback to `M_alpha`), so resolving this issue should just involve adding an additional check to ask the GSG if alpha test is supported, and falling back to `M_alpha` mode if not.

It might also be worth defaulting `m-dual 0` and deprecating the `M_dual` mode. As well, we may have to figure out how to handle `M_binary`, which similarly requires an alpha test. But perhaps these may be topics for (a) separate issue report(s). Do `M_dual`/`M_binary` make sense in the modern graphics ecosystem?

**Comment by rdb** [comment]
What about the option of injecting an alpha test into shaders?  Once we have a SPIR-V-based pipeline, this should be doable—and in fact, this is likely what drivers did before the feature was deprecated.

Another option is to set a #define in shaders indicating whether alpha test should be enabled or not, and leave it up to users whether they respect it in their shaders.

**Comment by rdb** [comment]
For the record, M_alpha also enables alpha testing, to avoid writing invisible pixels to the depth/stencil buffers.  That is not a specific advantage of M_dual.

The argument for gutting TransparencyAttrib because most modes rely on shader support is valid, but note that it could actually be raised for many RenderAttribs, including TextureAttrib, MaterialAttrib, LightAttrib, ColorScaleAttrib, AuxBitplaneAttrib, AlphaTestAttrib, TexGenAttrib, TexMatrixAttrib, (most of) LightRampAttrib, ClipPlaneAttrib, RescaleNormalAttrib, and FogAttrib.  None of these attributes can be implemented in fixed-function in core OpenGL 3.2+.

I think that's a valid question to discuss: should RenderState just tightly wrap around graphics hardware state, or are higher-level structures that have to be implemented by custom shaders fair game?  If the former, we should pivot towards putting all the non-fixed-function state in a higher-level Material abstraction, one that is perhaps more customizable and less one-size-fits-all.

For alpha testing, I am still willing to implement a discard injection into the SPIR-V code of custom shaders, but I'm curious how others feel about this.
