### ISSUE TITLE
Shapekeys only load once (model-cache error)

### ISSUE THREAD

**Issue by janEntikan** [panda3d/panda3d#862]
-Run test.py, rotate around model to see a large belly. 
-Close
-Run test.py, rotate around model, it's gone. (reload and it's still gone)

Setting model_cache_dir to nothing fixes it.

[shapekey-modelcache-test.zip](https://github.com/panda3d/panda3d/files/4130683/shapekey-modelcache-test.zip)

**Comment by serkkz** [comment]
I don't see such a problem, I loaded it 3 times and watched the animation every time.

**Comment by rdb** [comment]
Yes, I can reproduce it; the character changes from fat to skinny when re-running it.

I'll investigate.

**Comment by rdb** [comment]
This is actually a bug in panda3d-gltf (and totally my fault), because when I implemented morph targets there, I exploited a particular loophole in the Panda3D API to not have the vertex column name for the morph targets match up with the slider name.  Panda3D "corrects" this mismatch when reading from .bam.

I think I should just fix this properly in panda3d-gltf.
