### ISSUE TITLE
Status of WebGL port?

### ISSUE THREAD

**Issue by deeplook** [panda3d/panda3d#887]
@rdb I'm new to Panda3d (and sad to have discovered it so late), but would like to use it inside Jupyter notebooks. So I'd appreciate a statement about WebGL support as I don't see it in the docs, yet, or on the README. I have seen the webgl-port branch, https://github.com/panda3d/panda3d/tree/webgl-port, but there also I don't know what to expect.

**Comment by Moguri** [comment]
Hopefully someone more knowledgeable on the mater can give a more detailed answer, but in the meantime, I will say this: it *is* possible to run Panda with WebGL and I have seen some demos. However, the process to deploy Panda apps to HTML5/WebGL is non-trivial and requires -- from my understanding -- a fair amount of manual work. I also do not know the current state of deploying Python Panda apps to WebGL.

**Comment by rdb** [comment]
The status is:
* It works, as proven by [these demos](https://discourse.panda3d.org/t/panda3d-webgl-port/14858), and by the fact that someone published [a game](https://wiphotos.itch.io/asteroids) with it
* Building an application for the WebGL port of Panda is not at all trivial, requiring building Panda from source using emscripten, the use of a modified version of pfreeze and some C and compiler knowledge to hook it up.
* The branch has not been updated for quite a while
* I have not gotten it to work with WebAssembly yet.

The main remaining challenge is getting a pipeline up to build applications for it with our deployment system, without needing to go through all the hoops.  This will require building Panda3D in a more modular fashion, probably using WebAssembly, but this will probably require dynamic linking, which is riddled with caveats in emscripten.  It will also require finding a way to ship the Python bytecode and assets in web applications.

**Comment by pmp-p** [comment]
Also if you have success building for wasm and as rdb said it's far from trivial :
you should not use threads and if you want network/filesystems you'll have to use an asyncio flavour, since threads support is not yet in wasm mvp specification.

If you are not ready to write fully async code you'll have a 10x performance loss or worse using emscripten wasm vm pre-emption.

so yeah it can work, even very well ... but with a cost.

also note that wasm (not asm.js) requires the use of python 3.8+ no less

**Comment by deeplook** [comment]
I don't think I'm interested in "applications", but only in visualizations inside Jupyter notebooks. Are the existing demos helpful in any way for that end?

**Comment by rdb** [comment]
I hadn't really considered Jupyter notebooks.  I do not know enough about them to know how to integrate them.

I do know, however, possible to construct something that will run arbitrary Panda code on the fly, as proven by this:
http://rdb.name/panda3d-webgl/editor.html
But it will take some build system finagling to put it together.

**Comment by pmp-p** [comment]
@deeplook, i don't know jupyter notebooks, either, but the dynamic way used to feed (micro)python in that particular sample https://cdn.statically.io/gh/littlevgl/lv_micropython/ef943a1ab40b32a8a77059d6e833a440446c51e8/ports/javascript/lvgl_editor.html?env=dev&script=https://raw.githubusercontent.com/littlevgl/lv_binding_micropython/dev-6.0/examples/chart_anim_example.py  could also be used with Panda3D as a display.

**Comment by pmp-p** [comment]
*if* dynamic linking could work again on emscripten, then it would probably nice to use pyodide as soon as they switch to 3.8
that could happen see https://github.com/iodide-project/pyodide/issues/635#issuecomment-613755145 
and then you would have notebook support i guess

for now clang 10 & 11 crash very early on Panda3D building, C++ support is not as good as C apparently.

**Comment by Moguri** [comment]
Has the question in this issue been answered then? If so, can this be closed? Maybe we want to create a new issue (or multiple issues with a label) that enumerates some of the remaining tasks for Panda3D WebGL support? Although most of it stems around "how to run Python well on the web."

**Comment by deeplook** [comment]
Well, maybe notebook support can be put on some kind of roadmap or related issues be created that lead to provide notebook support. For now the correct status seems to be "there is no proper support", and maybe it's ok to close this.

**Comment by pmp-p** [comment]
@deeplook, maybe you should explain to us a bit **what kind of (proper) support requires a notebook**.
 I'm surely wrong but to me "jupyter" stuff seems  yet another RPC so it has little to do with Panda3D which only requires ... an html5 canvas and wasm support from browser.

Since the pyodide thread about CPython 3.8.2 (dynamic) is still hanging too i don't see libpanda.wasm loading into it yet without someone bridging the gap.

FYI i managed to enable dynamic linking ( in a MicroPython/Pycopy project) again but Panda3D does not strictly requires that to be used it with CPython and it could complicate things for Panda3D.

Maybe come on irc/discord and ask around who know his way with jupyter notebooks. Or join me on pyodide's gitter to give some info about loading Panda3D.

 Actually i'd say if if there's any support or roadmap directions, it can only be **unofficial** until things are clear and workload evaluated by the mainteners of Panda3D.

**Comment by rdb** [comment]
*Does* Jupyter Notebook actually require WebGL support?  I opened an online Jupyter notebook and it's just running all the commands on a Linux installation.  It looks like it's actually running the Python code in a separate kernel process.

I've only taken a cursory look, but if I'm not mistaken, it looks like we would actually need to write a [front-end extension](https://jupyter-notebook.readthedocs.io/en/stable/extending/frontend_extensions.html) that is either able to communicate with the local Panda process to render the scene to a buffer and transfer the image to the browser, or, receives the output of the scene graph or cull process and does all the rendering via the WebGL port.  It would also have to get the input back from the browser to the kernel process.

The former is probably the least amount of work, and would not depend on the WebGL port whatsoever.  If you just need static renders you can probably use [this facility](http://ipython.org/ipython-doc/2/api/generated/IPython.core.display.html#IPython.core.display.Image) already to render the Panda result to a buffer and get it to show up in the front-end.

**Comment by deeplook** [comment]
I don't know enough about WebGL etc. but maybe it's worth taking a look at how other 3D projects are integrating into the Jupyter universe, e.g. https://github.com/InsightSoftwareConsortium/itkwidgets.

**Comment by rdb** [comment]
I'm marking this closed as there is no clear actionable item here.
