### ISSUE TITLE
Feature request: Allow unbuffered or line-buffered output to log file in deploy-stub

### ISSUE THREAD

**Issue by el-dee** [panda3d/panda3d#947]
Still from https://discourse.panda3d.org/t/deploy-ng-stdout-is-not-present-in-log-on-windows/24676/11 I would be a nice feature to be able to configure the value of PYTHONUNBUFFERED either from the application (through a PRC flag ?) or via a deploy-ng configuration flag.

Without setting PYTHONUNBUFFERED to 1, the error log from Panda is directly dumped into the log file while the app output is buffered and so no longer correlated to the Panda output which make debugging using logs quite complicated.

**Comment by el-dee** [comment]
I forgot to add that an easy workaround is to reopen stdin with the wanted buffering mode

    import os,sys
    sys.stdout = os.fdopen(sys.stdout.fileno(), 'w', buffering=1)

0 is for unbuffered, 1 for line buffered and > 1 for block buffered.

I'm not sure if adding complexity in deploy-ng just for one line of code is worth the effort.

**Comment by rdb** [comment]
Would it be acceptable if we configured deploy-stub to always use line buffering?

**Comment by el-dee** [comment]
Imho this is the most useful mode for the logs of an app. With block buffered model you can not really follow in real-time what's going on in your app while it's running, but it's the default mode for Windows.

**Comment by rdb** [comment]
I would be for making line buffering the default going forward.  I think we just need to insert a `setbuf` call in deploy-stub.c.

**Comment by rdb** [comment]
As it turns out, it's not quite that easy because Windows doesn't implement line buffering.  Python does have its own line buffering that can be used (which basically forces a flush on any written newline).  However, Python overrides this to be disabled when the output stream is not a TTY:
https://github.com/python/cpython/blob/3a150c77c31da240f1b92cab9ec74f1fa701b869/Python/pylifecycle.c#L1781

However, Python 3.7 makes it possible to activate this after the fact fairly elegantly, using this code:
```python
sys.stdout.reconfigure(line_buffering=True)
sys.stderr.reconfigure(line_buffering=True)
```
So I think I'll just make deploy-stub call this automatically.  It doesn't help for Python 3.6, though.  Do you think we need a solution that will work in older versions?

**Comment by rdb** [comment]
As it turns out older Python 3 versions have the same textio implementation, just without the `reconfigure()` convenience, so I simply put a slightly hackier case in for those versions that sets the property directly, which is what `reconfigure()` would have otherwise done anyway.
