### ISSUE TITLE
libffi-7.dll is missing in 1.10.x wheels

### ISSUE THREAD

**Issue by el-dee** [panda3d/panda3d#983]
## Description

With Panda3D 1.10.x, as _ctypes.pyd in Python 3.8 depends on libffi-7.dll. When building an app that uses ctypes in a Python 3.8 env, the app aborts immediately as _ctypes.pyd can not found libffi-7.dll

## Steps to Reproduce

* Clone https://github.com/el-dee/panda3d-openvr.git
* Go to samples/ralph
* Run python3 setup.py bdist_apps -p win_amd64
* Try to run Ralph.exe on any Windows machine, it will fails immediately

Note that this seems to be fixed in master branch in https://github.com/panda3d/panda3d/commit/2cb5b95d0823e816bb187d5aff4dce653e78197e I don't see why it should not be also included in 1.10.x (I tested with 1.10.7.dev49+opt and the problem still occurs)

## Environment
 * Operating system: Linux
 * System architecture: x86_64
 * Panda3D version: 1.10.7 : f7cef5c2841937304c8da03221ccd717302625f2
 * Installation method: built from source
 * Python version (if using Python): Python 3.8.2
 * Compiler (if using C++): None

**Comment by rdb** [comment]
This was, actually, committed to the 1.10 branch.  I am not sure why GitHub is showing it otherwise.  dev49 corresponds to that commit, so it should contain libffi-7.dll.

Indeed, if I grab and unzip [panda3d-1.10.7.dev49+opt-cp38-cp38-win_amd64.whl](https://buildbot.panda3d.org/downloads/2cb5b95d0823e816bb187d5aff4dce653e78197e/opt/panda3d-1.10.7.dev49+opt-cp38-cp38-win_amd64.whl#md5=a3b1709a4fa0be127f2768cc71af0df3), libffi-7.dll is present.  Could you make sure that it is indeed using that version and not a cached older one?

**Comment by el-dee** [comment]
Ok, the problem was  between the chair and the keyboard. The wheel was indeed dev49, I checked in build/__whl_cache__ the file timestamp is older than the generated app. I redid the whole generation today and this time it works and libffi is present. So, when moving around the app to test it, I probably messed up and reused an older version build with 1.10.6 instead of testing the freshly made app :(
